# core data

> core utilities for data processing: 
> datetime processing, time zone processing, validity, filtering

In [2]:
#| default_exp data.utils

In [3]:
#| hide
from nbdev.showdoc import *

In [4]:
#| hide
from IPython.core.interactiveshell import InteractiveShell

In [5]:
#| export
from datetime import datetime
import pytz

In [6]:
#| export
from sqlalchemy import MetaData, create_engine, asc, desc, and_, or_, not_, case, extract, cast, Numeric, text, distinct, Column, update, bindparam, Engine
from sqlalchemy.types import DateTime, Date, Time, String
from sqlalchemy.schema import *
from sqlalchemy.sql import func, Selectable, select, union, insert
from sqlalchemy.engine.row import Row
from sqlalchemy.orm import Session
from sqlalchemy.orm import sessionmaker
import requests
from tqdm.notebook import tqdm
import pandas as pd
import numpy as np

In [7]:
sqlite_eng = create_engine('sqlite:///../data/price_tokyo.db', echo=False)

In [50]:
#| export
pd.options.mode.chained_assignment = None

In [51]:

InteractiveShell.ast_node_interactivity = "all"

In [69]:
#| export
def validate_datetime(date_string, format_string):
    """
    Validates if a string is a valid datetime according to the given format.
    """

    try:
        datetime.strptime(date_string, format_string)
        return True
    except ValueError:
        return False
    
def validate_datetime_in_iso_format(date_text):
        try:
            datetime.fromisoformat(date_text)
            return True
        except ValueError:
            # raise ValueError("Incorrect data format, should be YYYY-MM-DD")
            return False

In [70]:
# Example usage
date_strings = [
    "2023-12-25 24:00:00",
    "2023-12-25 12:60:00.12",
    "2023-12-25 12:10:00",
    "2023-12-25 23:00:00",
    "2011-11-04",
    "20111104",
    "2011-11-04T00:05:23",
    "2011-11-04T00:05:23.283185",
    "20111104T000523",
    "20111104T000523.283185",
    "2011-11-04T00:05:23Z",
    "2011-11-04T00:05:23.283185+08:00",
    "2011-11-04T00:05:23+08:00",
    ]
format_string = "%Y-%m-%d"

for s in date_strings:
    if validate_datetime_in_iso_format(s):
        print(f"{s} is Valid datetime string")
    else:
        print(f"{s} is Invalid datetime string")

2023-12-25 24:00:00 is Invalid datetime string
2023-12-25 12:60:00.12 is Invalid datetime string
2023-12-25 12:10:00 is Valid datetime string
2023-12-25 23:00:00 is Valid datetime string
2011-11-04 is Valid datetime string
20111104 is Valid datetime string
2011-11-04T00:05:23 is Valid datetime string
2011-11-04T00:05:23.283185 is Valid datetime string
20111104T000523 is Valid datetime string
20111104T000523.283185 is Valid datetime string
2011-11-04T00:05:23Z is Valid datetime string
2011-11-04T00:05:23.283185+08:00 is Valid datetime string
2011-11-04T00:05:23+08:00 is Valid datetime string

In [71]:
df_datetime_str = pd.DataFrame(date_strings)
df_datetime_str.columns = ['datetime']
# df_datetime_str
df_datetime_str['validity'] = df_datetime_str.apply(lambda x: validate_datetime_in_iso_format(x.iloc[0]), axis=1)
df_datetime_str

                            datetime  validity
0                2023-12-25 24:00:00     False
1             2023-12-25 12:60:00.12     False
2                2023-12-25 12:10:00      True
3                2023-12-25 23:00:00      True
4                         2011-11-04      True
5                           20111104      True
6                2011-11-04T00:05:23      True
7         2011-11-04T00:05:23.283185      True
8                    20111104T000523      True
9             20111104T000523.283185      True
10              2011-11-04T00:05:23Z      True
11  2011-11-04T00:05:23.283185+08:00      True
12         2011-11-04T00:05:23+08:00      True

In [72]:
df_datetime = df_datetime_str[df_datetime_str.apply(lambda x: validate_datetime_in_iso_format(x.iloc[0]), axis=1)]
df_datetime

                            datetime  validity
2                2023-12-25 12:10:00      True
3                2023-12-25 23:00:00      True
4                         2011-11-04      True
5                           20111104      True
6                2011-11-04T00:05:23      True
7         2011-11-04T00:05:23.283185      True
8                    20111104T000523      True
9             20111104T000523.283185      True
10              2011-11-04T00:05:23Z      True
11  2011-11-04T00:05:23.283185+08:00      True
12         2011-11-04T00:05:23+08:00      True

In [73]:
df_datetime_invalid = df_datetime_str[df_datetime_str.apply(lambda x: not validate_datetime_in_iso_format(x.iloc[0]), axis=1)]
df_datetime_invalid

                 datetime  validity
0     2023-12-25 24:00:00     False
1  2023-12-25 12:60:00.12     False

In [74]:
df_datetime['datetime']

2                  2023-12-25 12:10:00
3                  2023-12-25 23:00:00
4                           2011-11-04
5                             20111104
6                  2011-11-04T00:05:23
7           2011-11-04T00:05:23.283185
8                      20111104T000523
9               20111104T000523.283185
10                2011-11-04T00:05:23Z
11    2011-11-04T00:05:23.283185+08:00
12           2011-11-04T00:05:23+08:00
Name: datetime, dtype: object

In [75]:
# df_datetime_str.apply(lambda x: validate_datetime_in_iso_format(x.iloc[0]), axis=1)
df_datetime1 = df_datetime.apply(lambda x: datetime.fromisoformat(x['datetime']), axis=1)
df_datetime1.name = 'datetime'
df_datetime1

2                  2023-12-25 12:10:00
3                  2023-12-25 23:00:00
4                  2011-11-04 00:00:00
5                  2011-11-04 00:00:00
6                  2011-11-04 00:05:23
7           2011-11-04 00:05:23.283185
8                  2011-11-04 00:05:23
9           2011-11-04 00:05:23.283185
10           2011-11-04 00:05:23+00:00
11    2011-11-04 00:05:23.283185+08:00
12           2011-11-04 00:05:23+08:00
Name: datetime, dtype: object

In [76]:
df_datetime1.loc[0:8]

2           2023-12-25 12:10:00
3           2023-12-25 23:00:00
4           2011-11-04 00:00:00
5           2011-11-04 00:00:00
6           2011-11-04 00:05:23
7    2011-11-04 00:05:23.283185
8           2011-11-04 00:05:23
Name: datetime, dtype: object

In [77]:
df_no_tz = pd.to_datetime(df_datetime1.loc[0:8])
df_no_tz

2   2023-12-25 12:10:00.000000
3   2023-12-25 23:00:00.000000
4   2011-11-04 00:00:00.000000
5   2011-11-04 00:00:00.000000
6   2011-11-04 00:05:23.000000
7   2011-11-04 00:05:23.283185
8   2011-11-04 00:05:23.000000
Name: datetime, dtype: datetime64[ns]

In [78]:
#| export
def get_timezone_abbreviation(timezone_name):
    timezone = pytz.timezone(timezone_name)
    now = datetime.now(timezone)
    return now.strftime("%Z")

def validate_timezone_in_iana(timezone_name):
    return timezone_name in pytz.all_timezones

In [79]:

time_zone_strings = [
    'Eastern Standard Time',
    'Eastern Daylight Time',
    'US/Eastern',
    'US/Daylight',
    'Asia/Shanghai',
    'Asia/Mumbai',
    'America/New_York',
    'Europe/London',
    'America/Los_Angeles',
    'Asia/Kolkata',
    'Europe/London',
    'Asia/Hong_Kong',
    'Asia/Tokyo',
]
df_timezone_str = pd.DataFrame(time_zone_strings)
df_timezone_str.columns = ['timezone']

# df_datetime_str
df_timezone_str['validity'] = df_timezone_str.apply(lambda x: validate_timezone_in_iana(x['timezone']), axis=1)
df_timezone_str

                 timezone  validity
0   Eastern Standard Time     False
1   Eastern Daylight Time     False
2              US/Eastern      True
3             US/Daylight     False
4           Asia/Shanghai      True
5             Asia/Mumbai     False
6        America/New_York      True
7           Europe/London      True
8     America/Los_Angeles      True
9            Asia/Kolkata      True
10          Europe/London      True
11         Asia/Hong_Kong      True
12             Asia/Tokyo      True

In [80]:
#| export
timezone_fixing_map = {'Eastern Standard Time': 'US/Eastern',
                       'Eastern Daylight Time': 'US/Eastern',
                       'US/Daylight': 'US/Eastern',
                       'Asia/Mumbai': 'Asia/Calcutta',}

In [81]:
#| export
def fix_timezone(timezone_name):
    return timezone_fixing_map.get(timezone_name, timezone_name)

In [82]:
for tz in time_zone_strings:
    print(f"{tz} -> {fix_timezone(tz)} -> {get_timezone_abbreviation(fix_timezone(tz))}")

Eastern Standard Time -> US/Eastern -> EDT
Eastern Daylight Time -> US/Eastern -> EDT
US/Eastern -> US/Eastern -> EDT
US/Daylight -> US/Eastern -> EDT
Asia/Shanghai -> Asia/Shanghai -> CST
Asia/Mumbai -> Asia/Calcutta -> IST
America/New_York -> America/New_York -> EDT
Europe/London -> Europe/London -> BST
America/Los_Angeles -> America/Los_Angeles -> PDT
Asia/Kolkata -> Asia/Kolkata -> IST
Europe/London -> Europe/London -> BST
Asia/Hong_Kong -> Asia/Hong_Kong -> HKT
Asia/Tokyo -> Asia/Tokyo -> JST

In [83]:

df_timezone_unidentified = df_timezone_str[df_timezone_str.apply(lambda x: not validate_timezone_in_iana(x['timezone']), axis=1)]
df_timezone_unidentified

                timezone  validity
0  Eastern Standard Time     False
1  Eastern Daylight Time     False
3            US/Daylight     False
5            Asia/Mumbai     False

In [84]:

df_timezone_unidentified.apply(lambda x: fix_timezone(x['timezone']), axis=1)

0       US/Eastern
1       US/Eastern
3       US/Eastern
5    Asia/Calcutta
dtype: object

In [85]:
df_timezone_str['timezone_fixed'] = df_timezone_str.apply(lambda x: fix_timezone(x['timezone']), axis=1)
df_timezone_str

                 timezone  validity       timezone_fixed
0   Eastern Standard Time     False           US/Eastern
1   Eastern Daylight Time     False           US/Eastern
2              US/Eastern      True           US/Eastern
3             US/Daylight     False           US/Eastern
4           Asia/Shanghai      True        Asia/Shanghai
5             Asia/Mumbai     False        Asia/Calcutta
6        America/New_York      True     America/New_York
7           Europe/London      True        Europe/London
8     America/Los_Angeles      True  America/Los_Angeles
9            Asia/Kolkata      True         Asia/Kolkata
10          Europe/London      True        Europe/London
11         Asia/Hong_Kong      True       Asia/Hong_Kong
12             Asia/Tokyo      True           Asia/Tokyo

In [86]:

df_timezone = df_timezone_str[df_timezone_str.apply(lambda x: validate_timezone_in_iana(x['timezone_fixed']), axis=1)]
df_timezone

                 timezone  validity       timezone_fixed
0   Eastern Standard Time     False           US/Eastern
1   Eastern Daylight Time     False           US/Eastern
2              US/Eastern      True           US/Eastern
3             US/Daylight     False           US/Eastern
4           Asia/Shanghai      True        Asia/Shanghai
5             Asia/Mumbai     False        Asia/Calcutta
6        America/New_York      True     America/New_York
7           Europe/London      True        Europe/London
8     America/Los_Angeles      True  America/Los_Angeles
9            Asia/Kolkata      True         Asia/Kolkata
10          Europe/London      True        Europe/London
11         Asia/Hong_Kong      True       Asia/Hong_Kong
12             Asia/Tokyo      True           Asia/Tokyo

In [87]:
# extract invalid data
df_timezone_invalid = df_timezone_str[df_timezone_str.apply(lambda x: not validate_timezone_in_iana(x.iloc[0]), axis=1)]
df_timezone_invalid

                timezone  validity timezone_fixed
0  Eastern Standard Time     False     US/Eastern
1  Eastern Daylight Time     False     US/Eastern
3            US/Daylight     False     US/Eastern
5            Asia/Mumbai     False  Asia/Calcutta

In [88]:
df_abbr = df_timezone.apply(lambda x: get_timezone_abbreviation(x.loc['timezone_fixed']), axis=1)
df_abbr.name = 'abbr'
df_abbr

0     EDT
1     EDT
2     EDT
3     EDT
4     CST
5     IST
6     EDT
7     BST
8     PDT
9     IST
10    BST
11    HKT
12    JST
Name: abbr, dtype: object

In [89]:
df_timezone

                 timezone  validity       timezone_fixed
0   Eastern Standard Time     False           US/Eastern
1   Eastern Daylight Time     False           US/Eastern
2              US/Eastern      True           US/Eastern
3             US/Daylight     False           US/Eastern
4           Asia/Shanghai      True        Asia/Shanghai
5             Asia/Mumbai     False        Asia/Calcutta
6        America/New_York      True     America/New_York
7           Europe/London      True        Europe/London
8     America/Los_Angeles      True  America/Los_Angeles
9            Asia/Kolkata      True         Asia/Kolkata
10          Europe/London      True        Europe/London
11         Asia/Hong_Kong      True       Asia/Hong_Kong
12             Asia/Tokyo      True           Asia/Tokyo

In [90]:
# df_timezone_str['validity'] = df_timezone_str.apply(lambda x: validate_timezone_in_iana(x.iloc[0]), axis=1)
# df_timezone['abbr'] = df_timezone.apply(lambda x: get_timezone_abbreviation(x.iloc[0]), axis=1)
# df_timezone.apply(lambda x: get_timezone_abbreviation(x.iloc[0]), axis=1)
df_timezone.loc[:,'abbr'] = df_abbr
df_timezone
# df_timezone

                 timezone  validity       timezone_fixed abbr
0   Eastern Standard Time     False           US/Eastern  EDT
1   Eastern Daylight Time     False           US/Eastern  EDT
2              US/Eastern      True           US/Eastern  EDT
3             US/Daylight     False           US/Eastern  EDT
4           Asia/Shanghai      True        Asia/Shanghai  CST
5             Asia/Mumbai     False        Asia/Calcutta  IST
6        America/New_York      True     America/New_York  EDT
7           Europe/London      True        Europe/London  BST
8     America/Los_Angeles      True  America/Los_Angeles  PDT
9            Asia/Kolkata      True         Asia/Kolkata  IST
10          Europe/London      True        Europe/London  BST
11         Asia/Hong_Kong      True       Asia/Hong_Kong  HKT
12             Asia/Tokyo      True           Asia/Tokyo  JST

In [91]:

df_utc_offset = (df_timezone.apply(lambda x: datetime.now(pytz.timezone(x.loc['timezone_fixed'])), axis=1)
                            .apply(lambda x: x.strftime('%z')))
df_utc_offset.name = 'utc_offset'
df_utc_offset

0     -0400
1     -0400
2     -0400
3     -0400
4     +0800
5     +0530
6     -0400
7     +0100
8     -0700
9     +0530
10    +0100
11    +0800
12    +0900
Name: utc_offset, dtype: object

In [92]:

df_timezone.loc[:,'utc_offset'] = df_utc_offset
df_timezone

                 timezone  validity       timezone_fixed abbr utc_offset
0   Eastern Standard Time     False           US/Eastern  EDT      -0400
1   Eastern Daylight Time     False           US/Eastern  EDT      -0400
2              US/Eastern      True           US/Eastern  EDT      -0400
3             US/Daylight     False           US/Eastern  EDT      -0400
4           Asia/Shanghai      True        Asia/Shanghai  CST      +0800
5             Asia/Mumbai     False        Asia/Calcutta  IST      +0530
6        America/New_York      True     America/New_York  EDT      -0400
7           Europe/London      True        Europe/London  BST      +0100
8     America/Los_Angeles      True  America/Los_Angeles  PDT      -0700
9            Asia/Kolkata      True         Asia/Kolkata  IST      +0530
10          Europe/London      True        Europe/London  BST      +0100
11         Asia/Hong_Kong      True       Asia/Hong_Kong  HKT      +0800
12             Asia/Tokyo      True           Asia/Tokyo  JST      +0900

In [93]:
for tz in df_timezone.loc[:,'timezone_fixed']:
    print(f"{tz}: {datetime.now(pytz.timezone(tz))} - {datetime.now(pytz.timezone(tz)).strftime('%Z')}, {datetime.now(pytz.timezone(tz)).strftime('%z')}")

US/Eastern: 2024-10-25 03:16:51.399613-04:00 - EDT, -0400
US/Eastern: 2024-10-25 03:16:51.399682-04:00 - EDT, -0400
US/Eastern: 2024-10-25 03:16:51.399705-04:00 - EDT, -0400
US/Eastern: 2024-10-25 03:16:51.399725-04:00 - EDT, -0400
Asia/Shanghai: 2024-10-25 15:16:51.399742+08:00 - CST, +0800
Asia/Calcutta: 2024-10-25 12:46:51.399763+05:30 - IST, +0530
America/New_York: 2024-10-25 03:16:51.399783-04:00 - EDT, -0400
Europe/London: 2024-10-25 08:16:51.399802+01:00 - BST, +0100
America/Los_Angeles: 2024-10-25 00:16:51.399821-07:00 - PDT, -0700
Asia/Kolkata: 2024-10-25 12:46:51.399839+05:30 - IST, +0530
Europe/London: 2024-10-25 08:16:51.399857+01:00 - BST, +0100
Asia/Hong_Kong: 2024-10-25 15:16:51.399874+08:00 - HKT, +0800
Asia/Tokyo: 2024-10-25 16:16:51.399893+09:00 - JST, +0900

In [94]:
for dt,tz in zip(df_no_tz, df_timezone.loc[:,'timezone_fixed']):
    print(f"{dt}: {dt.tz_localize(tz)}, as {dt.tz_localize(tz).astimezone('utc')}")

2023-12-25 12:10:00: 2023-12-25 12:10:00-05:00, as 2023-12-25 17:10:00+00:00
2023-12-25 23:00:00: 2023-12-25 23:00:00-05:00, as 2023-12-26 04:00:00+00:00
2011-11-04 00:00:00: 2011-11-04 00:00:00-04:00, as 2011-11-04 04:00:00+00:00
2011-11-04 00:00:00: 2011-11-04 00:00:00-04:00, as 2011-11-04 04:00:00+00:00
2011-11-04 00:05:23: 2011-11-04 00:05:23+08:00, as 2011-11-03 16:05:23+00:00
2011-11-04 00:05:23.283185: 2011-11-04 00:05:23.283185+05:30, as 2011-11-03 18:35:23.283185+00:00
2011-11-04 00:05:23: 2011-11-04 00:05:23-04:00, as 2011-11-04 04:05:23+00:00

In [95]:
from zoneinfo import ZoneInfo

In [96]:
for dt,tz in zip(df_no_tz, df_timezone.loc[:,'timezone_fixed']):
    tz_zone = pytz.timezone(tz)
    print(f"{dt}: {tz_zone.localize(dt)}, or {dt.replace(tzinfo=tz_zone)}, or {dt.tz_localize(tz)}, as {dt.tz_localize(tz).astimezone('utc')}")

2023-12-25 12:10:00: 2023-12-25 12:10:00-05:00, or 2023-12-25 12:10:00-05:00, or 2023-12-25 12:10:00-05:00, as 2023-12-25 17:10:00+00:00
2023-12-25 23:00:00: 2023-12-25 23:00:00-05:00, or 2023-12-25 23:00:00-05:00, or 2023-12-25 23:00:00-05:00, as 2023-12-26 04:00:00+00:00
2011-11-04 00:00:00: 2011-11-04 00:00:00-04:00, or 2011-11-04 00:00:00-04:00, or 2011-11-04 00:00:00-04:00, as 2011-11-04 04:00:00+00:00
2011-11-04 00:00:00: 2011-11-04 00:00:00-04:00, or 2011-11-04 00:00:00-04:00, or 2011-11-04 00:00:00-04:00, as 2011-11-04 04:00:00+00:00
2011-11-04 00:05:23: 2011-11-04 00:05:23+08:00, or 2011-11-04 00:05:23+08:00, or 2011-11-04 00:05:23+08:00, as 2011-11-03 16:05:23+00:00
2011-11-04 00:05:23.283185: 2011-11-04 00:05:23.283185+05:30, or 2011-11-04 00:05:23.283185+05:30, or 2011-11-04 00:05:23.283185+05:30, as 2011-11-03 18:35:23.283185+00:00
2011-11-04 00:05:23: 2011-11-04 00:05:23-04:00, or 2011-11-04 00:05:23-04:00, or 2011-11-04 00:05:23-04:00, as 2011-11-04 04:05:23+00:00

# Convert csv to sqlite db

In [97]:
csv_file_path = '../data/price_training_tokyo.csv'
chunk_size = 10000
total_lines = sum(1 for line in open(csv_file_path))
print(total_lines)

67441

In [98]:
sample = pd.read_csv(csv_file_path, index_col='dispatch_id', nrows=5)
sample

,ride_id,trip_count,ride_inserted_at,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,passenger_count,luggage_count,...,start_place,start_lng,start_ltt,end_place_id,end_place,end_lng,end_ltt,vehicle_class_id,vehicle_class,row_num
dispatch_id,,,,,,,,,,,,,,,,,,,,,
4680,2166988,1,2020-10-29 21:41:00.000000,1604239200,2020-11-01 23:00,Japan Standard Time,NaN,NaN,1,3,...,Narita International Airport,140.392850,35.771987,2040,Hotel Main Kanda,139.769481,35.689175,1,Sedan,1
4724,2167009,1,2020-11-01 02:16:12.000000,1604239200,2020-11-01 23:00,Japan Standard Time,NaN,NaN,1,3,...,Narita International Airport,140.392850,35.771987,2057,Koto City,139.817452,35.672775,1,Sedan,1
6351,2167772,1,2020-12-23 14:01:24.000000,1608868800,2020-12-25 13:00,Japan Standard Time,NaN,NaN,1,3,...,Narita International Airport,140.392850,35.771987,2691,1 Chome-3 Ishikawacho,139.683002,35.601995,1,Sedan,1
12562,2171080,1,2021-04-21 23:15:35.000000,1619388000,2021-04-26 07:00,Japan Standard Time,NaN,NaN,4,10,...,Navy Gateway Inn & Suites,139.668106,35.284527,81,"Tokyo International Airport,",139.779839,35.549393,10,Minibus-12,1
25940,2177878,1,2021-06-22 04:49:42.000000,1624442400,2021-06-23 19:00,Asia/Tokyo,NaN,NaN,2,3,...,"Tokyo International Airport,",139.779839,35.549393,8327,Comforia Shinjuku Eastside Tower,139.708205,35.696093,2,Business Sedan,1

In [ ]:
for chunk in tqdm(pd.read_csv(csv_file_path, index_col='dispatch_id', chunksize=chunk_size), total=total_lines//chunk_size +1):
# for chunk in tqdm(pd.read_csv(csv_file_path, chunksize=chunk_size), total=total_lines//chunk_size +1):
    data = np.empty((chunk.shape[0],), dtype=[('route_start','U'), ('route_end','U')])
    df_append = pd.DataFrame(index=chunk.index, data=data)
    chunk = pd.concat([chunk, df_append], axis = 1)
    # chunk = chunk.convert_dtypes()
    chunk.to_sql('price_training_tokyo', sqlite_eng, if_exists= 'append',index=True)

  0%|          | 0/7 [00:00<?, ?it/s]

10000

10000

10000

10000

10000

10000

7440

## Find invalid timestamps

In [9]:
sql_eng = create_engine('sqlite:///../data/price_tokyo.db', echo=False)
sql_conn = sql_eng.connect()
sql_metadata = MetaData()
Sql_Session = sessionmaker(bind=sql_eng)
sql_session = Sql_Session()

In [10]:
 
# dispatch_routes_t = Table('dispatch_feature_routes_2324_sa_fix', sql_metadata3, autoload_with=sql_eng2)
dispatch_routes_t = Table('price_training_tokyo', sql_metadata, autoload_with=sql_eng)
total_rows = sql_session.query(dispatch_routes_t).count()
print(total_rows)

df_dispatch_routes = pd.read_sql(select(dispatch_routes_t), sql_conn, index_col='dispatch_id')  #sqlite3
df_dispatch_routes

67432

,ride_id,trip_count,ride_inserted_at,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,passenger_count,luggage_count,...,start_ltt,end_place_id,end_place,end_lng,end_ltt,vehicle_class_id,vehicle_class,row_num,route_start,route_end
dispatch_id,,,,,,,,,,,,,,,,,,,,,
4680,2166988,1,2020-10-29 21:41:00.000000,1604239200,2020-11-01 23:00,Japan Standard Time,None,None,1.0,3.0,...,35.771987,2040.0,Hotel Main Kanda,139.769481,35.689175,1.0,Sedan,1,,
4724,2167009,1,2020-11-01 02:16:12.000000,1604239200,2020-11-01 23:00,Japan Standard Time,None,None,1.0,3.0,...,35.771987,2057.0,Koto City,139.817452,35.672775,1.0,Sedan,1,,
6351,2167772,1,2020-12-23 14:01:24.000000,1608868800,2020-12-25 13:00,Japan Standard Time,None,None,1.0,3.0,...,35.771987,2691.0,1 Chome-3 Ishikawacho,139.683002,35.601995,1.0,Sedan,1,,
12562,2171080,1,2021-04-21 23:15:35.000000,1619388000,2021-04-26 07:00,Japan Standard Time,None,None,4.0,10.0,...,35.284527,81.0,"Tokyo International Airport,",139.779839,35.549393,10.0,Minibus-12,1,,
25940,2177878,1,2021-06-22 04:49:42.000000,1624442400,2021-06-23 19:00,Asia/Tokyo,None,None,2.0,3.0,...,35.549393,8327.0,Comforia Shinjuku Eastside Tower,139.708205,35.696093,2.0,Business Sedan,1,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2829232,3520308,1,2024-06-08 08:51:56.000000,1718791200,2024-06-19 19:00,Asia/Tokyo,None,None,3.0,5.0,...,35.764702,1719273.0,"Royal Park Hotel, 2 Chome-1-1 Nihonbashi-Kakig...",139.786632,35.682320,4.0,Business SUV,1,,
2841098,3463254,1,2024-05-11 20:20:07.000000,1719082800,2024-06-23 04:00,Asia/Tokyo,None,None,6.0,8.0,...,35.697808,1607831.0,NRT,140.386002,35.764702,5.0,Minibus-8,1,,
2923399,3409801,2,2024-04-18 15:16:49.000000,1719022800,2024-06-22 11:20,Asia/Tokyo,2024-07-10 07:20,Asia/Tokyo,6.0,0.0,...,35.771987,1502246.0,Osanbashi Pier Building,139.646463,35.449534,5.0,Minibus-8,1,,
3285060,3418096,1,2024-04-22 10:42:20.000000,1728774000,2024-10-13 08:00,Asia/Tokyo,None,None,8.0,8.0,...,35.770178,1518639.0,The B Shimbashi,139.753579,35.667581,5.0,Minibus-8,1,,
3335943,3442807,2,2024-05-02 05:23:31.000000,1729247400,2024-10-18 19:30,Asia/Tokyo,2024-10-23 17:55,Japan Standard Time,3.0,3.0,...,35.544647,68629.0,JR Kyushu Hotel Blossom Shinjuku,139.698366,35.687627,1.0,Sedan,1,,

In [11]:
csv_file_path = "../data/invalid_from_timestamp_tokyo_check.csv"
def check_invalid_timestamp(x):
    try:
        datetime.fromisoformat(x)
        return False
    except ValueError:
        return True
    except Exception as exc:
        return True

chunk_size = 10000    
for chunk in tqdm(pd.read_sql(select(dispatch_routes_t), con=sql_conn, index_col='dispatch_id', chunksize=chunk_size), total=total_rows//chunk_size +1):
    df_invalid = chunk[chunk['from_datetime_fix_str'].apply(check_invalid_timestamp)]
    with open(csv_file_path, 'a') as f:
        df_invalid.to_csv(f, header=f.tell()==0,chunksize=chunk_size)

  0%|          | 0/7 [00:00<?, ?it/s]

# Precision reduction for start_ltt, start_lng, end_ltt, end_lng and pick distinct values

In [12]:
sql_eng = create_engine('sqlite:///../data/price_tokyo.db', echo=False)
conn = sql_eng.connect()
my_table = Table('price_training_tokyo', MetaData(), autoload_with=sql_eng)
metadata = MetaData()

In [13]:
query = select(func.count(distinct(my_table.c.dispatch_id)))

In [14]:
with sql_eng.connect() as connection:
    result = connection.execute(query)
    unique_count = result.scalar()
    
print(unique_count)

67432

In [15]:
query = select(my_table).limit(10)
df = pd.read_sql(query, conn, index_col='dispatch_id')
# df[['route_start','route_end']]
df

,ride_id,trip_count,ride_inserted_at,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,passenger_count,luggage_count,...,start_ltt,end_place_id,end_place,end_lng,end_ltt,vehicle_class_id,vehicle_class,row_num,route_start,route_end
dispatch_id,,,,,,,,,,,,,,,,,,,,,
4680,2166988,1,2020-10-29 21:41:00.000000,1604239200,2020-11-01 23:00,Japan Standard Time,None,None,1.0,3.0,...,35.771987,2040,Hotel Main Kanda,139.769481,35.689175,1,Sedan,1,,
4724,2167009,1,2020-11-01 02:16:12.000000,1604239200,2020-11-01 23:00,Japan Standard Time,None,None,1.0,3.0,...,35.771987,2057,Koto City,139.817452,35.672775,1,Sedan,1,,
6351,2167772,1,2020-12-23 14:01:24.000000,1608868800,2020-12-25 13:00,Japan Standard Time,None,None,1.0,3.0,...,35.771987,2691,1 Chome-3 Ishikawacho,139.683002,35.601995,1,Sedan,1,,
12562,2171080,1,2021-04-21 23:15:35.000000,1619388000,2021-04-26 07:00,Japan Standard Time,None,None,4.0,10.0,...,35.284527,81,"Tokyo International Airport,",139.779839,35.549393,10,Minibus-12,1,,
25940,2177878,1,2021-06-22 04:49:42.000000,1624442400,2021-06-23 19:00,Asia/Tokyo,None,None,2.0,3.0,...,35.549393,8327,Comforia Shinjuku Eastside Tower,139.708205,35.696093,2,Business Sedan,1,,
25953,2177888,1,2021-06-22 08:27:19.000000,1625551200,2021-07-06 15:00,Asia/Tokyo,None,None,1.0,3.0,...,35.549393,8333,KiLuck,139.627768,35.451921,1,Sedan,1,,
26635,2178127,1,2021-06-23 17:18:03.000000,1624522500,2021-06-24 17:15,Asia/Tokyo,None,None,1.0,3.0,...,35.732941,82,Narita International Airport,140.392850,35.771987,1,Sedan,1,,
39684,2184005,1,2021-07-25 16:30:10.000000,1627354800,2021-07-27 12:00,Asia/Tokyo,None,None,2.0,3.0,...,35.549393,11104,Hiyori Hotel Ginza Higashi,139.773319,35.673644,1,Sedan,1,,
51124,2188968,1,2021-08-20 08:21:58.000000,1629495900,2021-08-21 06:45,Asia/Tokyo,None,None,1.0,3.0,...,35.771987,13339,SAKURA HOUSE Monzen Nakacho,139.791079,35.676564,1,Sedan,1,,
56084,2191084,1,2021-09-04 02:28:26.000000,1630796400,2021-09-05 08:00,Asia/Tokyo,None,None,1.0,5.0,...,35.636373,82,Narita International Airport,140.392850,35.771987,4,Business SUV,1,,

 ## EDA of raw data

In [16]:
# raw_t = Table('price_training_2324_clean', metadata, autoload_with=sql_eng)
# newyork_t = Table('price_training_newyork', metadata, autoload_with=sql_eng)
raw_t = Table('price_training_tokyo', metadata, autoload_with=sql_eng)

In [17]:
query = select(func.count(distinct(raw_t.c.dispatch_id)))
with sql_eng.connect() as connection:
    result = connection.execute(query)
    total_rows = result.scalar()
print(total_rows)

67432

In [18]:
service_area_q = select(raw_t.c.dispatch_id, raw_t.c.service_area_id,raw_t.c.service_area, func.COUNT(raw_t.c.dispatch_id).label('count')).group_by(raw_t.c.service_area_id).order_by(desc('count'))
df = pd.read_sql(service_area_q, sql_eng)
df

   dispatch_id  service_area_id  service_area  count
0         4680               43  Tokyo, Japan  67432

In [19]:
partner_q = select(raw_t.c.dispatch_id, raw_t.c.partner,raw_t.c.partner_id, func.COUNT(raw_t.c.dispatch_id).label('count')).group_by(raw_t.c.partner_id).order_by(desc('count'))
df = pd.read_sql(partner_q, sql_eng)
df

    dispatch_id                           partner  partner_id  count
0        512506                           Booking           2  37618
1        485865                  CityAirportTaxis           5  10111
2          4680                             Mozio           3   5742
3        160851                           Expedia           1   4418
4        592065                            TaoBao           8   2291
5       1123687                        Fliggy API        2606   1641
6        226363                    Elife Transfer          13   1448
7        786267                           Jayride           4    692
8        768387                         Book Taxi          20    682
9       1846732                       XiaoHongShu        2637    568
10        56547                       Tripadvisor          24    335
11      1431447                     Travel Agency          33    270
12       335156                         Affiliate          36    255
13      2568603                             Tuniu        2640    174
14      1699316                        Servantrip        2599    173
15      1991402                  Tongcheng Travel        2645    155
16       680527                      GetYourGuide          50    136
17       676302                        Fliggy CRS        2596    134
18      1531624                 Elife Transfer CN        2605    129
19      1565864                         Corporate         100    117
20       487931                          Despegar          40     81
21      2308818                       Umetrip API        2664     48
22      1327736                       ShuttleFare          34     43
23       282226                           TESTING          11     31
24      2717509                      Corporate CN        2662     24
25        12562                  Airport Shuttles          26     16
26      2591724                         JD travel        2652     15
27      2322253                          Mafengwo        2614     14
28      2093173                 Elife Transfer zh        2653      9
29       695320  Booking-Motor__Finantek-Seis-S-A        2587      9
30       699987                 Gateway Transfers          39      9
31      2684102         Booking-Motor__Andes-Reps        2581      8
32      2210683                        FCM travel        2656      7
33      1925872                              E.T.        2598      6
34      2970764         Tuniu API - International        2687      4
35      1932396           Booking-Motor__VIajarLH        2651      3
36      1526734                   China Ctrip API        2621      3
37       862451           Booking-Motor__Carrusel          54      3
38      2066230                        Qunar tour        2646      2
39       795059          Booking-Motor__Grupo-Gea          55      2
40       588883                              Deem          22      2
41      2429937                         Elifelimo          12      2
42      2710016               HeyTrip-rate001-net        2665      1
43      2284832                 Tuniu API - China        2659      1

In [20]:
raw_q = select(raw_t.c.dispatch_id, raw_t.c.vehicle_class_id,raw_t.c.vehicle_class, func.COUNT(raw_t.c.dispatch_id).label('count')).group_by(raw_t.c.vehicle_class_id).order_by(desc('count'))
df = pd.read_sql(raw_q, sql_eng)
df

    dispatch_id  vehicle_class_id      vehicle_class  count
0          4680               1.0              Sedan  24272
1        226363               6.0              MPV-4  18222
2        446175               3.0              MPV-5   8152
3        571557               5.0          Minibus-8   6911
4         56084               4.0       Business SUV   5044
5         25940               2.0     Business Sedan   1910
6        580680               9.0         Minibus-10    821
7        645395              36.0   Business Minivan    653
8       1515452               7.0              MPV-6    399
9       2155008              13.0     Business MPV-4    289
10      1757492               8.0          Minibus-7    256
11      2653752              12.0      Comfort Sedan    216
12        12562              10.0         Minibus-12    120
13      2487653              29.0        16-seat Bus     67
14      1236256              11.0         Minibus-14     61
15       507344              30.0        20-seat Bus     16
16      1646766              31.0        23-seat Bus      7
17      2945156              34.0  44-seat Coach Bus      6
18      2796953              32.0        27-seat Bus      4
19         3653               NaN               None      3
20       752950              33.0        36-seat Bus      2
21      1451173              50.0     Wheelchair Van      1

## convert service area table cvs to sqlite db

In [21]:
df = pd.read_csv('../data/service_area_2024.csv', index_col='ride_id')

In [22]:
df.shape
df.iloc[:5,:]

         service_area_id     from_time_str        service_area
ride_id
3596861              273  2024-09-02 10:15            HangZhou
3591584             1435  2024-09-17 16:20  Berlin-BER,Germany
3581482              277  2024-09-06 18:00     Barcelona,Spain
3555299              913  2024-09-03 07:45     Nevsehir,Turkey
3597835              365  2024-09-11 22:20   Reykjavik,Iceland

In [23]:
df.to_sql('service_area_2024', sqlite_eng, if_exists='replace', index=True)

786832

## convert route deduplication result to sqlite db

In [24]:
csv_result_file_list = ['../data/price_training_tokyo_start_result.csv',
                        '../data/price_training_tokyo_end_result.csv']
csv_result_table_list = ['price_training_tokyo_start_result',
                        'price_training_tokyo_end_result']

chunk_size = 10000
total_lines = [sum(1 for line in open(csv_result_file_list[0])),sum(1 for line in open(csv_result_file_list[1]))]
print(total_lines)

[3195, 4743]

In [25]:
sample = pd.read_csv(csv_result_file_list[1], index_col='dispatch_id', nrows=5)
sample

,index,ride_id,trip_count,ride_inserted_at,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,passenger_count,...,end_ltt,vehicle_class_id,vehicle_class,row_num,route_start,route_end,start_ltt_lp,start_lng_lp,end_ltt_lp,end_lng_lp
dispatch_id,,,,,,,,,,,,,,,,,,,,,
585030,0,2430725,1,2023-01-04 22:06:08.000000,1673080500,2023-01-07 17:35,Japan Standard Time,NaN,NaN,1.0,...,NaN,1,Sedan,1,NaN,NaN,35.77257,140.39336,NaN,NaN
1107529,1,2566992,2,2023-05-02 07:37:15.000000,1688372700,2023-07-03 17:25,Asia/Tokyo,2023-07-17 16:00,India Standard Time,5.0,...,28.625018,3,MPV-5,1,NaN,NaN,35.54939,139.77984,28.62502,77.21823
2676750,2,3473304,1,2024-05-16 03:16:52.000000,1715929200,2024-05-17 16:00,Japan Standard Time,NaN,NaN,4.0,...,33.628730,5,Minibus-8,1,NaN,NaN,35.54939,139.77984,33.62873,135.94232
52905,3,2189726,1,2021-08-25 07:31:41.000000,1629959400,2021-08-26 15:30,Asia/Tokyo,NaN,NaN,1.0,...,34.133324,2,Business Sedan,1,NaN,NaN,35.54939,139.77984,34.13332,-81.46433
1720510,4,3004336,1,2023-11-25 11:15:58.000000,1703808900,2023-12-29 09:15,Asia/Tokyo,NaN,NaN,4.0,...,34.432002,7,MPV-6,1,NaN,NaN,36.68937,137.84076,34.43200,135.23039

In [26]:
for t in range(2):
    for chunk in tqdm(pd.read_csv(csv_result_file_list[t], index_col='dispatch_id', chunksize=chunk_size),
                      total=total_lines[t] // chunk_size + 1):
        # for chunk in tqdm(pd.read_csv(csv_file_path, chunksize=chunk_size), total=total_lines//chunk_size +1):
        chunk.to_sql(csv_result_table_list[t], sqlite_eng, if_exists='append', index=True)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

## Get the union of the label tables

In [114]:
chunk_size = 100

In [117]:
label_list = ['price_training_tokyo_start_result',
              'price_training_tokyo_end_result',
              'price_training_tokyo_route_label',]

In [118]:
label_start_t = Table(label_list[0], metadata, autoload_with=sql_eng)
print(sql_session.query(label_start_t).count())
label_end_t = Table(label_list[1], metadata, autoload_with=sql_eng)
print(sql_session.query(label_end_t).count())

3194
4742

In [119]:
label_start_q = sql_session.query(label_start_t)
label_start_q.count()
label_end_q = sql_session.query(label_end_t)
label_end_q.count()

3194

4742

In [120]:
label_start_t.columns.keys()

['dispatch_id',
 'index',
 'ride_id',
 'trip_count',
 'ride_inserted_at',
 'from_utc',
 'from_time_str',
 'from_timezone_str',
 'to_time_str',
 'to_timezone_str',
 'passenger_count',
 'luggage_count',
 'children_count',
 'infant_count',
 'distance',
 'duration',
 'trip_no',
 'dispatch_amount',
 'dispatch_currency',
 'dispatch_inserted_at',
 'from_cur',
 'to_cur',
 'rate',
 'effective_at',
 'expire_at',
 'from_date_str',
 'from_time_fix_str',
 'from_datetime_fix_str',
 'trip_type_id',
 'trip_type',
 'ride_status_id',
 'ride_status',
 'dispatch_status_id',
 'dispatch_status',
 'dispatch_type',
 'fleet',
 'partner_id',
 'partner',
 'service_area_id',
 'service_area',
 'start_place_id',
 'start_place',
 'start_lng',
 'start_ltt',
 'end_place_id',
 'end_place',
 'end_lng',
 'end_ltt',
 'vehicle_class_id',
 'vehicle_class',
 'row_num',
 'route_start',
 'route_end',
 'start_ltt_lp',
 'start_lng_lp',
 'end_ltt_lp',
 'end_lng_lp']

In [121]:
label_routes_q = union(label_start_q, label_end_q)

In [122]:
df = pd.read_sql(label_routes_q, sql_eng)
# {l:r for l,r in zip(df.columns,label_start_t.columns.keys())}
df.columns = label_start_t.columns.keys()
# df.index = df['dispatch_id']
df.set_index(['start_ltt_lp', 'start_lng_lp', 'end_ltt_lp', 'end_lng_lp'], inplace=True)
# df.set_index('dispatch_id', inplace=True)
df

                                                 dispatch_id  index  ride_id  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
35.70069     139.69738    35.54500   139.76904           487    418  2165002
                                     139.76904           487   2151  2165002
35.65465     139.73519    35.54939   139.77984           739    714  2165121
35.63009     139.71035    35.77199   140.39285           889    478  2165212
35.77199     140.39285    35.79632   139.72241          1106   4678  2165312
...                                                      ...    ...      ...
35.58715     139.73616    35.44953   139.64646       3447309    329  3409772
35.67448     139.81470    35.45017   139.64625       3472020   1385  3361526
35.54465     139.76779    35.70829   139.79553       3488096   3532  3510782
                          35.68783   139.69849       3489456   2385  3521511
                          35.71139   139.77288       3519099   3701  3520019

                                                 trip_count  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
35.70069     139.69738    35.54500   139.76904            1
                                     139.76904            1
35.65465     139.73519    35.54939   139.77984            1
35.63009     139.71035    35.77199   140.39285            1
35.77199     140.39285    35.79632   139.72241            1
...                                                     ...
35.58715     139.73616    35.44953   139.64646            1
35.67448     139.81470    35.45017   139.64625            1
35.54465     139.76779    35.70829   139.79553            1
                          35.68783   139.69849            2
                          35.71139   139.77288            1

                                                           ride_inserted_at  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
35.70069     139.69738    35.54500   139.76904   2020-06-15 03:32:19.000000
                                     139.76904   2020-06-15 03:32:19.000000
35.65465     139.73519    35.54939   139.77984   2020-06-27 16:57:10.000000
35.63009     139.71035    35.77199   140.39285   2020-07-02 06:07:02.000000
35.77199     140.39285    35.79632   139.72241   2020-07-09 18:02:50.000000
...                                                                     ...
35.58715     139.73616    35.44953   139.64646   2024-04-18 15:03:29.000000
35.67448     139.81470    35.45017   139.64625   2024-03-29 11:55:56.000000
35.54465     139.76779    35.70829   139.79553   2024-06-03 21:30:54.000000
                          35.68783   139.69849   2024-06-08 21:19:07.000000
                          35.71139   139.77288   2024-06-08 05:13:43.000000

                                                   from_utc     from_time_str  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
35.70069     139.69738    35.54500   139.76904   1592359200  2020-06-17 11:00
                                     139.76904   1592359200  2020-06-17 11:00
35.65465     139.73519    35.54939   139.77984   1593662400  2020-07-02 13:00
35.63009     139.71035    35.77199   140.39285   1593752400  2020-07-03 14:00
35.77199     140.39285    35.79632   139.72241   1594512000  2020-07-12 09:00
...                                                     ...               ...
35.58715     139.73616    35.44953   139.64646   1728180000  2024-10-06 11:00
35.67448     139.81470    35.45017   139.64625   1729213200  2024-10-18 10:00
35.54465     139.76779    35.70829   139.79553   1728727200  2024-10-12 19:00
                          35.68783   139.69849   1728886200  2024-10-14 15:10
                          35.71139   139.77288   1729845000  2024-10-25 17:30

                                                   from_timezone_str  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
35.70069     139.69738    35.54500   139.76904   Japan Standard Time
                                     139.76904   Japan Standard Time
35.65465     139.73519    35.54939   139.77984   Japan Standard Time
35.63009     139.71035    35.77199   140.39285   Japan Standard Time
35.77199     140.39285    35.79632   139.72241   Japan Standard Time
...                                                              ...
35.58715     139.73616    35.44953   139.64646            Asia/Tokyo
35.67448     139.81470    35.45017   139.64625            Asia/Tokyo
35.54465     139.76779    35.70829   139.79553            Asia/Tokyo
                          35.68783   139.69849            Asia/Tokyo
                          35.71139   139.77288            Asia/Tokyo

                                                      to_time_str  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
35.70069     139.69738    35.54500   139.76904               None
                                     139.76904               None
35.65465     139.73519    35.54939   139.77984               None
35.63009     139.71035    35.77199   140.39285               None
35.77199     140.39285    35.79632   139.72241               None
...                                                           ...
35.58715     139.73616    35.44953   139.64646               None
35.67448     139.81470    35.45017   139.64625               None
35.54465     139.76779    35.70829   139.79553               None
                          35.68783   139.69849   2024-10-20 12:50
                          35.71139   139.77288               None

                                                to_timezone_str  ...  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp                  ...
35.70069     139.69738    35.54500   139.76904             None  ...
                                     139.76904             None  ...
35.65465     139.73519    35.54939   139.77984             None  ...
35.63009     139.71035    35.77199   140.39285             None  ...
35.77199     140.39285    35.79632   139.72241             None  ...
...                                                         ...  ...
35.58715     139.73616    35.44953   139.64646             None  ...
35.67448     139.81470    35.45017   139.64625             None  ...
35.54465     139.76779    35.70829   139.79553             None  ...
                          35.68783   139.69849       Asia/Tokyo  ...
                          35.71139   139.77288             None  ...

                                                 start_ltt  end_place_id  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
35.70069     139.69738    35.54500   139.76904   35.700687         242.0
                                     139.76904   35.700687         242.0
35.65465     139.73519    35.54939   139.77984   35.654654          81.0
35.63009     139.71035    35.77199   140.39285   35.630095          82.0
35.77199     140.39285    35.79632   139.72241   35.771987         558.0
...                                                    ...           ...
35.58715     139.73616    35.44953   139.64646   35.587147     1502188.0
35.67448     139.81470    35.45017   139.64625   35.674484     1406738.0
35.54465     139.76779    35.70829   139.79553   35.544647     1700731.0
                          35.68783   139.69849   35.544647     1721650.0
                          35.71139   139.77288   35.544647     1718720.0

                                                                                         end_place  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
35.70069     139.69738    35.54500   139.76904   Haneda Airport Passenger Terminal 3 Japan, 〒14...
                                     139.76904   Haneda Airport Passenger Terminal 3 Japan, 〒14...
35.65465     139.73519    35.54939   139.77984                        Tokyo International Airport,
35.63009     139.71035    35.77199   140.39285                        Narita International Airport
35.77199     140.39285    35.79632   139.72241                                         Kanayamacho
...                                                                                            ...
35.58715     139.73616    35.44953   139.64646                             Osanbashi Pier Building
35.67448     139.81470    35.45017   139.64625                       Yokohama cruise ship term Nal
35.54465     139.76779    35.70829   139.79553                          APA Hotel Asakusa - Ekimae
                          35.68783   139.69849                    JR Kyushu Hotel Blossom Shinjuku
                          35.71139   139.77288                        APA Hotel Keisei Ueno-Ekimae

                                                    end_lng    end_ltt  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
35.70069     139.69738    35.54500   139.76904   139.769043  35.545002
                                     139.76904   139.769043  35.545002
35.65465     139.73519    35.54939   139.77984   139.779839  35.549393
35.63009     139.71035    35.77199   140.39285   140.392850  35.771987
35.77199     140.39285    35.79632   139.72241   139.722415  35.796324
...                                                     ...        ...
35.58715     139.73616    35.44953   139.64646   139.646463  35.449534
35.67448     139.81470    35.45017   139.64625   139.646246  35.450166
35.54465     139.76779    35.70829   139.79553   139.795525  35.708292
                          35.68783   139.69849   139.698494  35.687835
                          35.71139   139.77288   139.772884  35.711387

                                                 vehicle_class_id  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
35.70069     139.69738    35.54500   139.76904                  1
                                     139.76904                  1
35.65465     139.73519    35.54939   139.77984                  6
35.63009     139.71035    35.77199   140.39285                  1
35.77199     140.39285    35.79632   139.72241                  3
...                                                           ...
35.58715     139.73616    35.44953   139.64646                  6
35.67448     139.81470    35.45017   139.64625                  6
35.54465     139.76779    35.70829   139.79553                  1
                          35.68783   139.69849                  3
                          35.71139   139.77288                  1

                                                 vehicle_class  row_num  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
35.70069     139.69738    35.54500   139.76904           Sedan        1
                                     139.76904           Sedan        1
35.65465     139.73519    35.54939   139.77984           MPV-4        1
35.63009     139.71035    35.77199   140.39285           Sedan        1
35.77199     140.39285    35.79632   139.72241           MPV-5        1
...                                                        ...      ...
35.58715     139.73616    35.44953   139.64646           MPV-4        1
35.67448     139.81470    35.45017   139.64625           MPV-4        1
35.54465     139.76779    35.70829   139.79553           Sedan        1
                          35.68783   139.69849           MPV-5        1
                          35.71139   139.77288           Sedan        1

                                                route_start route_end
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
35.70069     139.69738    35.54500   139.76904          东京1       HND
                                     139.76904          东京1       HND
35.65465     139.73519    35.54939   139.77984          东京2       HND
35.63009     139.71035    35.77199   140.39285          东京3       NRT
35.77199     140.39285    35.79632   139.72241          NRT        琦玉
...                                                     ...       ...
35.58715     139.73616    35.44953   139.64646          东京3        横滨
35.67448     139.81470    35.45017   139.64625          东京2        横滨
35.54465     139.76779    35.70829   139.79553          HND       东京2
                          35.68783   139.69849          HND       东京2
                          35.71139   139.77288          HND       东京2

[7936 rows x 53 columns]

In [123]:
# df.sort_values(['start_ltt_lp', 'start_lng_lp', 'end_ltt_lp', 'end_lng_lp'], inplace=True)
df.dropna(subset=['route_start', 'route_end'], how='any', inplace=True)
df

                                                 dispatch_id  index  ride_id  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
35.70069     139.69738    35.54500   139.76904           487    418  2165002
                                     139.76904           487   2151  2165002
35.65465     139.73519    35.54939   139.77984           739    714  2165121
35.63009     139.71035    35.77199   140.39285           889    478  2165212
35.77199     140.39285    35.79632   139.72241          1106   4678  2165312
...                                                      ...    ...      ...
35.58715     139.73616    35.44953   139.64646       3447309    329  3409772
35.67448     139.81470    35.45017   139.64625       3472020   1385  3361526
35.54465     139.76779    35.70829   139.79553       3488096   3532  3510782
                          35.68783   139.69849       3489456   2385  3521511
                          35.71139   139.77288       3519099   3701  3520019

                                                 trip_count  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
35.70069     139.69738    35.54500   139.76904            1
                                     139.76904            1
35.65465     139.73519    35.54939   139.77984            1
35.63009     139.71035    35.77199   140.39285            1
35.77199     140.39285    35.79632   139.72241            1
...                                                     ...
35.58715     139.73616    35.44953   139.64646            1
35.67448     139.81470    35.45017   139.64625            1
35.54465     139.76779    35.70829   139.79553            1
                          35.68783   139.69849            2
                          35.71139   139.77288            1

                                                           ride_inserted_at  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
35.70069     139.69738    35.54500   139.76904   2020-06-15 03:32:19.000000
                                     139.76904   2020-06-15 03:32:19.000000
35.65465     139.73519    35.54939   139.77984   2020-06-27 16:57:10.000000
35.63009     139.71035    35.77199   140.39285   2020-07-02 06:07:02.000000
35.77199     140.39285    35.79632   139.72241   2020-07-09 18:02:50.000000
...                                                                     ...
35.58715     139.73616    35.44953   139.64646   2024-04-18 15:03:29.000000
35.67448     139.81470    35.45017   139.64625   2024-03-29 11:55:56.000000
35.54465     139.76779    35.70829   139.79553   2024-06-03 21:30:54.000000
                          35.68783   139.69849   2024-06-08 21:19:07.000000
                          35.71139   139.77288   2024-06-08 05:13:43.000000

                                                   from_utc     from_time_str  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
35.70069     139.69738    35.54500   139.76904   1592359200  2020-06-17 11:00
                                     139.76904   1592359200  2020-06-17 11:00
35.65465     139.73519    35.54939   139.77984   1593662400  2020-07-02 13:00
35.63009     139.71035    35.77199   140.39285   1593752400  2020-07-03 14:00
35.77199     140.39285    35.79632   139.72241   1594512000  2020-07-12 09:00
...                                                     ...               ...
35.58715     139.73616    35.44953   139.64646   1728180000  2024-10-06 11:00
35.67448     139.81470    35.45017   139.64625   1729213200  2024-10-18 10:00
35.54465     139.76779    35.70829   139.79553   1728727200  2024-10-12 19:00
                          35.68783   139.69849   1728886200  2024-10-14 15:10
                          35.71139   139.77288   1729845000  2024-10-25 17:30

                                                   from_timezone_str  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
35.70069     139.69738    35.54500   139.76904   Japan Standard Time
                                     139.76904   Japan Standard Time
35.65465     139.73519    35.54939   139.77984   Japan Standard Time
35.63009     139.71035    35.77199   140.39285   Japan Standard Time
35.77199     140.39285    35.79632   139.72241   Japan Standard Time
...                                                              ...
35.58715     139.73616    35.44953   139.64646            Asia/Tokyo
35.67448     139.81470    35.45017   139.64625            Asia/Tokyo
35.54465     139.76779    35.70829   139.79553            Asia/Tokyo
                          35.68783   139.69849            Asia/Tokyo
                          35.71139   139.77288            Asia/Tokyo

                                                      to_time_str  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
35.70069     139.69738    35.54500   139.76904               None
                                     139.76904               None
35.65465     139.73519    35.54939   139.77984               None
35.63009     139.71035    35.77199   140.39285               None
35.77199     140.39285    35.79632   139.72241               None
...                                                           ...
35.58715     139.73616    35.44953   139.64646               None
35.67448     139.81470    35.45017   139.64625               None
35.54465     139.76779    35.70829   139.79553               None
                          35.68783   139.69849   2024-10-20 12:50
                          35.71139   139.77288               None

                                                to_timezone_str  ...  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp                  ...
35.70069     139.69738    35.54500   139.76904             None  ...
                                     139.76904             None  ...
35.65465     139.73519    35.54939   139.77984             None  ...
35.63009     139.71035    35.77199   140.39285             None  ...
35.77199     140.39285    35.79632   139.72241             None  ...
...                                                         ...  ...
35.58715     139.73616    35.44953   139.64646             None  ...
35.67448     139.81470    35.45017   139.64625             None  ...
35.54465     139.76779    35.70829   139.79553             None  ...
                          35.68783   139.69849       Asia/Tokyo  ...
                          35.71139   139.77288             None  ...

                                                 start_ltt  end_place_id  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
35.70069     139.69738    35.54500   139.76904   35.700687         242.0
                                     139.76904   35.700687         242.0
35.65465     139.73519    35.54939   139.77984   35.654654          81.0
35.63009     139.71035    35.77199   140.39285   35.630095          82.0
35.77199     140.39285    35.79632   139.72241   35.771987         558.0
...                                                    ...           ...
35.58715     139.73616    35.44953   139.64646   35.587147     1502188.0
35.67448     139.81470    35.45017   139.64625   35.674484     1406738.0
35.54465     139.76779    35.70829   139.79553   35.544647     1700731.0
                          35.68783   139.69849   35.544647     1721650.0
                          35.71139   139.77288   35.544647     1718720.0

                                                                                         end_place  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
35.70069     139.69738    35.54500   139.76904   Haneda Airport Passenger Terminal 3 Japan, 〒14...
                                     139.76904   Haneda Airport Passenger Terminal 3 Japan, 〒14...
35.65465     139.73519    35.54939   139.77984                        Tokyo International Airport,
35.63009     139.71035    35.77199   140.39285                        Narita International Airport
35.77199     140.39285    35.79632   139.72241                                         Kanayamacho
...                                                                                            ...
35.58715     139.73616    35.44953   139.64646                             Osanbashi Pier Building
35.67448     139.81470    35.45017   139.64625                       Yokohama cruise ship term Nal
35.54465     139.76779    35.70829   139.79553                          APA Hotel Asakusa - Ekimae
                          35.68783   139.69849                    JR Kyushu Hotel Blossom Shinjuku
                          35.71139   139.77288                        APA Hotel Keisei Ueno-Ekimae

                                                    end_lng    end_ltt  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
35.70069     139.69738    35.54500   139.76904   139.769043  35.545002
                                     139.76904   139.769043  35.545002
35.65465     139.73519    35.54939   139.77984   139.779839  35.549393
35.63009     139.71035    35.77199   140.39285   140.392850  35.771987
35.77199     140.39285    35.79632   139.72241   139.722415  35.796324
...                                                     ...        ...
35.58715     139.73616    35.44953   139.64646   139.646463  35.449534
35.67448     139.81470    35.45017   139.64625   139.646246  35.450166
35.54465     139.76779    35.70829   139.79553   139.795525  35.708292
                          35.68783   139.69849   139.698494  35.687835
                          35.71139   139.77288   139.772884  35.711387

                                                 vehicle_class_id  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
35.70069     139.69738    35.54500   139.76904                  1
                                     139.76904                  1
35.65465     139.73519    35.54939   139.77984                  6
35.63009     139.71035    35.77199   140.39285                  1
35.77199     140.39285    35.79632   139.72241                  3
...                                                           ...
35.58715     139.73616    35.44953   139.64646                  6
35.67448     139.81470    35.45017   139.64625                  6
35.54465     139.76779    35.70829   139.79553                  1
                          35.68783   139.69849                  3
                          35.71139   139.77288                  1

                                                 vehicle_class  row_num  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
35.70069     139.69738    35.54500   139.76904           Sedan        1
                                     139.76904           Sedan        1
35.65465     139.73519    35.54939   139.77984           MPV-4        1
35.63009     139.71035    35.77199   140.39285           Sedan        1
35.77199     140.39285    35.79632   139.72241           MPV-5        1
...                                                        ...      ...
35.58715     139.73616    35.44953   139.64646           MPV-4        1
35.67448     139.81470    35.45017   139.64625           MPV-4        1
35.54465     139.76779    35.70829   139.79553           Sedan        1
                          35.68783   139.69849           MPV-5        1
                          35.71139   139.77288           Sedan        1

                                                route_start route_end
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
35.70069     139.69738    35.54500   139.76904          东京1       HND
                                     139.76904          东京1       HND
35.65465     139.73519    35.54939   139.77984          东京2       HND
35.63009     139.71035    35.77199   140.39285          东京3       NRT
35.77199     140.39285    35.79632   139.72241          NRT        琦玉
...                                                     ...       ...
35.58715     139.73616    35.44953   139.64646          东京3        横滨
35.67448     139.81470    35.45017   139.64625          东京2        横滨
35.54465     139.76779    35.70829   139.79553          HND       东京2
                          35.68783   139.69849          HND       东京2
                          35.71139   139.77288          HND       东京2

[7613 rows x 53 columns]

In [124]:
df.drop_duplicates(subset=['route_start', 'route_end', 'vehicle_class_id'], inplace=True)
df

,,,,dispatch_id,index,ride_id,trip_count,ride_inserted_at,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,...,start_ltt,end_place_id,end_place,end_lng,end_ltt,vehicle_class_id,vehicle_class,row_num,route_start,route_end
start_ltt_lp,start_lng_lp,end_ltt_lp,end_lng_lp,,,,,,,,,,,,,,,,,,,,,
35.70069,139.69738,35.54500,139.76904,487,418,2165002,1,2020-06-15 03:32:19.000000,1592359200,2020-06-17 11:00,Japan Standard Time,None,None,...,35.700687,242.0,"Haneda Airport Passenger Terminal 3 Japan, 〒14...",139.769043,35.545002,1,Sedan,1,东京1,HND
35.65465,139.73519,35.54939,139.77984,739,714,2165121,1,2020-06-27 16:57:10.000000,1593662400,2020-07-02 13:00,Japan Standard Time,None,None,...,35.654654,81.0,"Tokyo International Airport,",139.779839,35.549393,6,MPV-4,1,东京2,HND
35.63009,139.71035,35.77199,140.39285,889,478,2165212,1,2020-07-02 06:07:02.000000,1593752400,2020-07-03 14:00,Japan Standard Time,None,None,...,35.630095,82.0,Narita International Airport,140.392850,35.771987,1,Sedan,1,东京3,NRT
35.77199,140.39285,35.79632,139.72241,1106,4678,2165312,1,2020-07-09 18:02:50.000000,1594512000,2020-07-12 09:00,Japan Standard Time,None,None,...,35.771987,558.0,Kanayamacho,139.722415,35.796324,3,MPV-5,1,NRT,琦玉
35.54939,139.77984,35.66197,139.70380,1163,1353,2165337,1,2020-07-11 20:10:11.000000,1594713600,2020-07-14 17:00,Japan Standard Time,None,None,...,35.549393,583.0,Shibuya City,139.703795,35.661971,3,MPV-5,1,HND,东京2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35.67245,139.75790,35.74924,139.76163,2765493,4496,3513634,2,2024-06-05 08:21:05.000000,1719532800,2024-06-28 09:00,Japan Standard Time,2024-06-28 12:30,Japan Standard Time,...,35.672454,1706317.0,"YUCa's Japanese Cooking 2-chōme-34-8 Nishiogu,...",139.761635,35.749235,36,Business Minivan,1,东京2,东京1
35.77135,140.39166,35.55443,139.74124,2770147,3106,3516005,1,2024-06-06 10:46:40.000000,1727957100,2024-10-03 21:05,Asia/Tokyo,None,None,...,35.771347,1710928.0,Henn na Hotel Tokyo Haneda,139.741242,35.554429,32,27-seat Bus,1,NRT,东京3
35.62768,139.73639,35.64129,139.88105,2783029,890,3522466,1,2024-06-09 11:09:26.000000,1718147700,2024-06-12 08:15,Asia/Tokyo,None,None,...,35.627679,1723521.0,11,139.881048,35.641290,5,Minibus-8,1,东京3,东京1
35.62529,139.72544,35.45118,139.64732,2788910,415,3525519,1,2024-06-10 17:50:27.000000,1718848800,2024-06-20 11:00,Asia/Tokyo,None,None,...,35.625293,1729545.0,"Osanbashi Pier, 1 Chome Kaigandōri, Naka Ward,...",139.647323,35.451177,3,MPV-5,1,东京3,横滨
35.45000,139.64611,35.62671,139.88508,2795822,709,3468692,1,2024-05-14 07:41:32.000000,1720564200,2024-07-10 07:30,Japan Standard Time,None,None,...,35.450000,185672.0,Tokyo DisneySea,139.885078,35.626711,1,Sedan,1,横滨,东京1

In [125]:
df = df.reindex(columns=df.columns.tolist() + ['cost','profit'])
df

,,,,dispatch_id,index,ride_id,trip_count,ride_inserted_at,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,...,end_place,end_lng,end_ltt,vehicle_class_id,vehicle_class,row_num,route_start,route_end,cost,profit
start_ltt_lp,start_lng_lp,end_ltt_lp,end_lng_lp,,,,,,,,,,,,,,,,,,,,,
35.70069,139.69738,35.54500,139.76904,487,418,2165002,1,2020-06-15 03:32:19.000000,1592359200,2020-06-17 11:00,Japan Standard Time,None,None,...,"Haneda Airport Passenger Terminal 3 Japan, 〒14...",139.769043,35.545002,1,Sedan,1,东京1,HND,NaN,NaN
35.65465,139.73519,35.54939,139.77984,739,714,2165121,1,2020-06-27 16:57:10.000000,1593662400,2020-07-02 13:00,Japan Standard Time,None,None,...,"Tokyo International Airport,",139.779839,35.549393,6,MPV-4,1,东京2,HND,NaN,NaN
35.63009,139.71035,35.77199,140.39285,889,478,2165212,1,2020-07-02 06:07:02.000000,1593752400,2020-07-03 14:00,Japan Standard Time,None,None,...,Narita International Airport,140.392850,35.771987,1,Sedan,1,东京3,NRT,NaN,NaN
35.77199,140.39285,35.79632,139.72241,1106,4678,2165312,1,2020-07-09 18:02:50.000000,1594512000,2020-07-12 09:00,Japan Standard Time,None,None,...,Kanayamacho,139.722415,35.796324,3,MPV-5,1,NRT,琦玉,NaN,NaN
35.54939,139.77984,35.66197,139.70380,1163,1353,2165337,1,2020-07-11 20:10:11.000000,1594713600,2020-07-14 17:00,Japan Standard Time,None,None,...,Shibuya City,139.703795,35.661971,3,MPV-5,1,HND,东京2,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35.67245,139.75790,35.74924,139.76163,2765493,4496,3513634,2,2024-06-05 08:21:05.000000,1719532800,2024-06-28 09:00,Japan Standard Time,2024-06-28 12:30,Japan Standard Time,...,"YUCa's Japanese Cooking 2-chōme-34-8 Nishiogu,...",139.761635,35.749235,36,Business Minivan,1,东京2,东京1,NaN,NaN
35.77135,140.39166,35.55443,139.74124,2770147,3106,3516005,1,2024-06-06 10:46:40.000000,1727957100,2024-10-03 21:05,Asia/Tokyo,None,None,...,Henn na Hotel Tokyo Haneda,139.741242,35.554429,32,27-seat Bus,1,NRT,东京3,NaN,NaN
35.62768,139.73639,35.64129,139.88105,2783029,890,3522466,1,2024-06-09 11:09:26.000000,1718147700,2024-06-12 08:15,Asia/Tokyo,None,None,...,11,139.881048,35.641290,5,Minibus-8,1,东京3,东京1,NaN,NaN
35.62529,139.72544,35.45118,139.64732,2788910,415,3525519,1,2024-06-10 17:50:27.000000,1718848800,2024-06-20 11:00,Asia/Tokyo,None,None,...,"Osanbashi Pier, 1 Chome Kaigandōri, Naka Ward,...",139.647323,35.451177,3,MPV-5,1,东京3,横滨,NaN,NaN
35.45000,139.64611,35.62671,139.88508,2795822,709,3468692,1,2024-05-14 07:41:32.000000,1720564200,2024-07-10 07:30,Japan Standard Time,None,None,...,Tokyo DisneySea,139.885078,35.626711,1,Sedan,1,横滨,东京1,NaN,NaN

In [126]:
# df.to_sql(label_list[2], sqlite_eng, if_exists='append', index=True)
df.to_sql('routes_vehicle_tokyo', sql_eng, if_exists='append', index=True)

446

In [ ]:
#| hide
import nbdev; nbdev.nbdev_export()