# core data utilities

> core utilities for data processing: 
> datetime processing, time zone processing, validity, filtering

In [1]:
#| default_exp data.database.deduplication

In [2]:
from asyncio import as_completed
from threading import Thread

#| hide
from nbdev.showdoc import *

In [3]:
#| hide
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [4]:
#| export
from datetime import datetime
import pandas as pd
import pytz
#| export
pd.options.mode.chained_assignment = None

# Precision reduction for start_ltt, start_lng, end_ltt, end_lng and pick distinct values

In [5]:
from tqdm.notebook import tqdm
from sqlalchemy import create_engine, select, func, distinct, MetaData, Table, update, bindparam, Column, insert, desc, asc, and_, or_, not_, Numeric, cast, func
from sqlalchemy.orm import sessionmaker, aliased
import pandas as pd
import numpy as np

In [6]:
sql_eng = create_engine('sqlite:///../data/price_training_raw.db', echo=False)
conn = sql_eng.connect()
my_table = Table('price_training_2324_clean', MetaData(), autoload_with=sql_eng)

In [7]:
query = select(func.count(distinct(my_table.c.dispatch_id)))

In [8]:
with sql_eng.connect() as connection:
    result = connection.execute(query)
    unique_count = result.scalar()
    
print(unique_count)

2237349

In [9]:
query = select(my_table).limit(10)
df = pd.read_sql(query, conn, index_col='dispatch_id')
# df[['route_start','route_end']]
df

,ride_id,trip_count,ride_inserted_at,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,passenger_count,luggage_count,...,start_ltt,end_place_id,end_place,end_lng,end_ltt,vehicle_class_id,vehicle_class,row_num,route_start,route_end
dispatch_id,,,,,,,,,,,,,,,,,,,,,
1595931,2939039,1,2023-11-02 09:39:04.000000,1699260300,2023-11-06 09:45,Europe/Berlin,None,None,2.0,2.0,...,52.363839,50881.0,Pullman Berlin Schweizerhof,13.343945,52.506016,1,Sedan,1,,
810009,2546343,1,2023-04-16 03:21:26.000000,1683495000,2023-05-07 17:30,America/Santo_Domingo,None,None,1.0,3.0,...,18.429701,148992.0,"Weston Suites Hotel, Avenida 27 De Febrero 194...",-69.931883,18.464455,1,Sedan,1,,
1234501,2759280,1,2023-08-15 21:02:59.000000,1692291600,2023-08-17 12:00,America/Cancun,None,None,3.0,3.0,...,20.606892,298763.0,"Occidental Tucancún, Calle Retorno Kukulcán 24...",-86.764801,21.101150,1,Sedan,1,,
2184711,3237638,1,2024-02-18 12:56:06.000000,1710411300,2024-03-14 11:15,Europe/Berlin,None,None,1.0,3.0,...,51.223159,1164071.0,DUS,6.766780,51.289501,1,Sedan,1,,
1991900,3114551,1,2024-01-07 03:33:10.000000,1707822716,2024-02-13 12:06,Europe/Berlin,None,None,2.0,5.0,...,52.366697,932220.0,Steigenberger Berlin,13.368089,52.523609,5,Minibus-8,1,,
1017459,2544841,1,2023-04-14 16:38:09.000000,1687793400,2023-06-26 11:30,America/New_York,None,None,2.0,2.0,...,27.980060,53380.0,"Tampa International Airport (TPA), 4100 George...",-82.531138,27.977152,1,Sedan,1,,
2346657,3244645,1,2024-02-20 13:20:30.000000,1711031400,2024-03-21 20:00,Asia/Colombo,None,None,2.0,2.0,...,7.180760,1177966.0,"Hotel MaRadha Colombo, 31 St Kilda's Ln, Colom...",79.852672,6.895760,1,Sedan,1,,
2394581,3342568,1,2024-03-23 17:42:24.000000,1711566000,2024-03-27 20:00,Europe/Paris,None,None,4.0,4.0,...,49.458413,1373269.0,"JAJAJA, 7 Rue Lacharrière, 75011 Paris, France",2.378052,48.862095,3,MPV-5,1,,
1945564,3116051,1,2024-01-07 14:35:06.000000,1704691800,2024-01-08 11:00,Asia/Calcutta,None,None,1.0,3.0,...,28.568519,935015.0,DEL,77.103104,28.566500,1,Sedan,1,,
1646467,2541181,1,2023-04-11 17:52:09.000000,1701014400,2023-11-26 10:00,America/Chicago,None,None,2.0,2.0,...,29.314215,82302.0,George Bush Intercontinental Houston Airport (...,-95.336975,29.988329,6,MPV-4,1,,

In [10]:
# query = select(my_table)
# df = pd.read_sql(query, conn)
# df[['route_start','route_end']]

In [11]:
# df = df.drop_duplicates(subset=['dispatch_id'],keep='first')
# df = df[~df['fleet']]

In [13]:
# len(df)

2238848

In [12]:
# df.to_sql('price_training_2324_clean', sql_eng, if_exists='replace', index=True)

2238848

# order by start_ltt, start_lng, end_ltt, end_lng

In [12]:
sql_eng = create_engine('sqlite:///../data/price_training_raw.db', echo=False)
conn = sql_eng.connect()
metadata = MetaData()
my_table = Table('price_training_2324_clean', metadata, autoload_with=sql_eng)

In [13]:
metadata.reflect(bind=sql_eng)
raw_t = metadata.tables['price_training_2324_clean']
s = select(raw_t).limit(10)
rp = sql_eng.connect().execute(s)
df = pd.DataFrame(rp)
df

,dispatch_id,ride_id,trip_count,ride_inserted_at,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,passenger_count,...,start_ltt,end_place_id,end_place,end_lng,end_ltt,vehicle_class_id,vehicle_class,row_num,route_start,route_end
0,1595931,2939039,1,2023-11-02 09:39:04.000000,1699260300,2023-11-06 09:45,Europe/Berlin,None,None,2.0,...,52.363839,50881.0,Pullman Berlin Schweizerhof,13.343945,52.506016,1,Sedan,1,,
1,810009,2546343,1,2023-04-16 03:21:26.000000,1683495000,2023-05-07 17:30,America/Santo_Domingo,None,None,1.0,...,18.429701,148992.0,"Weston Suites Hotel, Avenida 27 De Febrero 194...",-69.931883,18.464455,1,Sedan,1,,
2,1234501,2759280,1,2023-08-15 21:02:59.000000,1692291600,2023-08-17 12:00,America/Cancun,None,None,3.0,...,20.606892,298763.0,"Occidental Tucancún, Calle Retorno Kukulcán 24...",-86.764801,21.101150,1,Sedan,1,,
3,2184711,3237638,1,2024-02-18 12:56:06.000000,1710411300,2024-03-14 11:15,Europe/Berlin,None,None,1.0,...,51.223159,1164071.0,DUS,6.766780,51.289501,1,Sedan,1,,
4,1991900,3114551,1,2024-01-07 03:33:10.000000,1707822716,2024-02-13 12:06,Europe/Berlin,None,None,2.0,...,52.366697,932220.0,Steigenberger Berlin,13.368089,52.523609,5,Minibus-8,1,,
5,1017459,2544841,1,2023-04-14 16:38:09.000000,1687793400,2023-06-26 11:30,America/New_York,None,None,2.0,...,27.980060,53380.0,"Tampa International Airport (TPA), 4100 George...",-82.531138,27.977152,1,Sedan,1,,
6,2346657,3244645,1,2024-02-20 13:20:30.000000,1711031400,2024-03-21 20:00,Asia/Colombo,None,None,2.0,...,7.180760,1177966.0,"Hotel MaRadha Colombo, 31 St Kilda's Ln, Colom...",79.852672,6.895760,1,Sedan,1,,
7,2394581,3342568,1,2024-03-23 17:42:24.000000,1711566000,2024-03-27 20:00,Europe/Paris,None,None,4.0,...,49.458413,1373269.0,"JAJAJA, 7 Rue Lacharrière, 75011 Paris, France",2.378052,48.862095,3,MPV-5,1,,
8,1945564,3116051,1,2024-01-07 14:35:06.000000,1704691800,2024-01-08 11:00,Asia/Calcutta,None,None,1.0,...,28.568519,935015.0,DEL,77.103104,28.566500,1,Sedan,1,,
9,1646467,2541181,1,2023-04-11 17:52:09.000000,1701014400,2023-11-26 10:00,America/Chicago,None,None,2.0,...,29.314215,82302.0,George Bush Intercontinental Houston Airport (...,-95.336975,29.988329,6,MPV-4,1,,

## create new table with latitutde and longitude reduced to 5 decimal places

In [14]:
ordered_t = select(my_table).order_by(asc(my_table.c.start_ltt), asc(my_table.c.end_ltt))
ordered_t = ordered_t.select_from(my_table)
ordered_t = ordered_t.alias()

In [15]:
# ordered_t = ordered_t.limit(10)
# df = pd.read_sql(ordered_t.limit(10),sql_eng)
# df

In [16]:
lp_ltt_lng_t = select(ordered_t.c.dispatch_id,
                      cast(ordered_t.c.start_ltt, Numeric(9,5)).label('start_ltt_lp'),
                      cast(ordered_t.c.start_lng, Numeric(9,5)).label('start_lng_lp'),
                      cast(ordered_t.c.end_ltt, Numeric(9,5)).label('end_ltt_lp'),
                      cast(ordered_t.c.end_lng, Numeric(9,5)).label('end_lng_lp'))
lp_ltt_lng_t = lp_ltt_lng_t.select_from(ordered_t)
lp_ltt_lng_t = lp_ltt_lng_t.alias()

In [17]:
# df = pd.read_sql(lp_ltt_lng_t, sql_eng)
# df

In [18]:
distinct_start_lp_t = select(lp_ltt_lng_t.c.dispatch_id, 
                         lp_ltt_lng_t.c.start_ltt_lp,
                         # func.max(lp_ltt_lng_t.c.start_ltt_lp).label('unique_start_ltt_lp'), 
                         # func.max(lp_ltt_lng_t.c.start_lng_lp).label('unique_start_lng_lp'),
                         lp_ltt_lng_t.c.start_lng_lp, 
                         lp_ltt_lng_t.c.end_ltt_lp,
                         lp_ltt_lng_t.c.end_lng_lp
                         ).group_by(lp_ltt_lng_t.c.start_ltt_lp).distinct(lp_ltt_lng_t.c.start_lng_lp)#.subquery()
distinct_start_lp_t = distinct_start_lp_t.alias()

In [19]:
# df = pd.read_sql(distinct_start_lp_t, sql_eng)
# df

In [20]:

distinct_end_lp_t = select(lp_ltt_lng_t.c.dispatch_id, 
                         lp_ltt_lng_t.c.start_ltt_lp,
                         lp_ltt_lng_t.c.start_lng_lp,
                         lp_ltt_lng_t.c.end_ltt_lp,
                         lp_ltt_lng_t.c.end_lng_lp
                         ).group_by(lp_ltt_lng_t.c.end_ltt_lp).distinct(lp_ltt_lng_t.c.end_lng_lp)
distinct_end_lp_t = distinct_end_lp_t.alias()

In [21]:

# df = pd.read_sql(distinct_end_lp_t, sql_eng)
# df

In [22]:
fp_zone_start_t = select(
    ordered_t.c, 
    distinct_start_lp_t.c.start_ltt_lp, 
    distinct_start_lp_t.c.start_lng_lp, 
    distinct_start_lp_t.c.end_ltt_lp, 
    distinct_start_lp_t.c.end_lng_lp
    ).select_from(ordered_t
                  .join(distinct_start_lp_t, 
                        ordered_t.c.dispatch_id == distinct_start_lp_t.c.dispatch_id))
df_start = pd.read_sql(fp_zone_start_t, sql_eng)
df_start

,dispatch_id,ride_id,trip_count,ride_inserted_at,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,passenger_count,...,end_ltt,vehicle_class_id,vehicle_class,row_num,route_start,route_end,start_ltt_lp,start_lng_lp,end_ltt_lp,end_lng_lp
0,496634,2388613,1,2022-11-02 21:22:10.000000,1.674913e+09,2023-01-28 10:30,America/Argentina/Ushuaia,None,None,2.0,...,-54.841858,1.0,Sedan,1,,,-54.84330,-68.29580,-54.84186,-68.37252
1,1952052,3119727,1,2024-01-08 16:30:39.000000,1.705246e+09,2024-01-14 12:30,America/Argentina/Ushuaia,None,None,8.0,...,-54.809199,5.0,Minibus-8,1,,,-54.84328,-68.29575,-54.80920,-68.32320
2,2431686,3361701,1,2024-03-29 13:37:26.000000,1.732467e+09,2024-11-24 13:45,America/Argentina/Ushuaia,None,None,2.0,...,-54.809276,3.0,MPV-5,1,,,-54.84223,-68.31189,-54.80928,-68.31659
3,496635,2388614,1,2022-11-02 21:22:10.000000,1.675168e+09,2023-01-31 09:30,America/Argentina/Ushuaia,None,None,2.0,...,-54.843300,1.0,Sedan,1,,,-54.84186,-68.37252,-54.84330,-68.29580
4,1965849,3126904,1,2024-01-10 19:02:39.000000,1.707065e+09,2024-02-04 13:45,America/Argentina/Ushuaia,None,None,2.0,...,-54.843300,1.0,Sedan,1,,,-54.84183,-68.37259,-54.84330,-68.29580
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117340,1815247,3050491,1,2023-12-13 00:18:50.000000,1.702703e+09,2023-12-16 06:17,Europe/Oslo,None,None,4.0,...,69.679899,1.0,Sedan,1,,,69.77751,19.38227,69.67990,18.90727
117341,1011455,2643336,1,2023-06-22 09:02:59.000000,1.687658e+09,2023-06-25 04:00,Europe/Oslo,None,None,4.0,...,69.681935,3.0,MPV-5,1,,,69.79514,19.02246,69.68194,18.91626
117342,2330187,3311361,1,2024-03-13 11:03:31.000000,1.711450e+09,2024-03-26 11:45,Europe/Oslo,None,None,2.0,...,69.977842,1.0,Sedan,1,,,69.86523,23.31799,69.97784,23.35350
117343,2375766,3333627,1,2024-03-20 19:27:16.000000,1.711616e+09,2024-03-28 10:00,Europe/Oslo,None,None,2.0,...,69.865232,1.0,Sedan,1,,,69.91836,23.28534,69.86523,23.31799
117344,1992716,3140888,1,2024-01-15 13:11:38.000000,1.707041e+09,2024-02-04 11:00,Europe/Oslo,None,None,5.0,...,69.977842,3.0,MPV-5,1,,,70.43425,24.50478,69.97784,23.35350

In [23]:
# df_start.to_sql('price_training_2324_start', sql_eng, if_exists='replace', index=True)
# df_start.to_csv('../data/price_training_2324_start.csv', index=False)

In [24]:
fp_zone_end_t = select(
    ordered_t.c,
    distinct_end_lp_t.c.start_ltt_lp,
    distinct_end_lp_t.c.start_lng_lp,
    distinct_end_lp_t.c.end_ltt_lp,
    distinct_end_lp_t.c.end_lng_lp
).select_from(ordered_t
              .join(distinct_end_lp_t, 
                    ordered_t.c.dispatch_id == distinct_end_lp_t.c.dispatch_id)
              )
df_end = pd.read_sql(fp_zone_end_t, sql_eng)
df_end

,dispatch_id,ride_id,trip_count,ride_inserted_at,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,passenger_count,...,end_ltt,vehicle_class_id,vehicle_class,row_num,route_start,route_end,start_ltt_lp,start_lng_lp,end_ltt_lp,end_lng_lp
0,496635,2388614,1,2022-11-02 21:22:10.000000,1675168200,2023-01-31 09:30,America/Argentina/Ushuaia,None,None,2.0,...,-54.843300,1.0,Sedan,1,,,-54.84186,-68.37252,-54.84330,-68.29580
1,2560396,3419727,1,2024-04-22 22:17:24.000000,1714996800,2024-05-06 09:00,America/Argentina/Ushuaia,None,None,4.0,...,-54.842234,3.0,MPV-5,1,,,-54.80735,-68.35211,-54.84223,-68.31189
2,496634,2388613,1,2022-11-02 21:22:10.000000,1674912600,2023-01-28 10:30,America/Argentina/Ushuaia,None,None,2.0,...,-54.841858,1.0,Sedan,1,,,-54.84330,-68.29580,-54.84186,-68.37252
3,1965848,3126903,1,2024-01-10 19:02:38.000000,1706639400,2024-01-30 15:30,America/Argentina/Ushuaia,None,None,2.0,...,-54.841829,1.0,Sedan,1,,,-54.84330,-68.29580,-54.84183,-68.37259
4,556892,2417357,1,2022-12-18 20:16:19.000000,1672594200,2023-01-01 14:30,Argentina Standard Time,None,None,3.0,...,-54.841827,1.0,Sedan,1,,,-54.83956,-68.31224,-54.84183,-68.37265
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199912,1585608,2932061,1,2023-10-31 10:27:09.000000,1699185492,2023-11-05 13:14,Europe/Oslo,None,None,1.0,...,69.763092,1.0,Sedan,1,,,69.64920,18.95532,69.76309,20.46462
199913,1728363,3002392,1,2023-11-24 20:16:15.000000,1701091643,2023-11-27 14:43,Europe/Oslo,None,None,2.0,...,69.777510,1.0,Sedan,1,,,69.67990,18.90727,69.77751,19.38227
199914,2375766,3333627,1,2024-03-20 19:27:16.000000,1711616400,2024-03-28 10:00,Europe/Oslo,None,None,2.0,...,69.865232,1.0,Sedan,1,,,69.91836,23.28534,69.86523,23.31799
199915,2330187,3311361,1,2024-03-13 11:03:31.000000,1711449900,2024-03-26 11:45,Europe/Oslo,None,None,2.0,...,69.977842,1.0,Sedan,1,,,69.86523,23.31799,69.97784,23.35350
199916,2375796,3333654,1,2024-03-20 19:35:02.000000,1711803600,2024-03-30 14:00,Central European Standard Time,None,None,2.0,...,69.977909,1.0,Sedan,1,,,69.86523,23.31799,69.97791,23.34684

In [25]:
# df_end.to_sql('price_training_2324_end', sql_eng, if_exists='replace', index=True)
# df_end.to_csv('../data/price_training_2324_end.csv', index=False)

In [26]:
import requests

In [27]:
from concurrent.futures import ThreadPoolExecutor, as_completed
import httpx
from http import HTTPStatus
from concurrent import futures
from enum import Enum

In [28]:
# df_start.to_sql('price_training_raw_2024_usd_start_deduplicated', sql_eng, if_exists='replace', index=True)
sql_eng = create_engine('sqlite:///../data/price_training_raw.db', echo=False)
connection = sql_eng.connect()
metadata = MetaData()
start_table = Table('price_training_2324_start', metadata, autoload_with=sql_eng)
end_table = Table('price_training_2324_end', metadata, autoload_with=sql_eng)
s = select(end_table).limit(10)
# rp =sql_eng.connect().execute(s)
# df = pd.DataFrame(rp)
df = pd.read_sql(s,sql_eng)
df

,index,dispatch_id,ride_id,trip_count,ride_inserted_at,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,...,end_ltt,vehicle_class_id,vehicle_class,row_num,route_start,route_end,start_ltt_lp,start_lng_lp,end_ltt_lp,end_lng_lp
0,0,496635,2388614,1,2022-11-02 21:22:10.000000,1675168200,2023-01-31 09:30,America/Argentina/Ushuaia,None,None,...,-54.843300,1.0,Sedan,1,,,-54.84186,-68.37252,-54.84330,-68.29580
1,1,2560396,3419727,1,2024-04-22 22:17:24.000000,1714996800,2024-05-06 09:00,America/Argentina/Ushuaia,None,None,...,-54.842234,3.0,MPV-5,1,,,-54.80735,-68.35211,-54.84223,-68.31189
2,2,496634,2388613,1,2022-11-02 21:22:10.000000,1674912600,2023-01-28 10:30,America/Argentina/Ushuaia,None,None,...,-54.841858,1.0,Sedan,1,,,-54.84330,-68.29580,-54.84186,-68.37252
3,3,1965848,3126903,1,2024-01-10 19:02:38.000000,1706639400,2024-01-30 15:30,America/Argentina/Ushuaia,None,None,...,-54.841829,1.0,Sedan,1,,,-54.84330,-68.29580,-54.84183,-68.37259
4,4,556892,2417357,1,2022-12-18 20:16:19.000000,1672594200,2023-01-01 14:30,Argentina Standard Time,None,None,...,-54.841827,1.0,Sedan,1,,,-54.83956,-68.31224,-54.84183,-68.37265
5,5,1762309,3025778,1,2023-12-03 16:54:51.000000,1715095200,2024-05-07 12:20,America/Argentina/Ushuaia,None,None,...,-54.841706,1.0,Sedan,1,,,-54.84330,-68.29580,-54.84171,-68.37298
6,6,1847025,3065245,1,2023-12-18 19:00:08.000000,1705489200,2024-01-17 08:00,America/Argentina/Ushuaia,None,None,...,-54.839562,1.0,Sedan,1,,,-54.80981,-68.31207,-54.83956,-68.31224
7,7,2445680,3367546,1,2024-04-01 13:56:14.000000,1721655300,2024-07-22 10:35,America/Argentina/Ushuaia,None,None,...,-54.839347,1.0,Sedan,1,,,-54.80912,-68.31596,-54.83935,-68.31245
8,8,2493013,3389370,1,2024-04-10 01:08:09.000000,1720015200,2024-07-03 11:00,America/Argentina/Ushuaia,None,None,...,-54.837181,6.0,MPV-4,1,,,-54.84330,-68.29580,-54.83718,-68.36194
9,9,1269529,2626714,1,2023-06-12 00:27:26.000000,1692970200,2023-08-25 10:30,America/Argentina/Ushuaia,None,None,...,-54.836167,1.0,Sedan,1,,,-54.84330,-68.29580,-54.83617,-68.36157

In [29]:

query = [select(start_table), select(end_table)]
result_table = ['label_2324_start', 'label_2324_end']

In [30]:

FZPQueryStatus = Enum('FZPQueryStatus', 'JsonError HTTPXStatusError HTTPXError IndexOrKeyError DictError NoFixedPrice Success')
fzp = {'from': None, 'to': None}
def get_one_fixed_zone(start_ltt, start_lng, end_ltt, end_lng) -> FZPQueryStatus:
    global fzp
    params = {
        'from_lat': start_ltt,
        'from_lng': start_lng,
        'to_lat': end_ltt,
        'to_lng': end_lng,
    }
    try:
        # response = requests.get(url=url, params=params)
        response = httpx.get(url=url, params=params)
    except httpx.HTTPStatusError as exc:
        return FZPQueryStatus.HTTPXStatusError
    except Exception as exc:
        return FZPQueryStatus.HTTPXError

    try:
        res = response.json()
    except Exception as exc:
        return FZPQueryStatus.JsonError
    try:
        fix_price_zones = res['fleets'][0]['vehicle_classes'][0]['price_detail']['base_pricing']['fix_price_detail']
    except Exception as exc:
        return FZPQueryStatus.IndexOrKeyError
    # print('4')
    if not isinstance(fix_price_zones,dict):
        return FZPQueryStatus.DictError
    else:
        try:
            fzp['from'] = fix_price_zones['from']
            fzp['to']   = fix_price_zones['to']
            return FZPQueryStatus.Success
        except KeyError as e:
            return FZPQueryStatus.NoFixedPrice

In [31]:
import requests
url = 'https://j1j495o5pk.execute-api.us-east-2.amazonaws.com/upncoming/ride-pricings'

In [37]:
csv_file_list = ['../data/price_training_2324_start.csv',
             '../data/price_training_2324_end.csv']
csv_result_file_list = ['../data/price_training_2324_start_result.csv',
                 '../data/price_training_2324_end_result.csv']
total_rows = [df_start.shape[0], df_end.shape[0]]
result_csv = '../data/dispatch_fzp_2324_label_list.csv'
total_rows

chunk_size = 10000

[117345, 199917]

In [38]:
non_fzp_count = 0
max_concurrent = 96
for t in [1]: #range(2):
    for i,chunk in enumerate(tqdm(pd.read_sql(query[t],connection,index_col='dispatch_id', chunksize=chunk_size),     total=total_rows[t]//chunk_size+1, desc='Overall Progress')):
        chunk = chunk.astype({'route_start': str, 'route_end': str})
        non_fzp_count_chunk = 0
        # get_fixed_zone_chunk(chunk)
        
        with ThreadPoolExecutor(max_workers=max_concurrent) as executor:
            to_do_map = {} # list[futures.Future] = [] 
            # for ind,r in tqdm(chunk.iterrows(),total=chunk_size,desc='chunk progress', leave=False):
            for ind,r in chunk.iterrows():
                future = executor.submit(get_one_fixed_zone, r['start_ltt_lp'], r['start_lng_lp'], r['end_ltt_lp'],     r['end_lng_lp'])
                to_do_map[future] = ind
            done_iter = as_completed(to_do_map)
            done_iter = tqdm(done_iter, total=len(to_do_map), desc='chunk progress', leave=False)
            
            for future in done_iter:
                try:
                    status = future.result()
                except Exception as e:
                    # print(f"Exception: {e}")
                    continue
                
                if status == FZPQueryStatus.Success:
                    ind = to_do_map[future]
                    try:
                        chunk.at[ind, 'route_start'] = fzp['from']
                        chunk.at[ind, 'route_end'] = fzp['to']
                    except KeyError as e:
                        non_fzp_count_chunk += 1
                        # print(f"\r {e}: {non_fzp_count_chunk}/{chunk_size}")
                        continue
                    except Exception as e:
                        non_fzp_count_chunk += 1
                        # print(f"\r {e}: {non_fzp_count_chunk}/{chunk_size}")
                        continue
                else:
                    non_fzp_count_chunk += 1
                    # print(f"\r non fzp chunk: {non_fzp_count_chunk}/{chunk_size}")
                    continue
            
        non_fzp_count += non_fzp_count_chunk
        scanned_row_number = (i+1)*chunk_size
        try:
            # pd.DataFrame(data=route_list, columns=['dispatch_id', 'route_start', 'route_end']).to_csv(result_csv,     mode='a', header=False)
            with open(csv_result_file_list[t], 'a') as f:
                chunk.to_csv(f, header=f.tell()==0,chunksize=chunk_size)
            # chunk.to_csv(path_or_buf=csv_result_file_list[0],mode='a',chunksize=chunk_size)
            # chunk.to_sql(result_table[0], sql_eng, if_exists='append', index=True)
            print(f"\r Non_FZP count: {non_fzp_count}/{scanned_row_number}")
        except Exception as e:
            print(f"\r {e}, Non_FZP count: {non_fzp_count}/{scanned_row_number} ")
            continue

Overall Progress:   0%|          | 0/20 [00:00<?, ?it/s]

chunk progress:   0%|          | 0/10000 [00:00<?, ?it/s]

 Non_FZP count: 1096/10000

chunk progress:   0%|          | 0/10000 [00:00<?, ?it/s]

 Non_FZP count: 3893/20000

chunk progress:   0%|          | 0/10000 [00:00<?, ?it/s]

 Non_FZP count: 5817/30000

chunk progress:   0%|          | 0/10000 [00:00<?, ?it/s]

 Non_FZP count: 7266/40000

chunk progress:   0%|          | 0/10000 [00:00<?, ?it/s]

 Non_FZP count: 9444/50000

chunk progress:   0%|          | 0/10000 [00:00<?, ?it/s]

 Non_FZP count: 11152/60000

chunk progress:   0%|          | 0/10000 [00:00<?, ?it/s]

 Non_FZP count: 13492/70000

chunk progress:   0%|          | 0/10000 [00:00<?, ?it/s]

 Non_FZP count: 14830/80000

chunk progress:   0%|          | 0/10000 [00:00<?, ?it/s]

 Non_FZP count: 16782/90000

chunk progress:   0%|          | 0/10000 [00:00<?, ?it/s]

 Non_FZP count: 18843/100000

chunk progress:   0%|          | 0/10000 [00:00<?, ?it/s]

 Non_FZP count: 20633/110000

chunk progress:   0%|          | 0/10000 [00:00<?, ?it/s]

 Non_FZP count: 21647/120000

chunk progress:   0%|          | 0/10000 [00:00<?, ?it/s]

 Non_FZP count: 24253/130000

chunk progress:   0%|          | 0/10000 [00:00<?, ?it/s]

 Non_FZP count: 25937/140000

chunk progress:   0%|          | 0/10000 [00:00<?, ?it/s]

 Non_FZP count: 27320/150000

chunk progress:   0%|          | 0/10000 [00:00<?, ?it/s]

 Non_FZP count: 28749/160000

chunk progress:   0%|          | 0/10000 [00:00<?, ?it/s]

 Non_FZP count: 31034/170000

chunk progress:   0%|          | 0/10000 [00:00<?, ?it/s]

 Non_FZP count: 32669/180000

chunk progress:   0%|          | 0/10000 [00:00<?, ?it/s]

 Non_FZP count: 34456/190000

chunk progress:   0%|          | 0/9917 [00:00<?, ?it/s]

 Non_FZP count: 37025/200000

In [ ]:
# non_fzp_count = 0
# max_concurrent = 20
# for i,chunk in enumerate(tqdm(pd.read_csv(csv_file_list[0],index_col='dispatch_id', chunksize=chunk_size), total=total_rows[0]//chunk_size+1, desc='Overall Progress')):
#     chunk = chunk.astype({'route_start': str, 'route_end': str})
#     non_fzp_count_chunk = 0
#     # get_fixed_zone_chunk(chunk)
#     
#     with ThreadPoolExecutor(max_workers=max_concurrent) as executor:
#         to_do_map = {} # list[futures.Future] = [] 
#         # for ind,r in tqdm(chunk.iterrows(),total=chunk_size,desc='chunk progress', leave=False):
#         for ind,r in chunk.iterrows():
#             future = executor.submit(get_one_fixed_zone, r['start_ltt_lp'], r['start_lng_lp'], r['end_ltt_lp'], r['end_lng_lp'])
#             to_do_map[future] = ind
#         done_iter = as_completed(to_do_map)
#         done_iter = tqdm(done_iter, total=len(to_do_map), desc='chunk progress', leave=False)
#         
#         for future in done_iter:
#             try:
#                 status = future.result()
#             except Exception as e:
#                 # print(f"Exception: {e}")
#                 continue
#             
#             if status == FZPQueryStatus.Success:
#                 ind = to_do_map[future]
#                 try:
#                     chunk.at[ind, 'route_start'] = fzp['from']
#                     chunk.at[ind, 'route_end'] = fzp['to']
#                 except KeyError as e:
#                     non_fzp_count_chunk += 1
#                     # print(f"\r {e}: {non_fzp_count_chunk}/{chunk_size}")
#                     continue
#                 except Exception as e:
#                     non_fzp_count_chunk += 1
#                     # print(f"\r {e}: {non_fzp_count_chunk}/{chunk_size}")
#                     continue
#             else:
#                 non_fzp_count_chunk += 1
#                 # print(f"\r non fzp chunk: {non_fzp_count_chunk}/{chunk_size}")
#                 continue
#         
#     non_fzp_count += non_fzp_count_chunk
#     scanned_row_number = (i+1)*chunk_size
#     try:
#         # pd.DataFrame(data=route_list, columns=['dispatch_id', 'rou:w
#         # te_start', 'route_end']).to_csv(result_csv, mode='a', header=False)
#         with open(csv_result_file_list[0], 'a') as f:
#             chunk.to_csv(f, header=f.tell()==0,chunksize=chunk_size)
#         # chunk.to_csv(path_or_buf=csv_result_file_list[0],mode='a',chunksize=chunk_size)
#         print(f"\r Non_FZP count: {non_fzp_count}/{scanned_row_number}")
#     except Exception as e:
#         print(f"\r {e}, Non_FZP count: {non_fzp_count}/{scanned_row_number} ")
#         continue

In [45]:
import requests
url = 'https://j1j495o5pk.execute-api.us-east-2.amazonaws.com/upncoming/ride-pricings'
def get_one_fixed_zone1(start_ltt, start_lng, end_ltt, end_lng):
    params = {
        'from_lat': start_ltt,
        'from_lng': start_lng,
        'to_lat': end_ltt,
        'to_lng': end_lng,
    }
    try:
        response = requests.get(url=url, params=params)
    except requests.exceptions.Timeout:
        print('Timeout')
        return None
    except requests.exceptions.TooManyRedirects:
        print('TooManyRedirects')
        return None
        # Tell the user their URL was bad and try a different one
    except requests.exceptions.RequestException as e:
        print('RequestException, Catastrophic error!')
        return None

    except Exception as e:
        print(f"request: {e}")
        return None
    # print('2')
    try:
        res = response.json()
    except Exception as e:
        print(f"json: {e}")
        return None
    # print('3')
    try:
        fix_price_zones = res['fleets'][0]['vehicle_classes'][0]['price_detail']['base_pricing']['fix_price_detail']
    except KeyError as e:
        # print(f"No Fixed Price!")
        return None
    except IndexError as e:
        # print("IndexError for fix_price_zones")
        return None
    except Exception as e:
        # print(f"dict: {e}")
        return None
    # print('4')
    if not isinstance(fix_price_zones,dict):
        # print(f"No fix price: {fix_price_zones}")
        return None
    else:
        try:
            return {'from': fix_price_zones['from'], 'to': fix_price_zones['to']}
        except KeyError as e:
            # print("KeyError for route")
            return None

non_fzp_count = 0
for i,chunk in enumerate(tqdm(pd.read_csv(csv_file_list[0],index_col='dispatch_id', chunksize=chunk_size), total=total_rows[0]//chunk_size+1, desc='Overall Progress')):
    chunk = chunk.astype({'route_start': str, 'route_end': str})
    non_fzp_count_chunk = 0
    # get_fixed_zone_chunk(chunk)
    for ind,r in tqdm(chunk.iterrows(),total=chunk_size,desc='chunk progress', leave=False):
        fpz = get_one_fixed_zone1(r['start_ltt_lp'], r['start_lng_lp'], r['end_ltt_lp'], r['end_lng_lp'])
        if fpz is None:
            non_fzp_count_chunk += 1
            # print(f"\r non fzp chunk: {non_fzp_count_chunk}/{chunk_size}")
            continue
        try:
            chunk.at[ind, 'route_start'] = fpz['from']
            chunk.at[ind, 'route_end'] = fpz['to']
        except KeyError as e:
            non_fzp_count_chunk += 1
            # print(f"\r {e}: {non_fzp_count_chunk}/{chunk_size}")
            continue
        except Exception as e:
            non_fzp_count_chunk += 1
            # print(f"\r {e}: {non_fzp_count_chunk}/{chunk_size}")
            continue

    non_fzp_count += non_fzp_count_chunk
    scanned_row_number = (i+1)*chunk_size
    try:
        # pd.DataFrame(data=route_list, columns=['dispatch_id', 'rou:w
        # te_start', 'route_end']).to_csv(result_csv, mode='a', header=False)
        with open(csv_result_file_list[0], 'a') as f:
            chunk.to_csv(f, header=f.tell()==0,chunksize=chunk_size)
        # chunk.to_csv(path_or_buf=csv_result_file_list[0],mode='a',chunksize=chunk_size)
        print(f"\r Non_FZP count: {non_fzp_count}/{scanned_row_number}")
    except Exception as e:
        print(f"\r {e}, Non_FZP count: {non_fzp_count}/{scanned_row_number} ")
        continue

Overall Progress:   0%|          | 0/118 [00:00<?, ?it/s]

chunk progress:   0%|          | 0/1000 [00:00<?, ?it/s]

KeyboardInterrupt:

In [ ]:
df.loc[:,'route_start'] = 'Zone 0'
df.loc[:,'route_end'] = 'Zone 1'
df

In [ ]:
# for chunk in tqdm(pd.read_csv(csv_file_list[0],index_col='dispatch_id', chunksize=chunk_size), total=total_rows[0]//chunk_size+1, desc='Overall Progress'):
# # for chunk in pd.read_csv(csv_file_list[0],index_col='dispatch_id', chunksize=chunk_size):
#     # [chunk[r] for r in chunk]
#     # l = [r for r in chunk.iterrows()]
#     # l
#     # print(chunk.dtypes)
#     # route_list = []
#     chunk = chunk.astype({'route_start': str, 'route_end': str})
#     for i,r in tqdm(chunk.iterrows(),total=chunk_size,desc='chunk progress', leave=False):
#     # for i,r in chunk.iterrows():
#         # l = [i, r['start_ltt'], r['start_lng'], r['end_ltt'], r['end_lng']]
#         # print(l)
#         params = {
#             'from_lat': r['start_ltt_lp'],
#             'from_lng': r['start_lng_lp'],
#             'to_lat': r['end_ltt_lp'],
#             'to_lng': r['end_lng_lp'],
#         }
#         try:
#             response = requests.get(url=url, params=params)
#         except requests.exceptions.Timeout:
#             print('Timeout')
#             continue
#         except requests.exceptions.TooManyRedirects:
#             print('TooManyRedirects')
#             continue
#             # Tell the user their URL was bad and try a different one
#         except requests.exceptions.RequestException as e:
#             print('RequestException, Catastrophic error!')
#             continue
#             # catastrophic error. bail.
#             # raise SystemExit(e)
# 
#         except Exception as e:
#             print(f"request: {e}")
#             continue
#         # print('2')
#         try:
#             res = response.json()
#         except Exception as e:
#             print(f"json: {e}")
#             continue
#         # print('3')
#         try:
#             fix_price_zones = res['fleets'][0]['vehicle_classes'][0]['price_detail']['base_pricing']['fix_price_detail']
#         except KeyError as e:
#             print(f"No Fixed Price!")
#             continue
#         except IndexError as e:
#             print("IndexError for fix_price_zones")
#             continue
#         except Exception as e:
#             print(f"dict: {e}")
#             continue
#         # print('4')
#         if not isinstance(fix_price_zones,dict):
#             print(f"No fix price: {fix_price_zones}")
#         else:
#             try:
#                 # route_list.append((i, fix_price_zones['from'], fix_price_zones['to']))
#                 # fix_zone_routes_list.append(route)
#                 chunk.at[i, 'route_start'] = fix_price_zones['from']
#                 chunk.at[i, 'route_end'] = fix_price_zones['to']
#                 # ins = insert(fixed_zone_routes).values(
#                 #     start=fix_price_zones['from'], end=fix_price_zones['from'], dispatch_id= pt        ._mapping['dispatch_id'])
#                 # stmt = (
#                 #     update(raw)  # 'raw' is your table object
#                 #     .where(raw.c.dispatch_id == int(i))
#                 #     .values(
#                 #         route_start = fix_price_zones['from'],
#                 #         route_end = fix_price_zones['to']
#                 #     )
#                 # )
#                 # conn.execute(stmt)
#                 # conn.commit()
#             except KeyError as e:
#                 print("KeyError for route")
#                 continue
#     
#     try:
#         # pd.DataFrame(data=route_list, columns=['dispatch_id', 'route_start', 'route_end']).to_csv(result_csv, mode='a', header=False)
#         chunk.to_csv(path_or_buf=csv_result_file_list[0],mode='a',chunksize=chunk_size)
#     except Exception as e:
#         print(f"csv: {e}")
#         continue
#     
#     # with sqlite_eng.begin() as conn:
#     #     conn.execute(
#     #         stmt, 
#     #         [
#     #             {
#     #                 'b_dispatch_id': i,
#     #                 'route_start': r['route_start'],
#     #                 'route_end': r['route_end']
#     #             }
#     #             for i,r in chunk.iterrows()
#     #         ],
#     #     )
#     #     conn.commit()
#

# Query FP-Server and add label to database

In [ ]:
# new_columns = [Column(col.name, col.type, primary_key=col.primary_key) for col in my_table.columns]
# new_table = Table('price_training_raw_2024_usd_reordered', metadata, *new_columns)
# new_table.create(sql_eng)
new_table = Table('price_training_raw_2024_usd_reordered', metadata, autoload_with=sql_eng)

In [ ]:
Session = sessionmaker(bind=sql_eng)
session = Session()

## insert data into new table: fp_zone_start_t & fp_zone_end_t

In [ ]:
chunk_size = 1000
total_rows = len(ordered_rows)
total_rows
total = total_rows//chunk_size+1
total

In [ ]:
for chunk in tqdm(range(total), total=total, desc='Overall Processing'):
    start = chunk*chunk_size
    end = (chunk+1)*chunk_size
    if end > total_rows:
        end = total_rows
    chunk_data = ordered_rows[start:end]
    batch = [dict(zip(cols,row)) for row in chunk_data]
    result = session.execute(insert(new_table).values(batch))
    session.commit()
    # for row in tqdm(chunk_data, total=len(chunk_data), desc='Chunk Processing'):
    #     session.execute(new_table.insert().values(row))
session.close()

In [ ]:
df = pd.DataFrame(data=ordered_rows)

In [ ]:
df = pd.read_sql(fp_zone_t, sql_eng)
df

In [ ]:
# distinct_t = select(distinct(lp_ltt_lng_t.c.start_lng_lp))
# distinct_t = distinct_t.limit(1000)#.distinct(lp_ltt_lng_t.c.start_ltt)
# df = pd.read_sql(distinct_t, sql_eng)
# df

## Create new table with ordered data

In [ ]:
ordered_t = select(my_table).where(
    and_(
        my_table.c.start_ltt.isnot(None),
        my_table.c.start_lng.isnot(None),
    )
).order_by(asc(my_table.c.start_ltt), asc(my_table.c.start_ltt))
ordered_t = ordered_t.select_from(my_table)

In [ ]:
with sql_eng.connect() as connection:
    result = connection.execute(ordered_t)
    ordered_rows = result.fetchall()
# ordered_rows[:3]

In [ ]:
data = ordered_rows[:10]
cols = [c.name for c in ordered_t.subquery().columns]
df = pd.DataFrame(data=data, columns=cols)
df

In [ ]:

batch = [dict(zip(cols, row)) for row in data]
batch[:2]

In [ ]:
for row in tqdm(result, total=unique_count):
    for chunk in tqdm(pd.read_sql(query.statement, conn, index_col='dispatch_id', chunksize=chunk_size), total=total_rows//chunk_size+1, desc='Overall Processing'):
    route_list = []

In [ ]:
with sql_eng.connect() as conn:
    result = conn.execute(ordered_t)
    for row in tqdm(result, total=unique_count):
        session.execute(new_table.insert().values(row))
    session.commit()

In [ ]:
# list(my_table.columns)

In [ ]:
# metadata_new = MetaData()
# my_table.to_metadata(metadata_new)
# metadata_new.tables

In [ ]:
new_table = Table('price_training_raw_2024_usd_geo_ordered', metadata, *my_table.columns)
# list(new_table.columns)
# new_table.name = 'price_training_raw_2024_usd_geo_ordered'
# metadata_new.create_all(sql_eng)

# reduce precision of start_ltt, start_lng, end_ltt, end_lng by 3 digits

In [ ]:
df.loc[:,'route_start'] = 'start'
df

In [ ]:

stmt = (
    update(my_table)  # 'raw' is your table object
    .where(my_table.c.dispatch_id == 822019)
    .values(
        route_start='New Zone C',
        route_end='New Zone D'
    )
)
print(stmt)

In [ ]:
compiled = stmt.compile()
compiled.params

In [ ]:
with sql_eng.connect() as conn:
    result = conn.execute(stmt)
    conn.commit()

In [ ]:
s = select(my_table).where(my_table.c.dispatch_id == 822019)
rp = sql_eng.connect().execute(s)
results = rp.fetchall()
results

In [ ]:
df

In [ ]:
for i,r in df.iterrows():
    l = [i, r['ride_id'], r['dispatch_amount'],r['fleet']]
    # print(r)
    df.at[i,'route_end'] = 'Shanghai'
    stmt = (
        update(my_table)
        .where(my_table.c.dispatch_id == int(i))
        .values(
            route_start='Beijing',
            route_end='Shanghai',
        )
    )
    with sql_eng.connect() as conn:
        conn.execute(stmt)
        conn.commit()
    # print('----')
    print(l)
df

# Update data batchwise in sqlite db

In [ ]:
stmt = (
    update(my_table)  # 'raw' is your table object
    .where(my_table.c.dispatch_id == bindparam('b_dispatch_id'))
    .values(
        route_start=bindparam('route_start'),
        route_end=bindparam('route_end')
    )
)
print(stmt)

In [ ]:
l = [ 
            {'dispatch_id': i,
             'route_start': r['route_start'],
             'route_end': r['route_end']} 
            for i,r in df.iterrows()
        ]
l

In [ ]:

with sql_eng.begin() as conn:
    conn.execute(
        stmt,
        [ 
            {'b_dispatch_id': i,
             'route_start': r['route_start'],
             'route_end': r['route_end']} 
            for i,r in df.iterrows()
        ],
    )
    conn.commit()

In [ ]:
s = select(my_table).limit(20)
rp = sql_eng.connect().execute(s)
results = rp.fetchall()
df = pd.DataFrame(results)
df

In [ ]:
for i,r in df.iterrows():
    print(i, r['ride_id'], r['dispatch_amount'],r['fleet'])

In [ ]:

# df.to_sql('price_training_raw_2024_usd', sqlite_eng, if_exists= 'replace',index=True, index_label='dispatch_id')

In [ ]:
for r in df.itertuples():
    # print(r)
    print(r.ride_id, r.fleet)
    df.at[r.Index, 'route_start'] = 'PVG'
    # r.route_start = 'start'
    # r.route_end = 'end'
df

In [ ]:

# df.to_sql('price_training_raw_2024_usd', sqlite_eng, if_exists= 'replace',index=True, index_label='dispatch_id')

In [ ]:
#| hide
import nbdev; nbdev.nbdev_export()