# core data utilities

> core utilities for data processing: 
> datetime processing, time zone processing, validity, filtering

In [1]:
#| default_exp data.database.deduplication

In [2]:
from asyncio import as_completed
from threading import Thread

#| hide
from nbdev.showdoc import *

In [3]:
#| hide
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [4]:
#| export
from datetime import datetime
import pandas as pd
import pytz
#| export
pd.options.mode.chained_assignment = None

# Precision reduction for start_ltt, start_lng, end_ltt, end_lng and pick distinct values

In [5]:
from tqdm.notebook import tqdm
from sqlalchemy import create_engine, select, func, distinct, MetaData, Table, update, bindparam, Column, insert, desc, asc, and_, or_, not_, Numeric, cast, func
from sqlalchemy.orm import sessionmaker, aliased
import pandas as pd
import numpy as np

In [6]:
sql_eng = create_engine('sqlite:///../data/price_ts.db', echo=False)
conn = sql_eng.connect()
my_table = Table('price_training_newyork', MetaData(), autoload_with=sql_eng)

In [7]:
query = select(func.count(distinct(my_table.c.dispatch_id)))

In [8]:
with sql_eng.connect() as connection:
    result = connection.execute(query)
    unique_count = result.scalar()
    
print(unique_count)

321254

In [9]:
query = select(my_table).limit(10)
df = pd.read_sql(query, conn, index_col='dispatch_id')
# df[['route_start','route_end']]
df

,ride_id,trip_count,ride_inserted_at,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,passenger_count,luggage_count,...,start_ltt,end_place_id,end_place,end_lng,end_ltt,vehicle_class_id,vehicle_class,row_num,route_start,route_end
dispatch_id,,,,,,,,,,,,,,,,,,,,,
155,2164872,1,2020-05-25 06:45:14.000000,1590431400,2020-05-25 14:30,Eastern Daylight Time,None,None,1.0,1.0,...,40.808108,9,John F. Kennedy International Airport,-73.778139,40.641311,1.0,Sedan,1,,
8144,2168707,1,2021-02-22 12:46:16.000000,1614125700,2021-02-23 19:15,America/New_York,None,None,2.0,2.0,...,40.643351,3379,7 W 45th St,-73.980025,40.755955,1.0,Sedan,1,,
8300,2168774,1,2021-02-26 23:20:34.000000,1614474900,2021-02-27 20:15,Eastern Standard Time,None,None,2.0,2.0,...,40.641311,3440,98 Frelinghuysen Ave,-74.185363,40.718531,1.0,Sedan,1,,
11335,2170440,1,2021-04-09 12:39:59.000000,1619530620,2021-04-27 09:37,America/New_York,None,None,1.0,1.0,...,40.979118,9,John F. Kennedy International Airport,-73.778139,40.641311,1.0,Sedan,1,,
11477,2170519,1,2021-04-10 18:54:08.000000,1628247600,2021-08-06 07:00,America/New_York,None,None,4.0,4.0,...,40.758586,11,New York LaGuardia Airport,-73.873966,40.776927,6.0,MPV-4,1,,
12637,2171119,1,2021-04-22 17:38:07.000000,1619281800,2021-04-24 12:30,Eastern Daylight Time,None,None,1.0,3.0,...,40.710009,3227,"LaGuardia Airport Terminal B - Ground Level, Q...",-73.872421,40.772663,1.0,Sedan,1,,
16273,2172967,1,2021-05-17 13:53:28.000000,1621607400,2021-05-21 10:30,America/New_York,None,None,1.0,1.0,...,40.756126,2152,333 Meadowlands Pkwy,-74.082241,40.779560,1.0,Sedan,1,,
16501,2173116,1,2021-05-18 16:40:24.000000,1622147400,2021-05-27 16:30,Eastern Daylight Time,None,None,1.0,1.0,...,41.068332,5985,None,-73.501362,41.510865,1.0,Sedan,1,,
16544,2173142,1,2021-05-18 20:27:26.000000,1626800700,2021-07-20 13:05,America/New_York,None,None,3.0,3.0,...,40.757692,11,New York LaGuardia Airport,-73.873966,40.776927,1.0,Sedan,1,,
16625,2173177,1,2021-05-19 02:04:00.000000,1621958100,2021-05-25 11:55,America/New_York,None,None,3.0,3.0,...,40.750501,9,John F. Kennedy International Airport,-73.778139,40.641311,1.0,Sedan,1,,

In [10]:
# query = select(my_table)
# df = pd.read_sql(query, conn)
# df[['route_start','route_end']]

In [11]:
# df = df.drop_duplicates(subset=['dispatch_id'],keep='first')
# df = df[~df['fleet']]

In [13]:
# len(df)

2238848

In [12]:
# df.to_sql('price_training_2324_clean', sql_eng, if_exists='replace', index=True)

2238848

# order by start_ltt, start_lng, end_ltt, end_lng

In [10]:
sql_eng = create_engine('sqlite:///../data/price_ts.db', echo=False)
conn = sql_eng.connect()
metadata = MetaData()
my_table = Table('price_training_newyork', metadata, autoload_with=sql_eng)

In [13]:
metadata.reflect(bind=sql_eng)
raw_t = metadata.tables['price_training_newyork']
s = select(raw_t).limit(10)
rp = sql_eng.connect().execute(s)
df = pd.DataFrame(rp)
df

,dispatch_id,ride_id,trip_count,ride_inserted_at,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,passenger_count,...,start_ltt,end_place_id,end_place,end_lng,end_ltt,vehicle_class_id,vehicle_class,row_num,route_start,route_end
0,155,2164872,1,2020-05-25 06:45:14.000000,1590431400,2020-05-25 14:30,Eastern Daylight Time,None,None,1.0,...,40.808108,9,John F. Kennedy International Airport,-73.778139,40.641311,1.0,Sedan,1,,
1,8144,2168707,1,2021-02-22 12:46:16.000000,1614125700,2021-02-23 19:15,America/New_York,None,None,2.0,...,40.643351,3379,7 W 45th St,-73.980025,40.755955,1.0,Sedan,1,,
2,8300,2168774,1,2021-02-26 23:20:34.000000,1614474900,2021-02-27 20:15,Eastern Standard Time,None,None,2.0,...,40.641311,3440,98 Frelinghuysen Ave,-74.185363,40.718531,1.0,Sedan,1,,
3,11335,2170440,1,2021-04-09 12:39:59.000000,1619530620,2021-04-27 09:37,America/New_York,None,None,1.0,...,40.979118,9,John F. Kennedy International Airport,-73.778139,40.641311,1.0,Sedan,1,,
4,11477,2170519,1,2021-04-10 18:54:08.000000,1628247600,2021-08-06 07:00,America/New_York,None,None,4.0,...,40.758586,11,New York LaGuardia Airport,-73.873966,40.776927,6.0,MPV-4,1,,
5,12637,2171119,1,2021-04-22 17:38:07.000000,1619281800,2021-04-24 12:30,Eastern Daylight Time,None,None,1.0,...,40.710009,3227,"LaGuardia Airport Terminal B - Ground Level, Q...",-73.872421,40.772663,1.0,Sedan,1,,
6,16273,2172967,1,2021-05-17 13:53:28.000000,1621607400,2021-05-21 10:30,America/New_York,None,None,1.0,...,40.756126,2152,333 Meadowlands Pkwy,-74.082241,40.779560,1.0,Sedan,1,,
7,16501,2173116,1,2021-05-18 16:40:24.000000,1622147400,2021-05-27 16:30,Eastern Daylight Time,None,None,1.0,...,41.068332,5985,None,-73.501362,41.510865,1.0,Sedan,1,,
8,16544,2173142,1,2021-05-18 20:27:26.000000,1626800700,2021-07-20 13:05,America/New_York,None,None,3.0,...,40.757692,11,New York LaGuardia Airport,-73.873966,40.776927,1.0,Sedan,1,,
9,16625,2173177,1,2021-05-19 02:04:00.000000,1621958100,2021-05-25 11:55,America/New_York,None,None,3.0,...,40.750501,9,John F. Kennedy International Airport,-73.778139,40.641311,1.0,Sedan,1,,

## create new table with latitutde and longitude reduced to 5 decimal places

In [14]:
ordered_t = select(my_table).order_by(asc(my_table.c.start_ltt), asc(my_table.c.end_ltt))
ordered_t = ordered_t.select_from(my_table)
ordered_t = ordered_t.alias()

In [15]:
# ordered_t = ordered_t.limit(10)
# df = pd.read_sql(ordered_t.limit(10),sql_eng)
# df

In [16]:
lp_ltt_lng_t = select(ordered_t.c.dispatch_id,
                      cast(ordered_t.c.start_ltt, Numeric(9,5)).label('start_ltt_lp'),
                      cast(ordered_t.c.start_lng, Numeric(9,5)).label('start_lng_lp'),
                      cast(ordered_t.c.end_ltt, Numeric(9,5)).label('end_ltt_lp'),
                      cast(ordered_t.c.end_lng, Numeric(9,5)).label('end_lng_lp'))
lp_ltt_lng_t = lp_ltt_lng_t.select_from(ordered_t)
lp_ltt_lng_t = lp_ltt_lng_t.alias()

In [17]:
# df = pd.read_sql(lp_ltt_lng_t, sql_eng)
# df

In [18]:
distinct_start_lp_t = select(lp_ltt_lng_t.c.dispatch_id, 
                         lp_ltt_lng_t.c.start_ltt_lp,
                         # func.max(lp_ltt_lng_t.c.start_ltt_lp).label('unique_start_ltt_lp'), 
                         # func.max(lp_ltt_lng_t.c.start_lng_lp).label('unique_start_lng_lp'),
                         lp_ltt_lng_t.c.start_lng_lp, 
                         lp_ltt_lng_t.c.end_ltt_lp,
                         lp_ltt_lng_t.c.end_lng_lp
                         ).group_by(lp_ltt_lng_t.c.start_ltt_lp).distinct(lp_ltt_lng_t.c.start_lng_lp)#.subquery()
distinct_start_lp_t = distinct_start_lp_t.alias()

In [19]:
# df = pd.read_sql(distinct_start_lp_t, sql_eng)
# df

In [20]:

distinct_end_lp_t = select(lp_ltt_lng_t.c.dispatch_id, 
                         lp_ltt_lng_t.c.start_ltt_lp,
                         lp_ltt_lng_t.c.start_lng_lp,
                         lp_ltt_lng_t.c.end_ltt_lp,
                         lp_ltt_lng_t.c.end_lng_lp
                         ).group_by(lp_ltt_lng_t.c.end_ltt_lp).distinct(lp_ltt_lng_t.c.end_lng_lp)
distinct_end_lp_t = distinct_end_lp_t.alias()

In [21]:

# df = pd.read_sql(distinct_end_lp_t, sql_eng)
# df

In [22]:
fp_zone_start_t = select(
    ordered_t.c, 
    distinct_start_lp_t.c.start_ltt_lp, 
    distinct_start_lp_t.c.start_lng_lp, 
    distinct_start_lp_t.c.end_ltt_lp, 
    distinct_start_lp_t.c.end_lng_lp
    ).select_from(ordered_t
                  .join(distinct_start_lp_t, 
                        ordered_t.c.dispatch_id == distinct_start_lp_t.c.dispatch_id))
df_start = pd.read_sql(fp_zone_start_t, sql_eng)
df_start

,dispatch_id,ride_id,trip_count,ride_inserted_at,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,passenger_count,...,end_ltt,vehicle_class_id,vehicle_class,row_num,route_start,route_end,start_ltt_lp,start_lng_lp,end_ltt_lp,end_lng_lp
0,2582811,3429849,1,2024-04-27 00:39:15.000000,1714221000,2024-04-27 08:30,Eastern Daylight Time,None,None,1.0,...,40.723663,1.0,Sedan,1,,,39.94883,-75.14539,40.72366,-74.03658
1,1977485,3131054,1,2024-01-12 01:29:42.000000,1705233600,2024-01-14 07:00,Eastern Standard Time,None,None,0.0,...,39.970736,4.0,Business SUV,1,,,39.97074,-83.09808,39.97074,-83.09808
2,1379613,2829838,1,2023-09-19 00:49:42.000000,1695088800,2023-09-18 22:00,Eastern Daylight Time,None,None,2.0,...,38.897580,6.0,MPV-4,1,,,40.04906,-74.23156,38.89758,-77.01078
3,353452,2327721,1,2022-07-14 18:08:59.000000,1658163600,2022-07-18 13:00,Eastern Daylight Time,None,None,2.0,...,40.649604,1.0,Sedan,1,,,40.12898,-74.07075,40.64960,-73.80311
4,913243,2595807,1,2023-05-22 18:37:54.000000,1685330100,2023-05-28 23:15,Eastern Daylight Time,None,None,2.0,...,40.724635,6.0,MPV-4,1,,,40.13395,-74.03008,40.72463,-73.99111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5383,1226399,2754793,1,2023-08-13 15:13:42.000000,1692018000,2023-08-14 09:00,America/New_York,None,None,2.0,...,40.894520,1.0,Sedan,1,,,41.48243,-71.31471,40.89452,-72.46684
5384,562200,2404131,1,2022-11-30 21:39:39.000000,1671726300,2022-12-22 11:25,America/New_York,None,None,1.0,...,40.776927,1.0,Sedan,1,,,41.74674,-74.08847,40.77693,-73.87397
5385,1204338,2744872,1,2023-08-08 08:03:28.000000,1691650800,2023-08-10 03:00,Eastern Daylight Time,None,None,4.0,...,40.640775,3.0,MPV-5,1,,,41.86475,-71.47439,40.64078,-73.78932
5386,2625748,3449407,1,2024-05-05 11:39:59.000000,1715150700,2024-05-08 02:45,Eastern Daylight Time,None,None,2.0,...,40.641311,3.0,MPV-5,1,,,43.03775,-76.14038,40.64131,-73.77814
5387,1956810,3122049,1,2024-01-09 10:13:21.000000,1704865500,2024-01-10 00:45,Eastern Standard Time,None,None,2.0,...,40.759735,1.0,Sedan,1,,,43.29943,-74.21793,40.75974,-73.98615

In [27]:
# df_start.to_sql('price_training_ny_start', sql_eng, if_exists='replace', index=True)
# df_start.to_csv('../data/price_training_ny_start.csv', index=False)

In [24]:
fp_zone_end_t = select(
    ordered_t.c,
    distinct_end_lp_t.c.start_ltt_lp,
    distinct_end_lp_t.c.start_lng_lp,
    distinct_end_lp_t.c.end_ltt_lp,
    distinct_end_lp_t.c.end_lng_lp
).select_from(ordered_t
              .join(distinct_end_lp_t, 
                    ordered_t.c.dispatch_id == distinct_end_lp_t.c.dispatch_id)
              )
df_end = pd.read_sql(fp_zone_end_t, sql_eng)
df_end

,dispatch_id,ride_id,trip_count,ride_inserted_at,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,passenger_count,...,end_ltt,vehicle_class_id,vehicle_class,row_num,route_start,route_end,start_ltt_lp,start_lng_lp,end_ltt_lp,end_lng_lp
0,1983048,3135744,1,2024-01-13 17:24:06.000000,1708001940,2024-02-15 07:59,America/New_York,None,None,3.0,...,-37.796575,1.0,Sedan,1,,,40.77286,-73.87217,-37.79657,144.97858
1,3269615,3069568,2,2023-12-20 09:14:26.000000,1727796300,2024-10-01 11:25,America/New_York,2024-10-08 16:15,Australian Eastern Daylight Time,2.0,...,-33.874297,1.0,Sedan,1,,,40.64953,-73.78287,-33.87430,151.20545
2,1545419,2769754,2,2023-08-21 19:30:14.000000,1698268800,2023-10-25 17:20,America/New_York,2023-11-01 19:40,Australian Eastern Standard Time,1.0,...,-27.261944,1.0,Sedan,1,,,40.64462,-73.77970,-27.26194,153.10384
3,563645,2420607,2,2022-12-23 01:28:45.000000,1671584400,2022-12-20 20:00,Eastern Standard Time,2023-01-03 13:50,Eastern Standard Time,2.0,...,25.795872,1.0,Sedan,1,,,40.64131,-73.77814,25.79587,-80.28705
4,1253014,2767528,2,2023-08-20 14:47:31.000000,1704324600,2024-01-03 18:30,America/New_York,2024-01-10 22:00,America/New_York,3.0,...,33.889460,1.0,Sedan,1,,,40.64462,-73.77970,33.88946,-118.15979
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7835,325847,2311415,1,2022-06-17 21:26:19.000000,1656250200,2022-06-26 09:30,Eastern Daylight Time,None,None,24.0,...,43.240207,35.0,55-seat Coach Bus,1,,,40.75676,-73.99044,43.24021,-70.60100
7836,874458,2577092,1,2023-05-09 15:38:55.000000,1686490200,2023-06-11 09:30,Eastern Daylight Time,None,None,30.0,...,43.240561,34.0,44-seat Coach Bus,1,,,40.75675,-73.99317,43.24056,-70.60125
7837,604328,2441254,1,2023-01-15 14:18:12.000000,1691528400,2023-08-08 17:00,America/New_York,None,None,2.0,...,43.626569,1.0,Sedan,1,,,40.64132,-73.77824,43.62657,-72.51408
7838,1620238,2926121,1,2023-10-29 04:36:17.000000,1701105480,2023-11-27 12:18,America/New_York,None,None,3.0,...,45.465181,1.0,Sedan,1,,,40.64462,-73.77970,45.46518,9.18946
7839,2204196,2982529,1,2023-11-17 11:07:59.000000,1708738500,2024-02-23 20:35,Eastern Standard Time,None,None,2.0,...,52.243438,1.0,Sedan,1,,,40.64131,-73.77814,52.24344,4.55808

In [28]:
# df_end.to_sql('price_training_ny_end', sql_eng, if_exists='replace', index=True)
# df_end.to_csv('../data/price_training_ny_end.csv', index=False)

In [26]:
import requests

In [29]:
from concurrent.futures import ThreadPoolExecutor, as_completed
import httpx
from http import HTTPStatus
from concurrent import futures
from enum import Enum

In [30]:
# df_start.to_sql('price_training_raw_2024_usd_start_deduplicated', sql_eng, if_exists='replace', index=True)
sql_eng = create_engine('sqlite:///../data/price_ts.db', echo=False)
connection = sql_eng.connect()
metadata = MetaData()
start_table = Table('price_training_ny_start', metadata, autoload_with=sql_eng)
end_table = Table('price_training_ny_end', metadata, autoload_with=sql_eng)
s = select(end_table).limit(10)
# rp =sql_eng.connect().execute(s)
# df = pd.DataFrame(rp)
df = pd.read_sql(s,sql_eng)
df

,index,dispatch_id,ride_id,trip_count,ride_inserted_at,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,...,end_ltt,vehicle_class_id,vehicle_class,row_num,route_start,route_end,start_ltt_lp,start_lng_lp,end_ltt_lp,end_lng_lp
0,0,1983048,3135744,1,2024-01-13 17:24:06.000000,1708001940,2024-02-15 07:59,America/New_York,None,None,...,-37.796575,1.0,Sedan,1,,,40.77286,-73.87217,-37.79657,144.97858
1,1,3269615,3069568,2,2023-12-20 09:14:26.000000,1727796300,2024-10-01 11:25,America/New_York,2024-10-08 16:15,Australian Eastern Daylight Time,...,-33.874297,1.0,Sedan,1,,,40.64953,-73.78287,-33.87430,151.20545
2,2,1545419,2769754,2,2023-08-21 19:30:14.000000,1698268800,2023-10-25 17:20,America/New_York,2023-11-01 19:40,Australian Eastern Standard Time,...,-27.261944,1.0,Sedan,1,,,40.64462,-73.77970,-27.26194,153.10384
3,3,563645,2420607,2,2022-12-23 01:28:45.000000,1671584400,2022-12-20 20:00,Eastern Standard Time,2023-01-03 13:50,Eastern Standard Time,...,25.795872,1.0,Sedan,1,,,40.64131,-73.77814,25.79587,-80.28705
4,4,1253014,2767528,2,2023-08-20 14:47:31.000000,1704324600,2024-01-03 18:30,America/New_York,2024-01-10 22:00,America/New_York,...,33.889460,1.0,Sedan,1,,,40.64462,-73.77970,33.88946,-118.15979
5,5,1250833,2766533,2,2023-08-19 23:50:01.000000,1703283900,2023-12-22 17:25,America/New_York,2023-12-27 19:00,America/New_York,...,35.800203,1.0,Sedan,1,,,40.64462,-73.77970,35.80020,-83.56910
6,6,2643623,3435657,1,2024-04-29 16:04:01.000000,1715393100,2024-05-10 22:05,America/New_York,None,None,...,36.305548,1.0,Sedan,1,,,40.64462,-73.77970,36.30555,-82.37031
7,7,192839,2245802,2,2022-03-02 19:13:47.000000,1648135800,2022-03-24 11:30,America/New_York,2022-03-29 07:15,Mountain Daylight Time,...,37.183040,3.0,MPV-5,1,,,40.77693,-73.87397,37.18304,-113.00295
8,8,718716,2501000,1,2023-03-11 09:54:45.000000,1678631400,2023-03-12 10:30,Eastern Daylight Time,None,None,...,38.750949,1.0,Sedan,1,,,40.78306,-73.97125,38.75095,-77.47527
9,9,97104,2209396,1,2021-11-16 22:32:36.000000,1638529200,2021-12-03 06:00,Eastern Standard Time,None,None,...,38.863419,35.0,55-seat Coach Bus,1,,,40.75267,-73.99356,38.86342,-77.35355

In [31]:

query = [select(start_table), select(end_table)]
result_table = ['label_2324_start', 'label_2324_end']

In [32]:

FZPQueryStatus = Enum('FZPQueryStatus', 'JsonError HTTPXStatusError HTTPXError IndexOrKeyError DictError NoFixedPrice Success')
fzp = {'from': None, 'to': None}
def get_one_fixed_zone(start_ltt, start_lng, end_ltt, end_lng) -> FZPQueryStatus:
    global fzp
    params = {
        'from_lat': start_ltt,
        'from_lng': start_lng,
        'to_lat': end_ltt,
        'to_lng': end_lng,
    }
    try:
        # response = requests.get(url=url, params=params)
        response = httpx.get(url=url, params=params)
    except httpx.HTTPStatusError as exc:
        return FZPQueryStatus.HTTPXStatusError
    except Exception as exc:
        return FZPQueryStatus.HTTPXError

    try:
        res = response.json()
    except Exception as exc:
        return FZPQueryStatus.JsonError
    try:
        fix_price_zones = res['fleets'][0]['vehicle_classes'][0]['price_detail']['base_pricing']['fix_price_detail']
    except Exception as exc:
        return FZPQueryStatus.IndexOrKeyError
    # print('4')
    if not isinstance(fix_price_zones,dict):
        return FZPQueryStatus.DictError
    else:
        try:
            fzp['from'] = fix_price_zones['from']
            fzp['to']   = fix_price_zones['to']
            return FZPQueryStatus.Success
        except KeyError as e:
            return FZPQueryStatus.NoFixedPrice

In [33]:
import requests
url = 'https://j1j495o5pk.execute-api.us-east-2.amazonaws.com/upncoming/ride-pricings'

In [35]:
csv_file_list = ['../data/price_training_ny_start.csv',
             '../data/price_training_ny_end.csv']
csv_result_file_list = ['../data/price_training_ny_start_result.csv',
                 '../data/price_training_ny_end_result.csv']
total_rows = [df_start.shape[0], df_end.shape[0]]
result_csv = '../data/dispatch_fpz_ny_label_list.csv'
total_rows

chunk_size = 1000

[5388, 7840]

In [37]:
non_fzp_count = 0
max_concurrent = 96
for t in [0]: #range(2):
    for i,chunk in enumerate(tqdm(pd.read_sql(query[t],connection,index_col='dispatch_id', chunksize=chunk_size),     total=total_rows[t]//chunk_size+1, desc='Overall Progress')):
        chunk = chunk.astype({'route_start': str, 'route_end': str})
        non_fzp_count_chunk = 0
        # get_fixed_zone_chunk(chunk)
        
        with ThreadPoolExecutor(max_workers=max_concurrent) as executor:
            to_do_map = {} # list[futures.Future] = [] 
            # for ind,r in tqdm(chunk.iterrows(),total=chunk_size,desc='chunk progress', leave=False):
            for ind,r in chunk.iterrows():
                future = executor.submit(get_one_fixed_zone, r['start_ltt_lp'], r['start_lng_lp'], r['end_ltt_lp'],     r['end_lng_lp'])
                to_do_map[future] = ind
            done_iter = as_completed(to_do_map)
            done_iter = tqdm(done_iter, total=len(to_do_map), desc='chunk progress', leave=False)
            
            for future in done_iter:
                try:
                    status = future.result()
                except Exception as e:
                    # print(f"Exception: {e}")
                    continue
                
                if status == FZPQueryStatus.Success:
                    ind = to_do_map[future]
                    try:
                        chunk.at[ind, 'route_start'] = fzp['from']
                        chunk.at[ind, 'route_end'] = fzp['to']
                    except KeyError as e:
                        non_fzp_count_chunk += 1
                        # print(f"\r {e}: {non_fzp_count_chunk}/{chunk_size}")
                        continue
                    except Exception as e:
                        non_fzp_count_chunk += 1
                        # print(f"\r {e}: {non_fzp_count_chunk}/{chunk_size}")
                        continue
                else:
                    non_fzp_count_chunk += 1
                    # print(f"\r non fzp chunk: {non_fzp_count_chunk}/{chunk_size}")
                    continue
            
        non_fzp_count += non_fzp_count_chunk
        scanned_row_number = (i+1)*chunk_size
        try:
            # pd.DataFrame(data=route_list, columns=['dispatch_id', 'route_start', 'route_end']).to_csv(result_csv,     mode='a', header=False)
            with open(csv_result_file_list[t], 'a') as f:
                chunk.to_csv(f, header=f.tell()==0,chunksize=chunk_size)
            # chunk.to_csv(path_or_buf=csv_result_file_list[0],mode='a',chunksize=chunk_size)
            # chunk.to_sql(result_table[0], sql_eng, if_exists='append', index=True)
            print(f"\r Non_FZP count: {non_fzp_count}/{scanned_row_number}")
        except Exception as e:
            print(f"\r {e}, Non_FZP count: {non_fzp_count}/{scanned_row_number} ")
            continue

Overall Progress:   0%|          | 0/6 [00:00<?, ?it/s]

chunk progress:   0%|          | 0/1000 [00:00<?, ?it/s]

 Non_FZP count: 107/1000

chunk progress:   0%|          | 0/1000 [00:00<?, ?it/s]

 Non_FZP count: 161/2000

chunk progress:   0%|          | 0/1000 [00:00<?, ?it/s]

 Non_FZP count: 189/3000

chunk progress:   0%|          | 0/1000 [00:00<?, ?it/s]

 Non_FZP count: 228/4000

chunk progress:   0%|          | 0/1000 [00:00<?, ?it/s]

 Non_FZP count: 280/5000

chunk progress:   0%|          | 0/388 [00:00<?, ?it/s]

 Non_FZP count: 416/6000

In [ ]:
# non_fzp_count = 0
# max_concurrent = 20
# for i,chunk in enumerate(tqdm(pd.read_csv(csv_file_list[0],index_col='dispatch_id', chunksize=chunk_size), total=total_rows[0]//chunk_size+1, desc='Overall Progress')):
#     chunk = chunk.astype({'route_start': str, 'route_end': str})
#     non_fzp_count_chunk = 0
#     # get_fixed_zone_chunk(chunk)
#     
#     with ThreadPoolExecutor(max_workers=max_concurrent) as executor:
#         to_do_map = {} # list[futures.Future] = [] 
#         # for ind,r in tqdm(chunk.iterrows(),total=chunk_size,desc='chunk progress', leave=False):
#         for ind,r in chunk.iterrows():
#             future = executor.submit(get_one_fixed_zone, r['start_ltt_lp'], r['start_lng_lp'], r['end_ltt_lp'], r['end_lng_lp'])
#             to_do_map[future] = ind
#         done_iter = as_completed(to_do_map)
#         done_iter = tqdm(done_iter, total=len(to_do_map), desc='chunk progress', leave=False)
#         
#         for future in done_iter:
#             try:
#                 status = future.result()
#             except Exception as e:
#                 # print(f"Exception: {e}")
#                 continue
#             
#             if status == FZPQueryStatus.Success:
#                 ind = to_do_map[future]
#                 try:
#                     chunk.at[ind, 'route_start'] = fzp['from']
#                     chunk.at[ind, 'route_end'] = fzp['to']
#                 except KeyError as e:
#                     non_fzp_count_chunk += 1
#                     # print(f"\r {e}: {non_fzp_count_chunk}/{chunk_size}")
#                     continue
#                 except Exception as e:
#                     non_fzp_count_chunk += 1
#                     # print(f"\r {e}: {non_fzp_count_chunk}/{chunk_size}")
#                     continue
#             else:
#                 non_fzp_count_chunk += 1
#                 # print(f"\r non fzp chunk: {non_fzp_count_chunk}/{chunk_size}")
#                 continue
#         
#     non_fzp_count += non_fzp_count_chunk
#     scanned_row_number = (i+1)*chunk_size
#     try:
#         # pd.DataFrame(data=route_list, columns=['dispatch_id', 'rou:w
#         # te_start', 'route_end']).to_csv(result_csv, mode='a', header=False)
#         with open(csv_result_file_list[0], 'a') as f:
#             chunk.to_csv(f, header=f.tell()==0,chunksize=chunk_size)
#         # chunk.to_csv(path_or_buf=csv_result_file_list[0],mode='a',chunksize=chunk_size)
#         print(f"\r Non_FZP count: {non_fzp_count}/{scanned_row_number}")
#     except Exception as e:
#         print(f"\r {e}, Non_FZP count: {non_fzp_count}/{scanned_row_number} ")
#         continue

In [45]:
import requests
url = 'https://j1j495o5pk.execute-api.us-east-2.amazonaws.com/upncoming/ride-pricings'
def get_one_fixed_zone1(start_ltt, start_lng, end_ltt, end_lng):
    params = {
        'from_lat': start_ltt,
        'from_lng': start_lng,
        'to_lat': end_ltt,
        'to_lng': end_lng,
    }
    try:
        response = requests.get(url=url, params=params)
    except requests.exceptions.Timeout:
        print('Timeout')
        return None
    except requests.exceptions.TooManyRedirects:
        print('TooManyRedirects')
        return None
        # Tell the user their URL was bad and try a different one
    except requests.exceptions.RequestException as e:
        print('RequestException, Catastrophic error!')
        return None

    except Exception as e:
        print(f"request: {e}")
        return None
    # print('2')
    try:
        res = response.json()
    except Exception as e:
        print(f"json: {e}")
        return None
    # print('3')
    try:
        fix_price_zones = res['fleets'][0]['vehicle_classes'][0]['price_detail']['base_pricing']['fix_price_detail']
    except KeyError as e:
        # print(f"No Fixed Price!")
        return None
    except IndexError as e:
        # print("IndexError for fix_price_zones")
        return None
    except Exception as e:
        # print(f"dict: {e}")
        return None
    # print('4')
    if not isinstance(fix_price_zones,dict):
        # print(f"No fix price: {fix_price_zones}")
        return None
    else:
        try:
            return {'from': fix_price_zones['from'], 'to': fix_price_zones['to']}
        except KeyError as e:
            # print("KeyError for route")
            return None

non_fzp_count = 0
for i,chunk in enumerate(tqdm(pd.read_csv(csv_file_list[0],index_col='dispatch_id', chunksize=chunk_size), total=total_rows[0]//chunk_size+1, desc='Overall Progress')):
    chunk = chunk.astype({'route_start': str, 'route_end': str})
    non_fzp_count_chunk = 0
    # get_fixed_zone_chunk(chunk)
    for ind,r in tqdm(chunk.iterrows(),total=chunk_size,desc='chunk progress', leave=False):
        fpz = get_one_fixed_zone1(r['start_ltt_lp'], r['start_lng_lp'], r['end_ltt_lp'], r['end_lng_lp'])
        if fpz is None:
            non_fzp_count_chunk += 1
            # print(f"\r non fzp chunk: {non_fzp_count_chunk}/{chunk_size}")
            continue
        try:
            chunk.at[ind, 'route_start'] = fpz['from']
            chunk.at[ind, 'route_end'] = fpz['to']
        except KeyError as e:
            non_fzp_count_chunk += 1
            # print(f"\r {e}: {non_fzp_count_chunk}/{chunk_size}")
            continue
        except Exception as e:
            non_fzp_count_chunk += 1
            # print(f"\r {e}: {non_fzp_count_chunk}/{chunk_size}")
            continue

    non_fzp_count += non_fzp_count_chunk
    scanned_row_number = (i+1)*chunk_size
    try:
        # pd.DataFrame(data=route_list, columns=['dispatch_id', 'rou:w
        # te_start', 'route_end']).to_csv(result_csv, mode='a', header=False)
        with open(csv_result_file_list[0], 'a') as f:
            chunk.to_csv(f, header=f.tell()==0,chunksize=chunk_size)
        # chunk.to_csv(path_or_buf=csv_result_file_list[0],mode='a',chunksize=chunk_size)
        print(f"\r Non_FZP count: {non_fzp_count}/{scanned_row_number}")
    except Exception as e:
        print(f"\r {e}, Non_FZP count: {non_fzp_count}/{scanned_row_number} ")
        continue

Overall Progress:   0%|          | 0/118 [00:00<?, ?it/s]

chunk progress:   0%|          | 0/1000 [00:00<?, ?it/s]

KeyboardInterrupt:

In [ ]:
df.loc[:,'route_start'] = 'Zone 0'
df.loc[:,'route_end'] = 'Zone 1'
df

In [ ]:
# for chunk in tqdm(pd.read_csv(csv_file_list[0],index_col='dispatch_id', chunksize=chunk_size), total=total_rows[0]//chunk_size+1, desc='Overall Progress'):
# # for chunk in pd.read_csv(csv_file_list[0],index_col='dispatch_id', chunksize=chunk_size):
#     # [chunk[r] for r in chunk]
#     # l = [r for r in chunk.iterrows()]
#     # l
#     # print(chunk.dtypes)
#     # route_list = []
#     chunk = chunk.astype({'route_start': str, 'route_end': str})
#     for i,r in tqdm(chunk.iterrows(),total=chunk_size,desc='chunk progress', leave=False):
#     # for i,r in chunk.iterrows():
#         # l = [i, r['start_ltt'], r['start_lng'], r['end_ltt'], r['end_lng']]
#         # print(l)
#         params = {
#             'from_lat': r['start_ltt_lp'],
#             'from_lng': r['start_lng_lp'],
#             'to_lat': r['end_ltt_lp'],
#             'to_lng': r['end_lng_lp'],
#         }
#         try:
#             response = requests.get(url=url, params=params)
#         except requests.exceptions.Timeout:
#             print('Timeout')
#             continue
#         except requests.exceptions.TooManyRedirects:
#             print('TooManyRedirects')
#             continue
#             # Tell the user their URL was bad and try a different one
#         except requests.exceptions.RequestException as e:
#             print('RequestException, Catastrophic error!')
#             continue
#             # catastrophic error. bail.
#             # raise SystemExit(e)
# 
#         except Exception as e:
#             print(f"request: {e}")
#             continue
#         # print('2')
#         try:
#             res = response.json()
#         except Exception as e:
#             print(f"json: {e}")
#             continue
#         # print('3')
#         try:
#             fix_price_zones = res['fleets'][0]['vehicle_classes'][0]['price_detail']['base_pricing']['fix_price_detail']
#         except KeyError as e:
#             print(f"No Fixed Price!")
#             continue
#         except IndexError as e:
#             print("IndexError for fix_price_zones")
#             continue
#         except Exception as e:
#             print(f"dict: {e}")
#             continue
#         # print('4')
#         if not isinstance(fix_price_zones,dict):
#             print(f"No fix price: {fix_price_zones}")
#         else:
#             try:
#                 # route_list.append((i, fix_price_zones['from'], fix_price_zones['to']))
#                 # fix_zone_routes_list.append(route)
#                 chunk.at[i, 'route_start'] = fix_price_zones['from']
#                 chunk.at[i, 'route_end'] = fix_price_zones['to']
#                 # ins = insert(fixed_zone_routes).values(
#                 #     start=fix_price_zones['from'], end=fix_price_zones['from'], dispatch_id= pt        ._mapping['dispatch_id'])
#                 # stmt = (
#                 #     update(raw)  # 'raw' is your table object
#                 #     .where(raw.c.dispatch_id == int(i))
#                 #     .values(
#                 #         route_start = fix_price_zones['from'],
#                 #         route_end = fix_price_zones['to']
#                 #     )
#                 # )
#                 # conn.execute(stmt)
#                 # conn.commit()
#             except KeyError as e:
#                 print("KeyError for route")
#                 continue
#     
#     try:
#         # pd.DataFrame(data=route_list, columns=['dispatch_id', 'route_start', 'route_end']).to_csv(result_csv, mode='a', header=False)
#         chunk.to_csv(path_or_buf=csv_result_file_list[0],mode='a',chunksize=chunk_size)
#     except Exception as e:
#         print(f"csv: {e}")
#         continue
#     
#     # with sqlite_eng.begin() as conn:
#     #     conn.execute(
#     #         stmt, 
#     #         [
#     #             {
#     #                 'b_dispatch_id': i,
#     #                 'route_start': r['route_start'],
#     #                 'route_end': r['route_end']
#     #             }
#     #             for i,r in chunk.iterrows()
#     #         ],
#     #     )
#     #     conn.commit()
#

# Query FP-Server and add label to database

In [ ]:
# new_columns = [Column(col.name, col.type, primary_key=col.primary_key) for col in my_table.columns]
# new_table = Table('price_training_raw_2024_usd_reordered', metadata, *new_columns)
# new_table.create(sql_eng)
new_table = Table('price_training_raw_2024_usd_reordered', metadata, autoload_with=sql_eng)

In [ ]:
Session = sessionmaker(bind=sql_eng)
session = Session()

## insert data into new table: fp_zone_start_t & fp_zone_end_t

In [ ]:
chunk_size = 1000
total_rows = len(ordered_rows)
total_rows
total = total_rows//chunk_size+1
total

In [ ]:
for chunk in tqdm(range(total), total=total, desc='Overall Processing'):
    start = chunk*chunk_size
    end = (chunk+1)*chunk_size
    if end > total_rows:
        end = total_rows
    chunk_data = ordered_rows[start:end]
    batch = [dict(zip(cols,row)) for row in chunk_data]
    result = session.execute(insert(new_table).values(batch))
    session.commit()
    # for row in tqdm(chunk_data, total=len(chunk_data), desc='Chunk Processing'):
    #     session.execute(new_table.insert().values(row))
session.close()

In [ ]:
df = pd.DataFrame(data=ordered_rows)

In [ ]:
df = pd.read_sql(fp_zone_t, sql_eng)
df

In [ ]:
# distinct_t = select(distinct(lp_ltt_lng_t.c.start_lng_lp))
# distinct_t = distinct_t.limit(1000)#.distinct(lp_ltt_lng_t.c.start_ltt)
# df = pd.read_sql(distinct_t, sql_eng)
# df

## Create new table with ordered data

In [ ]:
ordered_t = select(my_table).where(
    and_(
        my_table.c.start_ltt.isnot(None),
        my_table.c.start_lng.isnot(None),
    )
).order_by(asc(my_table.c.start_ltt), asc(my_table.c.start_ltt))
ordered_t = ordered_t.select_from(my_table)

In [ ]:
with sql_eng.connect() as connection:
    result = connection.execute(ordered_t)
    ordered_rows = result.fetchall()
# ordered_rows[:3]

In [ ]:
data = ordered_rows[:10]
cols = [c.name for c in ordered_t.subquery().columns]
df = pd.DataFrame(data=data, columns=cols)
df

In [ ]:

batch = [dict(zip(cols, row)) for row in data]
batch[:2]

In [ ]:
for row in tqdm(result, total=unique_count):
    for chunk in tqdm(pd.read_sql(query.statement, conn, index_col='dispatch_id', chunksize=chunk_size), total=total_rows//chunk_size+1, desc='Overall Processing'):
    route_list = []

In [ ]:
with sql_eng.connect() as conn:
    result = conn.execute(ordered_t)
    for row in tqdm(result, total=unique_count):
        session.execute(new_table.insert().values(row))
    session.commit()

In [ ]:
# list(my_table.columns)

In [ ]:
# metadata_new = MetaData()
# my_table.to_metadata(metadata_new)
# metadata_new.tables

In [ ]:
new_table = Table('price_training_raw_2024_usd_geo_ordered', metadata, *my_table.columns)
# list(new_table.columns)
# new_table.name = 'price_training_raw_2024_usd_geo_ordered'
# metadata_new.create_all(sql_eng)

# reduce precision of start_ltt, start_lng, end_ltt, end_lng by 3 digits

In [ ]:
df.loc[:,'route_start'] = 'start'
df

In [ ]:

stmt = (
    update(my_table)  # 'raw' is your table object
    .where(my_table.c.dispatch_id == 822019)
    .values(
        route_start='New Zone C',
        route_end='New Zone D'
    )
)
print(stmt)

In [ ]:
compiled = stmt.compile()
compiled.params

In [ ]:
with sql_eng.connect() as conn:
    result = conn.execute(stmt)
    conn.commit()

In [ ]:
s = select(my_table).where(my_table.c.dispatch_id == 822019)
rp = sql_eng.connect().execute(s)
results = rp.fetchall()
results

In [ ]:
df

In [ ]:
for i,r in df.iterrows():
    l = [i, r['ride_id'], r['dispatch_amount'],r['fleet']]
    # print(r)
    df.at[i,'route_end'] = 'Shanghai'
    stmt = (
        update(my_table)
        .where(my_table.c.dispatch_id == int(i))
        .values(
            route_start='Beijing',
            route_end='Shanghai',
        )
    )
    with sql_eng.connect() as conn:
        conn.execute(stmt)
        conn.commit()
    # print('----')
    print(l)
df

# Update data batchwise in sqlite db

In [ ]:
stmt = (
    update(my_table)  # 'raw' is your table object
    .where(my_table.c.dispatch_id == bindparam('b_dispatch_id'))
    .values(
        route_start=bindparam('route_start'),
        route_end=bindparam('route_end')
    )
)
print(stmt)

In [ ]:
l = [ 
            {'dispatch_id': i,
             'route_start': r['route_start'],
             'route_end': r['route_end']} 
            for i,r in df.iterrows()
        ]
l

In [ ]:

with sql_eng.begin() as conn:
    conn.execute(
        stmt,
        [ 
            {'b_dispatch_id': i,
             'route_start': r['route_start'],
             'route_end': r['route_end']} 
            for i,r in df.iterrows()
        ],
    )
    conn.commit()

In [ ]:
s = select(my_table).limit(20)
rp = sql_eng.connect().execute(s)
results = rp.fetchall()
df = pd.DataFrame(results)
df

In [ ]:
for i,r in df.iterrows():
    print(i, r['ride_id'], r['dispatch_amount'],r['fleet'])

In [ ]:

# df.to_sql('price_training_raw_2024_usd', sqlite_eng, if_exists= 'replace',index=True, index_label='dispatch_id')

In [ ]:
for r in df.itertuples():
    # print(r)
    print(r.ride_id, r.fleet)
    df.at[r.Index, 'route_start'] = 'PVG'
    # r.route_start = 'start'
    # r.route_end = 'end'
df

In [ ]:

# df.to_sql('price_training_raw_2024_usd', sqlite_eng, if_exists= 'replace',index=True, index_label='dispatch_id')

In [ ]:
#| hide
import nbdev; nbdev.nbdev_export()