# core data utilities

> core utilities for data processing: 
> datetime processing, time zone processing, validity, filtering

In [ ]:
#| default_exp data.utils

In [ ]:
#| hide
from nbdev.showdoc import *

In [9]:
#| hide
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [12]:
#| export
from datetime import datetime
import pandas as pd
import pytz

In [ ]:
#| export
pd.options.mode.chained_assignment = None

In [ ]:
#| export
def validate_datetime(date_string, format_string):
    """
    Validates if a string is a valid datetime according to the given format.
    """

    try:
        datetime.strptime(date_string, format_string)
        return True
    except ValueError:
        return False
    
def validate_datetime_in_iso_format(date_text):
        try:
            datetime.fromisoformat(date_text)
            return True
        except ValueError:
            # raise ValueError("Incorrect data format, should be YYYY-MM-DD")
            return False

In [ ]:
# Example usage
date_strings = [
    "2023-12-25 24:00:00",
    "2023-12-25 12:60:00.12",
    "2023-12-25 12:10:00",
    "2023-12-25 23:00:00",
    "2011-11-04",
    "20111104",
    "2011-11-04T00:05:23",
    "2011-11-04T00:05:23.283185",
    "20111104T000523",
    "20111104T000523.283185",
    "2011-11-04T00:05:23Z",
    "2011-11-04T00:05:23.283185+08:00",
    "2011-11-04T00:05:23+08:00",
    ]
format_string = "%Y-%m-%d"

for s in date_strings:
    if validate_datetime_in_iso_format(s):
        print(f"{s} is Valid datetime string")
    else:
        print(f"{s} is Invalid datetime string")

In [ ]:
df_datetime_str = pd.DataFrame(date_strings)
df_datetime_str.columns = ['datetime']
# df_datetime_str
df_datetime_str['validity'] = df_datetime_str.apply(lambda x: validate_datetime_in_iso_format(x.iloc[0]), axis=1)
df_datetime_str

In [ ]:
df_datetime = df_datetime_str[df_datetime_str.apply(lambda x: validate_datetime_in_iso_format(x.iloc[0]), axis=1)]
df_datetime

In [ ]:
df_datetime_invalid = df_datetime_str[df_datetime_str.apply(lambda x: not validate_datetime_in_iso_format(x.iloc[0]), axis=1)]
df_datetime_invalid

In [ ]:
df_datetime['datetime']

In [ ]:
# df_datetime_str.apply(lambda x: validate_datetime_in_iso_format(x.iloc[0]), axis=1)
df_datetime1 = df_datetime.apply(lambda x: datetime.fromisoformat(x['datetime']), axis=1)
df_datetime1.name = 'datetime'
df_datetime1

In [ ]:
df_datetime1.loc[0:8]

In [ ]:
df_no_tz = pd.to_datetime(df_datetime1.loc[0:8])
df_no_tz

In [ ]:
#| export
def get_timezone_abbreviation(timezone_name):
    timezone = pytz.timezone(timezone_name)
    now = datetime.now(timezone)
    return now.strftime("%Z")

def validate_timezone_in_iana(timezone_name):
    return timezone_name in pytz.all_timezones

In [ ]:

time_zone_strings = [
    'Eastern Standard Time',
    'Eastern Daylight Time',
    'US/Eastern',
    'US/Daylight',
    'Asia/Shanghai',
    'Asia/Mumbai',
    'America/New_York',
    'Europe/London',
    'America/Los_Angeles',
    'Asia/Kolkata',
    'Europe/London',
    'Asia/Hong_Kong',
    'Asia/Tokyo',
]
df_timezone_str = pd.DataFrame(time_zone_strings)
df_timezone_str.columns = ['timezone']

# df_datetime_str
df_timezone_str['validity'] = df_timezone_str.apply(lambda x: validate_timezone_in_iana(x['timezone']), axis=1)
df_timezone_str

In [ ]:
#| export
timezone_fixing_map = {'Eastern Standard Time': 'US/Eastern',
                       'Eastern Daylight Time': 'US/Eastern',
                       'US/Daylight': 'US/Eastern',
                       'Asia/Mumbai': 'Asia/Calcutta',}

In [ ]:
#| export
def fix_timezone(timezone_name):
    return timezone_fixing_map.get(timezone_name, timezone_name)

In [ ]:
for tz in time_zone_strings:
    print(f"{tz} -> {fix_timezone(tz)} -> {get_timezone_abbreviation(fix_timezone(tz))}")

In [ ]:

df_timezone_unidentified = df_timezone_str[df_timezone_str.apply(lambda x: not validate_timezone_in_iana(x['timezone']), axis=1)]
df_timezone_unidentified

In [ ]:

df_timezone_unidentified.apply(lambda x: fix_timezone(x['timezone']), axis=1)

In [ ]:
df_timezone_str['timezone_fixed'] = df_timezone_str.apply(lambda x: fix_timezone(x['timezone']), axis=1)
df_timezone_str

In [ ]:

df_timezone = df_timezone_str[df_timezone_str.apply(lambda x: validate_timezone_in_iana(x['timezone_fixed']), axis=1)]
df_timezone

In [ ]:
# extract invalid data
df_timezone_invalid = df_timezone_str[df_timezone_str.apply(lambda x: not validate_timezone_in_iana(x.iloc[0]), axis=1)]
df_timezone_invalid

In [ ]:
df_abbr = df_timezone.apply(lambda x: get_timezone_abbreviation(x.loc['timezone_fixed']), axis=1)
df_abbr.name = 'abbr'
df_abbr

In [ ]:
df_timezone

In [ ]:
# df_timezone_str['validity'] = df_timezone_str.apply(lambda x: validate_timezone_in_iana(x.iloc[0]), axis=1)
# df_timezone['abbr'] = df_timezone.apply(lambda x: get_timezone_abbreviation(x.iloc[0]), axis=1)
# df_timezone.apply(lambda x: get_timezone_abbreviation(x.iloc[0]), axis=1)
df_timezone.loc[:,'abbr'] = df_abbr
df_timezone
# df_timezone

In [ ]:

df_utc_offset = (df_timezone.apply(lambda x: datetime.now(pytz.timezone(x.loc['timezone_fixed'])), axis=1)
                            .apply(lambda x: x.strftime('%z')))
df_utc_offset.name = 'utc_offset'
df_utc_offset

In [ ]:

df_timezone.loc[:,'utc_offset'] = df_utc_offset
df_timezone

In [ ]:
for tz in df_timezone.loc[:,'timezone_fixed']:
    print(f"{tz}: {datetime.now(pytz.timezone(tz))} - {datetime.now(pytz.timezone(tz)).strftime('%Z')}, {datetime.now(pytz.timezone(tz)).strftime('%z')}")

In [ ]:
for dt,tz in zip(df_no_tz, df_timezone.loc[:,'timezone_fixed']):
    print(f"{dt}: {dt.tz_localize(tz)}, as {dt.tz_localize(tz).astimezone('utc')}")

In [ ]:
from zoneinfo import ZoneInfo

In [ ]:
for dt,tz in zip(df_no_tz, df_timezone.loc[:,'timezone_fixed']):
    tz_zone = pytz.timezone(tz)
    print(f"{dt}: {tz_zone.localize(dt)}, or {dt.replace(tzinfo=tz_zone)}, or {dt.tz_localize(tz)}, as {dt.tz_localize(tz).astimezone('utc')}")

# Convert csv to sqlite db

In [1]:
from sqlalchemy import create_engine
import pandas as pd
import numpy as np
from tqdm import tqdm

In [2]:
sql_eng = create_engine('sqlite:///../data/price_training_raw.db', echo=False)

In [5]:
# csv_file_path = '../data/bq-results-20240920-103832-1726828742594.csv'
csv_file_path = '../data/price_training_newyork.csv'
chunk_size = 10000
total_lines = sum(1 for line in open(csv_file_path))
print(total_lines)

321364

In [6]:
sample = pd.read_csv(csv_file_path, index_col='dispatch_id', nrows=5)
# sample = pd.read_csv(csv_file_path, nrows=5)
sample

,ride_id,trip_count,ride_inserted_at,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,passenger_count,luggage_count,...,start_place,start_lng,start_ltt,end_place_id,end_place,end_lng,end_ltt,vehicle_class_id,vehicle_class,row_num
dispatch_id,,,,,,,,,,,,,,,,,,,,,
155,2164872,1,2020-05-25 06:45:14.000000,1590431400,2020-05-25 14:30,Eastern Daylight Time,NaN,NaN,1,1,...,400 W 119th St,-73.958410,40.808108,9,John F. Kennedy International Airport,-73.778139,40.641311,1,Sedan,1
8144,2168707,1,2021-02-22 12:46:16.000000,1614125700,2021-02-23 19:15,America/New_York,NaN,NaN,2,2,...,11430,-73.788969,40.643351,3379,7 W 45th St,-73.980025,40.755955,1,Sedan,1
8300,2168774,1,2021-02-26 23:20:34.000000,1614474900,2021-02-27 20:15,Eastern Standard Time,NaN,NaN,2,2,...,John F. Kennedy International Airport,-73.778139,40.641311,3440,98 Frelinghuysen Ave,-74.185363,40.718531,1,Sedan,1
11335,2170440,1,2021-04-09 12:39:59.000000,1619530620,2021-04-27 09:37,America/New_York,NaN,NaN,1,1,...,27 Orchard Ave,-74.023196,40.979118,9,John F. Kennedy International Airport,-73.778139,40.641311,1,Sedan,1
11477,2170519,1,2021-04-10 18:54:08.000000,1628247600,2021-08-06 07:00,America/New_York,NaN,NaN,4,4,...,1535 Broadway,-73.985820,40.758586,11,New York LaGuardia Airport,-73.873966,40.776927,6,MPV-4,1

In [ ]:
# data = np.zeros((2,), dtype=[("A", "i4"), ("B", "f4"), ("C", "U")])
# data

# data = np.empty((2,), dtype=[('start','U'), ('end','U')])
# data

# df = pd.DataFrame(data)
# df

In [ ]:
# it = pd.read_csv(csv_file_path, index_col='dispatch_id', chunksize=chunk_size)
# d = it.get_chunk()
# d
# df = pd.DataFrame(it.get_chunk())
# df

In [ ]:
# with sql_eng.connect() as connection:
#     result = connection.execute(query)
#     unique_count = result.scalar()
    
# print(unique_count)

In [7]:
for chunk in tqdm(pd.read_csv(csv_file_path, index_col='dispatch_id', chunksize=chunk_size), total=total_lines//chunk_size +1):
# for chunk in tqdm(pd.read_csv(csv_file_path, chunksize=chunk_size), total=total_lines//chunk_size +1):
    data = np.empty((chunk.shape[0],), dtype=[('route_start','U'), ('route_end','U')])
    df_append = pd.DataFrame(index=chunk.index, data=data)
    chunk = pd.concat([chunk, df_append], axis = 1)
    chunk.convert_dtypes()
    chunk = chunk[~(chunk['fleet'].str.contains('test', case=False, na=True))]
    chunk = chunk.dropna(subset=['start_lng', 'start_ltt', 'end_lng', 'end_ltt'], how='any')
    # chunk.astype({ 
    #     'ride_id': 'int64',
    #     'trip_count': 'int8',
    #     'from_utc': 'float64',
    #     'from_time_str': 'string',
    #     'from_timezone_str': 'string',
    #     'to_time_str': 'string',
    #     'to_timezone_str': 'string',
    #     'passenger_count': 'int8',
    #     'luggage_count': 'int8',
    #     'children_count': 'int8',
    #     'infant_count': 'int8',
    #     'distance': 'float64',
    #     'duration': 'float64',
    #     'trip_no': 'int8',
    #     'dispatch_amount': 'float64',
    #     'dispatch_currency': 'string',
    #     'from_date_str': 'string',
    #     'from_time_fix_str': 'string',
    #     'from_datetime_fix_str': 'string',
    #     'trip_type_id': 'int64',
    #     'trip_type': 'string',
    #     'ride_status_id': 'int64',
    #     'ride_status': 'string',
    #     'dispatch_status_id': 'int64',
    #     'distpatch_status': 'string',
    #     'dispatch_type': 'string',
    #     'fleet': 'string',
    #     'partner_id': 'int64',
    #     'start_place_id': 'int64',
    #     'start_place': 'string',
    #     'start_lng': 'float64',
    #     'start_ltt': 'float64',
    #     'end_place_id': 'int64',
    #     'end_place': 'string',
    #     'end_lng': 'float64',
    #     'end_ltt': 'float64',
    #     'vehicle_class_id': 'int64',
    #     'vehicle_class': 'string',
    #     'row_num': 'int64',
    #     'route_start': 'string', 
    #     'route_end': 'string',
    #     })
    chunk.to_sql('price_training_newyork', sql_eng, if_exists= 'append',index=True)

100%|██████████| 33/33 [00:09<00:00,  3.32it/s]

In [7]:

from sqlalchemy import MetaData, create_engine, asc, desc, and_, or_, not_, case, extract, cast, Numeric, text, distinct, Column, update, bindparam, Engine
from sqlalchemy.types import DateTime, Date, Time, String
from sqlalchemy.schema import *
from sqlalchemy.sql import func as F, Selectable, select, union, insert
from sqlalchemy.dialects import registry
from sqlalchemy.engine.row import Row
from sqlalchemy.orm import Session
from sqlalchemy.orm import sessionmaker
import requests
from tqdm.notebook import tqdm
import pandas as pd
import numpy as np
from tqdm import tqdm
from datetime import datetime

sql_eng2 = create_engine('sqlite:///../data/price_2324.db', echo=False)
sql_conn2 = sql_eng2.connect()
sql_metadata2 = MetaData()
Sql_Session2 = sessionmaker(bind=sql_eng2)
sql_session2 = Sql_Session2()

In [5]:

dispatch_routes_t = Table('dispatch_feature_routes_2324_sa_fix', sql_metadata2, autoload_with=sql_eng2)
total_rows = sql_session2.query(dispatch_routes_t).count()
print(total_rows)

df_dispatch_routes = pd.read_sql(select(dispatch_routes_t), sql_conn2, index_col='dispatch_id')  #sqlite3
df_dispatch_routes

1061218

,index,from_datetime_fix_str,from_timezone_str,ride_inserted_at,dispatch_inserted_at,start_ltt_lp,start_lng_lp,end_ltt_lp,end_lng_lp,ride_id,...,passenger_count,luggage_count,children_count,infant_count,distance,duration,route_start,route_end,service_area_fix,holidays
dispatch_id,,,,,,,,,,,,,,,,,,,,,
1845170,0,2023-12-28 13:30:00,America/Argentina/Ushuaia,2023-12-18 16:52:11.000000,2023-12-18 16:52:11.000000,-54.8433,-68.2958,-54.80739,-68.30829,3064977,...,2.0,3.0,NaN,NaN,5989.0,751.0,USH,Ushuaia,"Ushuaia,Argentina",19
1717512,1,2024-03-02 11:25:00,America/Argentina/Ushuaia,2023-11-25 01:17:33.000000,2023-11-25 01:17:33.000000,-54.8433,-68.2958,-54.80724,-68.30465,3002859,...,2.0,3.0,NaN,NaN,6302.0,747.0,USH,Ushuaia,"Ushuaia,Argentina",19
2882892,2,2024-08-01 12:00:00,America/Argentina/Ushuaia,2024-03-30 12:35:43.000000,2024-07-01 15:00:22.000000,-54.8433,-68.2958,-54.80733,-68.30539,3363605,...,3.0,3.0,NaN,NaN,6350.0,772.0,USH,Ushuaia,"Ushuaia,Argentina",19
2029084,3,2024-07-24 21:25:00,America/Argentina/Ushuaia,2024-01-22 00:00:29.000000,2024-01-22 00:00:29.000000,-54.8433,-68.2958,-54.80501,-68.30144,3159454,...,2.0,3.0,NaN,NaN,6540.0,841.0,USH,Ushuaia,"Ushuaia,Argentina",19
2484384,4,2024-05-12 10:40:00,Argentina Standard Time,2023-12-05 17:30:18.000000,2024-04-08 16:00:12.000000,-54.8433,-68.2958,-54.80932,-68.31662,3031625,...,2.0,3.0,0.0,0.0,5414.0,666.0,USH,Ushuaia,"Ushuaia,Argentina",19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1520967,1061288,2023-10-19 22:55:00,Europe/Oslo,2023-10-01 21:31:32.000000,2023-10-18 08:34:14.000000,69.6833,18.9189,69.64816,18.95722,2860188,...,1.0,3.0,NaN,NaN,4968.0,552.0,IVL,Nellim,"Tromso, Norway",12
1234482,1061289,2023-11-13 18:40:00,Europe/Oslo,2023-08-15 20:58:24.000000,2023-08-15 20:58:24.000000,69.6833,18.9189,69.64894,18.95969,2759268,...,2.0,4.0,NaN,NaN,5157.0,660.0,TOS,Tromso,"Tromso, Norway",12
1757195,1061290,2024-02-22 13:30:00,Europe/Oslo,2023-12-02 15:05:37.000000,2023-12-02 15:05:37.000000,69.6833,18.9189,69.64803,18.95366,3023087,...,2.0,3.0,NaN,NaN,4792.0,490.0,TOS,Tromso,"Tromso, Norway",12
1441643,1061291,2023-10-19 22:55:00,Europe/Oslo,2023-10-01 21:31:32.000000,2023-10-01 21:31:32.000000,69.6833,18.9189,69.64816,18.95722,2860188,...,1.0,3.0,NaN,NaN,4968.0,552.0,IVL,Nellim,"Tromso, Norway",12
2033738,1061292,2024-02-19 15:00:00,Europe/Oslo,2024-01-22 17:33:27.000000,2024-01-22 17:33:27.000000,69.6833,18.9189,69.64842,18.95355,3161856,...,2.0,3.0,NaN,NaN,4695.0,501.0,TOS,Tromso,"Tromso, Norway",12

In [8]:
csv_file_path = "../data/invalid_from_timestamp_fix_2324.csv"
def check_invalid_timestamp(x):
    try:
        datetime.fromisoformat(x)
        return False
    except ValueError:
        return True

chunk_size = 10000    
for chunk in tqdm(pd.read_sql(select(dispatch_routes_t), con=sql_conn2, index_col='dispatch_id', chunksize=chunk_size), total=total_rows//chunk_size +1):
    df_invalid = chunk[chunk['from_datetime_fix_str'].apply(check_invalid_timestamp)]
    with open(csv_file_path, 'a') as f:
        df_invalid.to_csv(f, header=f.tell()==0,chunksize=chunk_size)

100%|██████████| 107/107 [00:08<00:00, 11.93it/s]


# EDA of raw data

In [9]:
from tqdm.notebook import tqdm
from sqlalchemy import create_engine, select, func, distinct, MetaData, Table, update, bindparam, Column, insert, desc, asc, and_, or_, not_, Numeric, cast

In [14]:
sql_eng = create_engine('sqlite:///../data/price_training_raw.db', echo=False)
sql_conn = sql_eng.connect()
metadata = MetaData()
raw_t = Table('price_training_2324_clean', metadata, autoload_with=sql_eng)
newyork_t = Table('price_training_newyork', metadata, autoload_with=sql_eng)
tokyo_t = Table('price_training_tokyo', metadata, autoload_with=sql_eng)

In [20]:
query = select(func.count(distinct(raw_t.c.dispatch_id)))
with sql_eng.connect() as connection:
    result = connection.execute(query)
    total_rows = result.scalar()
print(total_rows)

2237349

In [23]:
service_area_q = select(raw_t.c.dispatch_id, raw_t.c.service_area_id,raw_t.c.service_area, func.COUNT(raw_t.c.dispatch_id).label('count')).group_by(raw_t.c.service_area_id).order_by(desc('count'))
df = pd.read_sql(service_area_q, sql_eng)
df
# service_area_q = service_area_q.group_by(raw_t.c.service_area_id).distinct(raw_t.c.service_area)

# max_concurrent = 24
# for i,chunk in enumerate(tqdm(pd.read_sql(query,connection,index_col='dispatch_id', chunksize=chunk_size),     total=total_rows//chunk_size+1, desc='Overall Progress')):
#     chunk = chunk.groupby('service_area_id').

      dispatch_id  service_area_id                 service_area   count
0         2317332               40                 New York,USA  223952
1         1403354               41             Bangkok,Thailand  115193
2         2096059              133              Istanbul,Turkey  106455
3         2413801               62                Las Vegas,USA   92773
4         2372356               45              Phuket,Thailand   69734
...           ...              ...                          ...     ...
1098      1425201             1038            Altenburg, German       1
1099       528157             1033         Banda Aceh Indonesia       1
1100      2520122             1023          Palembang,Indonesia       1
1101       194726              855  Cayman Brac  Cayman Islands       1
1102      2023724              823           Lake simcoe,Canada       1

[1103 rows x 4 columns]

In [24]:
partner_q = select(raw_t.c.dispatch_id, raw_t.c.partner,raw_t.c.partner_id, func.COUNT(raw_t.c.dispatch_id).label('count')).group_by(raw_t.c.partner_id).order_by(desc('count'))
df = pd.read_sql(partner_q, sql_eng)
df

     dispatch_id                      partner  partner_id    count
0        1234501                      Booking           2  1274373
1         810009                        Mozio           3   296900
2        1595931             CityAirportTaxis           5   111062
3        1961714                      Expedia           1    71562
4        1092392                    Book Taxi          20    63504
..           ...                          ...         ...      ...
96        563921             Airport Shuttles          26        2
97       1002788  Booking-Motor__Protrave-SRL        2602        1
98        819188                       UNPAID        2584        1
99        575866                     CabForce          25        1
100       722061                  MyTransfers          14        1

[101 rows x 4 columns]

In [12]:
newyork_q = select(newyork_t.c.dispatch_id, newyork_t.c.vehicle_class_id,newyork_t.c.vehicle_class, func.COUNT(newyork_t.c.dispatch_id).label('count')).group_by(newyork_t.c.vehicle_class_id).order_by(desc('count'))
df = pd.read_sql(newyork_q, sql_eng)
df

    dispatch_id  vehicle_class_id               vehicle_class   count
0           155               1.0                       Sedan  204787
1         11477               6.0                       MPV-4   57346
2         22635               3.0                       MPV-5   34548
3         20401               2.0              Business Sedan   11243
4        105113               4.0                Business SUV    5165
5         44571               9.0                  Minibus-10    2826
6         27013               5.0                   Minibus-8    2256
7         32500              11.0                  Minibus-14    1132
8        658629              10.0                  Minibus-12     982
9        355265              36.0            Business Minivan     385
10       649545              29.0                 16-seat Bus      90
11       219054              30.0                 20-seat Bus      72
12      1827039              32.0                 27-seat Bus      51
13      1806321              40.0           First Class Sedan      48
14      1259495              33.0                 36-seat Bus      47
15      2460397              31.0                 23-seat Bus      46
16       325847              35.0           55-seat Coach Bus      40
17       411536              41.0                    EV Sedan      32
18      2348890              21.0   6 Passenger Stretch Sedan      30
19       177473              34.0           44-seat Coach Bus      28
20         5197               NaN                        None      27
21       463842              22.0   8 Passenger Stretch Sedan      24
22       415843              23.0  10 Passenger Stretch Sedan      12
23      2459315              12.0               Comfort Sedan      10
24       826847              50.0              Wheelchair Van       6
25       838611               8.0                   Minibus-7       6
26       530721              52.0              School Minivan       3
27       444667              48.0                      EV SUV       3
28      1200545              13.0              Business MPV-4       3
29      1272625             103.0          Black Business SUV       2
30       571461              42.0           EV Business Sedan       2
31       342256              27.0   16 Passenger Stretch Limo       2
32      2705100              25.0      12 Passenger Party Bus       2
33       747200              49.0             EV Business SUV       1
34       513967              43.0        EV First Class Sedan       1
35       359954              24.0    12 Passenger Stretch SUV       1

## convert service area table cvs to sqlite db

In [10]:
df = pd.read_csv('../data/service_area_2024.csv', index_col='ride_id')

In [11]:
df.shape
df.iloc[:5,:]

(786832, 3)

         service_area_id     from_time_str        service_area
ride_id
3596861              273  2024-09-02 10:15            HangZhou
3591584             1435  2024-09-17 16:20  Berlin-BER,Germany
3581482              277  2024-09-06 18:00     Barcelona,Spain
3555299              913  2024-09-03 07:45     Nevsehir,Turkey
3597835              365  2024-09-11 22:20   Reykjavik,Iceland

In [12]:
df.to_sql('service_area_2024', sqlite_eng, if_exists='replace', index=True)

786832

## convert route deduplication result to sqlite db

In [1]:
csv_result_file_list = ['../data/price_training_2324_start_result.csv',
                        '../data/price_training_2324_end_result.csv']
csv_result_table_list = ['price_training_2324_start_result',
                        'price_training_2324_end_result']

chunk_size = 10000
total_lines = [sum(1 for line in open(csv_result_file_list[0])),sum(1 for line in open(csv_result_file_list[1]))]
print(total_lines)

[117354, 199931]

In [2]:

from sqlalchemy import create_engine
import pandas as pd
import numpy as np
from tqdm import tqdm

sqlite_eng = create_engine('sqlite:///../data/price_training_raw.db', echo=False)

sample = pd.read_csv(csv_result_file_list[1], index_col='dispatch_id', nrows=5)
sample

,index,ride_id,trip_count,ride_inserted_at,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,passenger_count,...,end_ltt,vehicle_class_id,vehicle_class,row_num,route_start,route_end,start_ltt_lp,start_lng_lp,end_ltt_lp,end_lng_lp
dispatch_id,,,,,,,,,,,,,,,,,,,,,
496635,0,2388614,1,2022-11-02 21:22:10.000000,1675168200,2023-01-31 09:30,America/Argentina/Ushuaia,NaN,NaN,2.0,...,-54.843300,1.0,Sedan,1,NaN,NaN,-54.84186,-68.37252,-54.84330,-68.29580
2560396,1,3419727,1,2024-04-22 22:17:24.000000,1714996800,2024-05-06 09:00,America/Argentina/Ushuaia,NaN,NaN,4.0,...,-54.842234,3.0,MPV-5,1,CHC,Christchurch,-54.80735,-68.35211,-54.84223,-68.31189
496634,2,2388613,1,2022-11-02 21:22:10.000000,1674912600,2023-01-28 10:30,America/Argentina/Ushuaia,NaN,NaN,2.0,...,-54.841858,1.0,Sedan,1,NaN,NaN,-54.84330,-68.29580,-54.84186,-68.37252
1965848,3,3126903,1,2024-01-10 19:02:38.000000,1706639400,2024-01-30 15:30,America/Argentina/Ushuaia,NaN,NaN,2.0,...,-54.841829,1.0,Sedan,1,NaN,NaN,-54.84330,-68.29580,-54.84183,-68.37259
556892,4,2417357,1,2022-12-18 20:16:19.000000,1672594200,2023-01-01 14:30,Argentina Standard Time,NaN,NaN,3.0,...,-54.841827,1.0,Sedan,1,NaN,NaN,-54.83956,-68.31224,-54.84183,-68.37265

In [3]:
for t in range(2):
    for chunk in tqdm(pd.read_csv(csv_result_file_list[t], index_col='dispatch_id', chunksize=chunk_size),
                      total=total_lines[t] // chunk_size + 1):
        # for chunk in tqdm(pd.read_csv(csv_file_path, chunksize=chunk_size), total=total_lines//chunk_size +1):
        chunk.to_sql(csv_result_table_list[t], sqlite_eng, if_exists='append', index=True)

100%|██████████| 12/12 [00:03<00:00,  3.43it/s]
100%|██████████| 20/20 [00:06<00:00,  3.25it/s]

## Get the union of the label tables

In [9]:
#| export
from sqlalchemy import MetaData, create_engine, asc, desc, and_, or_, not_, case, extract, cast, Numeric, text, distinct, Column, update, bindparam
from sqlalchemy.types import DateTime, Date, Time, String
from sqlalchemy.schema import *
from sqlalchemy.sql import func as F, Selectable, select, union
from sqlalchemy.dialects import registry
from sqlalchemy.engine.row import Row
from sqlalchemy.orm import Session
from sqlalchemy.orm import sessionmaker
import pandas as pd

In [14]:
sql_eng = create_engine('sqlite:///../data/price_training_raw.db', echo=False)
conn = sql_eng.connect()
metadata = MetaData()
Session = sessionmaker(bind=sql_eng)
session = Session()
chunk_size = 100

In [3]:
label_list = ['price_training_2324_start_result',
              'price_training_2324_end_result',
              'price_training_2324_route_label',]

In [4]:
label_start_t = Table(label_list[0], metadata, autoload_with=sql_eng)
print(session.query(label_start_t).count())
label_end_t = Table(label_list[1], metadata, autoload_with=sql_eng)
print(session.query(label_end_t).count())

117345
199917

In [5]:
label_start_q = session.query(label_start_t)
label_start_q.count()
label_end_q = session.query(label_end_t)
label_end_q.count()

199917

In [6]:
label_start_t.columns.keys()

['dispatch_id',
 'index',
 'ride_id',
 'trip_count',
 'ride_inserted_at',
 'from_utc',
 'from_time_str',
 'from_timezone_str',
 'to_time_str',
 'to_timezone_str',
 'passenger_count',
 'luggage_count',
 'children_count',
 'infant_count',
 'distance',
 'duration',
 'trip_no',
 'dispatch_amount',
 'dispatch_currency',
 'dispatch_inserted_at',
 'from_cur',
 'to_cur',
 'rate',
 'effective_at',
 'expire_at',
 'from_date_str',
 'from_time_fix_str',
 'from_datetime_fix_str',
 'trip_type_id',
 'trip_type',
 'ride_status_id',
 'ride_status',
 'dispatch_status_id',
 'dispatch_status',
 'dispatch_type',
 'fleet',
 'partner_id',
 'partner',
 'service_area_id',
 'service_area',
 'start_place_id',
 'start_place',
 'start_lng',
 'start_ltt',
 'end_place_id',
 'end_place',
 'end_lng',
 'end_ltt',
 'vehicle_class_id',
 'vehicle_class',
 'row_num',
 'route_start',
 'route_end',
 'start_ltt_lp',
 'start_lng_lp',
 'end_ltt_lp',
 'end_lng_lp']

In [7]:
label_routes_q = union(label_start_q, label_end_q)

In [16]:
df = pd.read_sql(label_routes_q, sql_eng)
# {l:r for l,r in zip(df.columns,label_start_t.columns.keys())}
df.columns = label_start_t.columns.keys()
# df.index = df['dispatch_id']
df.set_index(['start_ltt_lp', 'start_lng_lp', 'end_ltt_lp', 'end_lng_lp'], inplace=True)
# df.set_index('dispatch_id', inplace=True)
df

                                                 dispatch_id   index  ride_id  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
-4.61764      55.41105    -1.32271    36.92607         30831   12992  2180214
                                      36.92607         30831   26590  2180214
 49.19669    -123.18151    49.28247  -123.11861        87749  183908  2206773
 29.65561    -95.27792     29.30810  -94.79726        101558   52498  2213222
 37.61487    -122.38985    37.79414  -122.40779       123241  128980  2222284
...                                                      ...     ...      ...
 34.43474     135.24427    34.69992   135.49596      3520264   60364  3385498
                                      135.49596      3520264  111501  3385498
 48.86559     2.78936      48.88206   2.33163        3520518  181762  3504514
 12.27395     102.31867    12.14091   102.26939      3521108   47970  3371394
 22.29503     114.16764    22.30805   113.91848      3521584   42733  3505811

                                                 trip_count  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
-4.61764      55.41105    -1.32271    36.92607            1
                                      36.92607            1
 49.19669    -123.18151    49.28247  -123.11861           1
 29.65561    -95.27792     29.30810  -94.79726            1
 37.61487    -122.38985    37.79414  -122.40779           1
...                                                     ...
 34.43474     135.24427    34.69992   135.49596           1
                                      135.49596           1
 48.86559     2.78936      48.88206   2.33163             1
 12.27395     102.31867    12.14091   102.26939           1
 22.29503     114.16764    22.30805   113.91848           1

                                                           ride_inserted_at  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
-4.61764      55.41105    -1.32271    36.92607   2021-07-05 03:33:42.000000
                                      36.92607   2021-07-05 03:33:42.000000
 49.19669    -123.18151    49.28247  -123.11861  2021-11-08 20:59:33.000000
 29.65561    -95.27792     29.30810  -94.79726   2021-11-29 00:22:16.000000
 37.61487    -122.38985    37.79414  -122.40779  2021-12-28 02:58:33.000000
...                                                                     ...
 34.43474     135.24427    34.69992   135.49596  2024-04-08 17:40:37.000000
                                      135.49596  2024-04-08 17:40:37.000000
 48.86559     2.78936      48.88206   2.33163    2024-05-31 10:42:11.000000
 12.27395     102.31867    12.14091   102.26939  2024-04-02 17:29:22.000000
 22.29503     114.16764    22.30805   113.91848  2024-06-01 05:34:21.000000

                                                     from_utc  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
-4.61764      55.41105    -1.32271    36.92607   1.676626e+09
                                      36.92607   1.676626e+09
 49.19669    -123.18151    49.28247  -123.11861  1.693854e+09
 29.65561    -95.27792     29.30810  -94.79726   1.702665e+09
 37.61487    -122.38985    37.79414  -122.40779  1.740210e+09
...                                                       ...
 34.43474     135.24427    34.69992   135.49596  1.729349e+09
                                      135.49596  1.729349e+09
 48.86559     2.78936      48.88206   2.33163    1.731260e+09
 12.27395     102.31867    12.14091   102.26939  1.730357e+09
 22.29503     114.16764    22.30805   113.91848  1.729206e+09

                                                    from_time_str  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
-4.61764      55.41105    -1.32271    36.92607   2023-02-17 13:30
                                      36.92607   2023-02-17 13:30
 49.19669    -123.18151    49.28247  -123.11861  2023-09-04 12:00
 29.65561    -95.27792     29.30810  -94.79726   2023-12-15 12:30
 37.61487    -122.38985    37.79414  -122.40779  2025-02-21 23:45
...                                                           ...
 34.43474     135.24427    34.69992   135.49596  2024-10-19 23:45
                                      135.49596  2024-10-19 23:45
 48.86559     2.78936      48.88206   2.33163    2024-11-10 18:30
 12.27395     102.31867    12.14091   102.26939  2024-10-31 13:40
 22.29503     114.16764    22.30805   113.91848  2024-10-18 07:00

                                                     from_timezone_str  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
-4.61764      55.41105    -1.32271    36.92607        East Africa Time
                                      36.92607        East Africa Time
 49.19669    -123.18151    49.28247  -123.11861  Pacific Daylight Time
 29.65561    -95.27792     29.30810  -94.79726   Central Standard Time
 37.61487    -122.38985    37.79414  -122.40779  Pacific Standard Time
...                                                                ...
 34.43474     135.24427    34.69992   135.49596             Asia/Tokyo
                                      135.49596             Asia/Tokyo
 48.86559     2.78936      48.88206   2.33163             Europe/Paris
 12.27395     102.31867    12.14091   102.26939           Asia/Bangkok
 22.29503     114.16764    22.30805   113.91848          Asia/Shanghai

                                                to_time_str to_timezone_str  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
-4.61764      55.41105    -1.32271    36.92607         None            None
                                      36.92607         None            None
 49.19669    -123.18151    49.28247  -123.11861        None            None
 29.65561    -95.27792     29.30810  -94.79726         None            None
 37.61487    -122.38985    37.79414  -122.40779        None            None
...                                                     ...             ...
 34.43474     135.24427    34.69992   135.49596        None            None
                                      135.49596        None            None
 48.86559     2.78936      48.88206   2.33163          None            None
 12.27395     102.31867    12.14091   102.26939        None            None
 22.29503     114.16764    22.30805   113.91848        None            None

                                                 ...  start_ltt  end_place_id  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp  ...
-4.61764      55.41105    -1.32271    36.92607   ...  -4.617643        2354.0
                                      36.92607   ...  -4.617643        2354.0
 49.19669    -123.18151    49.28247  -123.11861  ...  49.196691       20648.0
 29.65561    -95.27792     29.30810  -94.79726   ...  29.655610       23200.0
 37.61487    -122.38985    37.79414  -122.40779  ...  37.614871        1868.0
...                                              ...        ...           ...
 34.43474     135.24427    34.69992   135.49596  ...  34.434735     1454365.0
                                      135.49596  ...  34.434735     1454365.0
 48.86559     2.78936      48.88206   2.33163    ...  48.865589     1688499.0
 12.27395     102.31867    12.14091   102.26939  ...  12.273953     1426271.0
 22.29503     114.16764    22.30805   113.91848  ...  22.295032     1691011.0

                                                                                         end_place  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
-4.61764      55.41105    -1.32271    36.92607                 Jomo Kenyatta International Airport
                                      36.92607                 Jomo Kenyatta International Airport
 49.19669    -123.18151    49.28247  -123.11861                              Vancouver City Centre
 29.65561    -95.27792     29.30810  -94.79726   Port of Galveston Cruise Terminal 1 2502 Harbo...
 37.61487    -122.38985    37.79414  -122.40779                           旧金山唐人街 美国加利福尼亚州旧金山旧金山唐人街
...                                                                                            ...
 34.43474     135.24427    34.69992   135.49596                                       Hilton Osaka
                                      135.49596                                       Hilton Osaka
 48.86559     2.78936      48.88206   2.33163                     R. Kipling Hotel by Happyculture
 12.27395     102.31867    12.14091   102.26939  Sunset Emily Villas & Rooms, Unnamed Road, Tam...
 22.29503     114.16764    22.30805   113.91848                                  Hong Kong Airport

                                                    end_lng    end_ltt  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
-4.61764      55.41105    -1.32271    36.92607    36.926069  -1.322710
                                      36.92607    36.926069  -1.322710
 49.19669    -123.18151    49.28247  -123.11861 -123.118613  49.282469
 29.65561    -95.27792     29.30810  -94.79726   -94.797258  29.308097
 37.61487    -122.38985    37.79414  -122.40779 -122.407791  37.794138
...                                                     ...        ...
 34.43474     135.24427    34.69992   135.49596  135.495956  34.699924
                                      135.49596  135.495956  34.699924
 48.86559     2.78936      48.88206   2.33163      2.331629  48.882061
 12.27395     102.31867    12.14091   102.26939  102.269386  12.140911
 22.29503     114.16764    22.30805   113.91848  113.918481  22.308047

                                                 vehicle_class_id  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
-4.61764      55.41105    -1.32271    36.92607                1.0
                                      36.92607                1.0
 49.19669    -123.18151    49.28247  -123.11861               1.0
 29.65561    -95.27792     29.30810  -94.79726                3.0
 37.61487    -122.38985    37.79414  -122.40779               1.0
...                                                           ...
 34.43474     135.24427    34.69992   135.49596              36.0
                                      135.49596              36.0
 48.86559     2.78936      48.88206   2.33163                 6.0
 12.27395     102.31867    12.14091   102.26939               1.0
 22.29503     114.16764    22.30805   113.91848               1.0

                                                    vehicle_class  row_num  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
-4.61764      55.41105    -1.32271    36.92607              Sedan        1
                                      36.92607              Sedan        1
 49.19669    -123.18151    49.28247  -123.11861             Sedan        1
 29.65561    -95.27792     29.30810  -94.79726              MPV-5        1
 37.61487    -122.38985    37.79414  -122.40779             Sedan        1
...                                                           ...      ...
 34.43474     135.24427    34.69992   135.49596  Business Minivan        1
                                      135.49596  Business Minivan        1
 48.86559     2.78936      48.88206   2.33163               MPV-4        1
 12.27395     102.31867    12.14091   102.26939             Sedan        1
 22.29503     114.16764    22.30805   113.91848             Sedan        1

                                                route_start  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
-4.61764      55.41105    -1.32271    36.92607         None
                                      36.92607         None
 49.19669    -123.18151    49.28247  -123.11861         YVR
 29.65561    -95.27792     29.30810  -94.79726          HOU
 37.61487    -122.38985    37.79414  -122.40779         SFO
...                                                     ...
 34.43474     135.24427    34.69992   135.49596         KIX
                                      135.49596         KIX
 48.86559     2.78936      48.88206   2.33163           迪士尼
 12.27395     102.31867    12.14091   102.26939         TDX
 22.29503     114.16764    22.30805   113.91848          九龙

                                                                  route_end
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
-4.61764      55.41105    -1.32271    36.92607                         None
                                      36.92607                         None
 49.19669    -123.18151    49.28247  -123.11861                   Vancouver
 29.65561    -95.27792     29.30810  -94.79726                Galveston, TX
 37.61487    -122.38985    37.79414  -122.40779               san francisco
...                                                                     ...
 34.43474     135.24427    34.69992   135.49596                          大阪
                                      135.49596                          大阪
 48.86559     2.78936      48.88206   2.33163                         Paris
 12.27395     102.31867    12.14091   102.26939  Mu Koh Chang National Park
 22.29503     114.16764    22.30805   113.91848                         HKG

[317262 rows x 53 columns]

In [14]:
# df.sort_values(['start_ltt_lp', 'start_lng_lp', 'end_ltt_lp', 'end_lng_lp'], inplace=True)

In [17]:
df.dropna(subset=['route_start', 'route_end'], how='any', inplace=True)
df

                                                 dispatch_id   index  ride_id  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
49.19669     -123.18151   49.28247   -123.11861        87749  183908  2206773
29.65561     -95.27792    29.30810   -94.79726        101558   52498  2213222
37.61487     -122.38985   37.79414   -122.40779       123241  128980  2222284
19.43608     -99.07191    19.28447   -99.14919        140298   68154  2230107
40.75203     -73.98472    40.64131   -73.77814        155022   84728  2238054
...                                                      ...     ...      ...
34.43474      135.24427   34.69992    135.49596      3520264   60364  3385498
                                      135.49596      3520264  111501  3385498
48.86559      2.78936     48.88206    2.33163        3520518  181762  3504514
12.27395      102.31867   12.14091    102.26939      3521108   47970  3371394
22.29503      114.16764   22.30805    113.91848      3521584   42733  3505811

                                                 trip_count  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
49.19669     -123.18151   49.28247   -123.11861           1
29.65561     -95.27792    29.30810   -94.79726            1
37.61487     -122.38985   37.79414   -122.40779           1
19.43608     -99.07191    19.28447   -99.14919            1
40.75203     -73.98472    40.64131   -73.77814            1
...                                                     ...
34.43474      135.24427   34.69992    135.49596           1
                                      135.49596           1
48.86559      2.78936     48.88206    2.33163             1
12.27395      102.31867   12.14091    102.26939           1
22.29503      114.16764   22.30805    113.91848           1

                                                           ride_inserted_at  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
49.19669     -123.18151   49.28247   -123.11861  2021-11-08 20:59:33.000000
29.65561     -95.27792    29.30810   -94.79726   2021-11-29 00:22:16.000000
37.61487     -122.38985   37.79414   -122.40779  2021-12-28 02:58:33.000000
19.43608     -99.07191    19.28447   -99.14919   2022-01-25 08:11:14.000000
40.75203     -73.98472    40.64131   -73.77814   2022-02-13 15:39:56.000000
...                                                                     ...
34.43474      135.24427   34.69992    135.49596  2024-04-08 17:40:37.000000
                                      135.49596  2024-04-08 17:40:37.000000
48.86559      2.78936     48.88206    2.33163    2024-05-31 10:42:11.000000
12.27395      102.31867   12.14091    102.26939  2024-04-02 17:29:22.000000
22.29503      114.16764   22.30805    113.91848  2024-06-01 05:34:21.000000

                                                     from_utc  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
49.19669     -123.18151   49.28247   -123.11861  1.693854e+09
29.65561     -95.27792    29.30810   -94.79726   1.702665e+09
37.61487     -122.38985   37.79414   -122.40779  1.740210e+09
19.43608     -99.07191    19.28447   -99.14919   1.682032e+09
40.75203     -73.98472    40.64131   -73.77814   1.672850e+09
...                                                       ...
34.43474      135.24427   34.69992    135.49596  1.729349e+09
                                      135.49596  1.729349e+09
48.86559      2.78936     48.88206    2.33163    1.731260e+09
12.27395      102.31867   12.14091    102.26939  1.730357e+09
22.29503      114.16764   22.30805    113.91848  1.729206e+09

                                                    from_time_str  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
49.19669     -123.18151   49.28247   -123.11861  2023-09-04 12:00
29.65561     -95.27792    29.30810   -94.79726   2023-12-15 12:30
37.61487     -122.38985   37.79414   -122.40779  2025-02-21 23:45
19.43608     -99.07191    19.28447   -99.14919   2023-04-20 17:00
40.75203     -73.98472    40.64131   -73.77814   2023-01-04 11:30
...                                                           ...
34.43474      135.24427   34.69992    135.49596  2024-10-19 23:45
                                      135.49596  2024-10-19 23:45
48.86559      2.78936     48.88206    2.33163    2024-11-10 18:30
12.27395      102.31867   12.14091    102.26939  2024-10-31 13:40
22.29503      114.16764   22.30805    113.91848  2024-10-18 07:00

                                                     from_timezone_str  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
49.19669     -123.18151   49.28247   -123.11861  Pacific Daylight Time
29.65561     -95.27792    29.30810   -94.79726   Central Standard Time
37.61487     -122.38985   37.79414   -122.40779  Pacific Standard Time
19.43608     -99.07191    19.28447   -99.14919   Central Standard Time
40.75203     -73.98472    40.64131   -73.77814   Eastern Standard Time
...                                                                ...
34.43474      135.24427   34.69992    135.49596             Asia/Tokyo
                                      135.49596             Asia/Tokyo
48.86559      2.78936     48.88206    2.33163             Europe/Paris
12.27395      102.31867   12.14091    102.26939           Asia/Bangkok
22.29503      114.16764   22.30805    113.91848          Asia/Shanghai

                                                to_time_str to_timezone_str  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
49.19669     -123.18151   49.28247   -123.11861        None            None
29.65561     -95.27792    29.30810   -94.79726         None            None
37.61487     -122.38985   37.79414   -122.40779        None            None
19.43608     -99.07191    19.28447   -99.14919         None            None
40.75203     -73.98472    40.64131   -73.77814         None            None
...                                                     ...             ...
34.43474      135.24427   34.69992    135.49596        None            None
                                      135.49596        None            None
48.86559      2.78936     48.88206    2.33163          None            None
12.27395      102.31867   12.14091    102.26939        None            None
22.29503      114.16764   22.30805    113.91848        None            None

                                                 ...  start_ltt  end_place_id  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp  ...
49.19669     -123.18151   49.28247   -123.11861  ...  49.196691       20648.0
29.65561     -95.27792    29.30810   -94.79726   ...  29.655610       23200.0
37.61487     -122.38985   37.79414   -122.40779  ...  37.614871        1868.0
19.43608     -99.07191    19.28447   -99.14919   ...  19.436076       29370.0
40.75203     -73.98472    40.64131   -73.77814   ...  40.752027           9.0
...                                              ...        ...           ...
34.43474      135.24427   34.69992    135.49596  ...  34.434735     1454365.0
                                      135.49596  ...  34.434735     1454365.0
48.86559      2.78936     48.88206    2.33163    ...  48.865589     1688499.0
12.27395      102.31867   12.14091    102.26939  ...  12.273953     1426271.0
22.29503      114.16764   22.30805    113.91848  ...  22.295032     1691011.0

                                                                                         end_place  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
49.19669     -123.18151   49.28247   -123.11861                              Vancouver City Centre
29.65561     -95.27792    29.30810   -94.79726   Port of Galveston Cruise Terminal 1 2502 Harbo...
37.61487     -122.38985   37.79414   -122.40779                           旧金山唐人街 美国加利福尼亚州旧金山旧金山唐人街
19.43608     -99.07191    19.28447   -99.14919       School of Commerce and Administration Tepepan
40.75203     -73.98472    40.64131   -73.77814               John F. Kennedy International Airport
...                                                                                            ...
34.43474      135.24427   34.69992    135.49596                                       Hilton Osaka
                                      135.49596                                       Hilton Osaka
48.86559      2.78936     48.88206    2.33163                     R. Kipling Hotel by Happyculture
12.27395      102.31867   12.14091    102.26939  Sunset Emily Villas & Rooms, Unnamed Road, Tam...
22.29503      114.16764   22.30805    113.91848                                  Hong Kong Airport

                                                    end_lng    end_ltt  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
49.19669     -123.18151   49.28247   -123.11861 -123.118613  49.282469
29.65561     -95.27792    29.30810   -94.79726   -94.797258  29.308097
37.61487     -122.38985   37.79414   -122.40779 -122.407791  37.794138
19.43608     -99.07191    19.28447   -99.14919   -99.149190  19.284467
40.75203     -73.98472    40.64131   -73.77814   -73.778139  40.641311
...                                                     ...        ...
34.43474      135.24427   34.69992    135.49596  135.495956  34.699924
                                      135.49596  135.495956  34.699924
48.86559      2.78936     48.88206    2.33163      2.331629  48.882061
12.27395      102.31867   12.14091    102.26939  102.269386  12.140911
22.29503      114.16764   22.30805    113.91848  113.918481  22.308047

                                                 vehicle_class_id  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
49.19669     -123.18151   49.28247   -123.11861               1.0
29.65561     -95.27792    29.30810   -94.79726                3.0
37.61487     -122.38985   37.79414   -122.40779               1.0
19.43608     -99.07191    19.28447   -99.14919                1.0
40.75203     -73.98472    40.64131   -73.77814                6.0
...                                                           ...
34.43474      135.24427   34.69992    135.49596              36.0
                                      135.49596              36.0
48.86559      2.78936     48.88206    2.33163                 6.0
12.27395      102.31867   12.14091    102.26939               1.0
22.29503      114.16764   22.30805    113.91848               1.0

                                                    vehicle_class  row_num  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
49.19669     -123.18151   49.28247   -123.11861             Sedan        1
29.65561     -95.27792    29.30810   -94.79726              MPV-5        1
37.61487     -122.38985   37.79414   -122.40779             Sedan        1
19.43608     -99.07191    19.28447   -99.14919              Sedan        1
40.75203     -73.98472    40.64131   -73.77814              MPV-4        1
...                                                           ...      ...
34.43474      135.24427   34.69992    135.49596  Business Minivan        1
                                      135.49596  Business Minivan        1
48.86559      2.78936     48.88206    2.33163               MPV-4        1
12.27395      102.31867   12.14091    102.26939             Sedan        1
22.29503      114.16764   22.30805    113.91848             Sedan        1

                                                route_start  \
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
49.19669     -123.18151   49.28247   -123.11861         YVR
29.65561     -95.27792    29.30810   -94.79726          HOU
37.61487     -122.38985   37.79414   -122.40779         SFO
19.43608     -99.07191    19.28447   -99.14919          MEX
40.75203     -73.98472    40.64131   -73.77814          曼哈顿
...                                                     ...
34.43474      135.24427   34.69992    135.49596         KIX
                                      135.49596         KIX
48.86559      2.78936     48.88206    2.33163           迪士尼
12.27395      102.31867   12.14091    102.26939         TDX
22.29503      114.16764   22.30805    113.91848          九龙

                                                                  route_end
start_ltt_lp start_lng_lp end_ltt_lp end_lng_lp
49.19669     -123.18151   49.28247   -123.11861                   Vancouver
29.65561     -95.27792    29.30810   -94.79726                Galveston, TX
37.61487     -122.38985   37.79414   -122.40779               san francisco
19.43608     -99.07191    19.28447   -99.14919            Mexico city south
40.75203     -73.98472    40.64131   -73.77814                          JFK
...                                                                     ...
34.43474      135.24427   34.69992    135.49596                          大阪
                                      135.49596                          大阪
48.86559      2.78936     48.88206    2.33163                         Paris
12.27395      102.31867   12.14091    102.26939  Mu Koh Chang National Park
22.29503      114.16764   22.30805    113.91848                         HKG

[251387 rows x 53 columns]

In [18]:
df.drop_duplicates(subset=['route_start', 'route_end', 'vehicle_class_id'], inplace=True)
df

,,,,dispatch_id,index,ride_id,trip_count,ride_inserted_at,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,...,start_ltt,end_place_id,end_place,end_lng,end_ltt,vehicle_class_id,vehicle_class,row_num,route_start,route_end
start_ltt_lp,start_lng_lp,end_ltt_lp,end_lng_lp,,,,,,,,,,,,,,,,,,,,,
49.19669,-123.18151,49.28247,-123.11861,87749,183908,2206773,1,2021-11-08 20:59:33.000000,1.693854e+09,2023-09-04 12:00,Pacific Daylight Time,None,None,...,49.196691,20648.0,Vancouver City Centre,-123.118613,49.282469,1.0,Sedan,1,YVR,Vancouver
29.65561,-95.27792,29.30810,-94.79726,101558,52498,2213222,1,2021-11-29 00:22:16.000000,1.702665e+09,2023-12-15 12:30,Central Standard Time,None,None,...,29.655610,23200.0,Port of Galveston Cruise Terminal 1 2502 Harbo...,-94.797258,29.308097,3.0,MPV-5,1,HOU,"Galveston, TX"
37.61487,-122.38985,37.79414,-122.40779,123241,128980,2222284,1,2021-12-28 02:58:33.000000,1.740210e+09,2025-02-21 23:45,Pacific Standard Time,None,None,...,37.614871,1868.0,旧金山唐人街 美国加利福尼亚州旧金山旧金山唐人街,-122.407791,37.794138,1.0,Sedan,1,SFO,san francisco
19.43608,-99.07191,19.28447,-99.14919,140298,68154,2230107,1,2022-01-25 08:11:14.000000,1.682032e+09,2023-04-20 17:00,Central Standard Time,None,None,...,19.436076,29370.0,School of Commerce and Administration Tepepan,-99.149190,19.284467,1.0,Sedan,1,MEX,Mexico city south
40.75203,-73.98472,40.64131,-73.77814,155022,84728,2238054,1,2022-02-13 15:39:56.000000,1.672850e+09,2023-01-04 11:30,Eastern Standard Time,None,None,...,40.752027,9.0,John F. Kennedy International Airport,-73.778139,40.641311,6.0,MPV-4,1,曼哈顿,JFK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68.60856,27.41785,68.33424,27.33475,3412990,117194,3513268,1,2024-06-05 03:20:02.000000,1.728124e+09,2024-10-05 13:31,Europe/Helsinki,None,None,...,68.608565,1705602.0,Kakslauttanen Arctic Resort,27.334750,68.334235,7.0,MPV-6,1,IVL,KSL
43.76993,11.25736,43.50179,11.05265,3459229,99635,3428747,1,2024-04-26 13:24:39.000000,1.728374e+09,2024-10-08 10:00,Europe/Rome,None,None,...,43.769928,1539648.0,"Mormoraia, San Gimignano, Province of Siena, I...",11.052654,43.501786,36.0,Business Minivan,1,Florence,Mormoraia
37.24060,27.67320,37.07971,27.47213,3463779,122785,3323119,1,2024-03-17 16:02:07.000000,1.728470e+09,2024-10-09 13:35,Europe/Istanbul,None,None,...,37.240600,1334807.0,Hyde Bodrum,27.472133,37.079713,33.0,36-seat Bus,1,BJV,torba
37.01440,-7.96591,38.70826,-9.13963,3497778,133012,3333827,1,2024-03-20 20:35:39.000000,1.729853e+09,2024-10-25 11:45,Europe/Lisbon,None,None,...,37.014400,1355926.0,"AlmaLusa Baixa/Chiado, Praça do Município, Lis...",-9.139630,38.708258,5.0,Minibus-8,1,FAO,Lisbon
38.95062,-77.45685,38.81502,-77.04339,3497952,136596,3491436,1,2024-05-24 20:27:50.000000,1.731517e+09,2024-11-13 12:00,America/New_York,None,None,...,38.950620,1663145.0,"534 First St, Alexandria, VA 22314, USA",-77.043390,38.815021,2.0,Business Sedan,1,IAD,National Harbor

In [20]:
df = df.reindex(columns=df.columns.tolist() + ['cost','profit'])
df

,,,,dispatch_id,index,ride_id,trip_count,ride_inserted_at,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,...,end_place,end_lng,end_ltt,vehicle_class_id,vehicle_class,row_num,route_start,route_end,cost,profit
start_ltt_lp,start_lng_lp,end_ltt_lp,end_lng_lp,,,,,,,,,,,,,,,,,,,,,
49.19669,-123.18151,49.28247,-123.11861,87749,183908,2206773,1,2021-11-08 20:59:33.000000,1.693854e+09,2023-09-04 12:00,Pacific Daylight Time,None,None,...,Vancouver City Centre,-123.118613,49.282469,1.0,Sedan,1,YVR,Vancouver,NaN,NaN
29.65561,-95.27792,29.30810,-94.79726,101558,52498,2213222,1,2021-11-29 00:22:16.000000,1.702665e+09,2023-12-15 12:30,Central Standard Time,None,None,...,Port of Galveston Cruise Terminal 1 2502 Harbo...,-94.797258,29.308097,3.0,MPV-5,1,HOU,"Galveston, TX",NaN,NaN
37.61487,-122.38985,37.79414,-122.40779,123241,128980,2222284,1,2021-12-28 02:58:33.000000,1.740210e+09,2025-02-21 23:45,Pacific Standard Time,None,None,...,旧金山唐人街 美国加利福尼亚州旧金山旧金山唐人街,-122.407791,37.794138,1.0,Sedan,1,SFO,san francisco,NaN,NaN
19.43608,-99.07191,19.28447,-99.14919,140298,68154,2230107,1,2022-01-25 08:11:14.000000,1.682032e+09,2023-04-20 17:00,Central Standard Time,None,None,...,School of Commerce and Administration Tepepan,-99.149190,19.284467,1.0,Sedan,1,MEX,Mexico city south,NaN,NaN
40.75203,-73.98472,40.64131,-73.77814,155022,84728,2238054,1,2022-02-13 15:39:56.000000,1.672850e+09,2023-01-04 11:30,Eastern Standard Time,None,None,...,John F. Kennedy International Airport,-73.778139,40.641311,6.0,MPV-4,1,曼哈顿,JFK,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68.60856,27.41785,68.33424,27.33475,3412990,117194,3513268,1,2024-06-05 03:20:02.000000,1.728124e+09,2024-10-05 13:31,Europe/Helsinki,None,None,...,Kakslauttanen Arctic Resort,27.334750,68.334235,7.0,MPV-6,1,IVL,KSL,NaN,NaN
43.76993,11.25736,43.50179,11.05265,3459229,99635,3428747,1,2024-04-26 13:24:39.000000,1.728374e+09,2024-10-08 10:00,Europe/Rome,None,None,...,"Mormoraia, San Gimignano, Province of Siena, I...",11.052654,43.501786,36.0,Business Minivan,1,Florence,Mormoraia,NaN,NaN
37.24060,27.67320,37.07971,27.47213,3463779,122785,3323119,1,2024-03-17 16:02:07.000000,1.728470e+09,2024-10-09 13:35,Europe/Istanbul,None,None,...,Hyde Bodrum,27.472133,37.079713,33.0,36-seat Bus,1,BJV,torba,NaN,NaN
37.01440,-7.96591,38.70826,-9.13963,3497778,133012,3333827,1,2024-03-20 20:35:39.000000,1.729853e+09,2024-10-25 11:45,Europe/Lisbon,None,None,...,"AlmaLusa Baixa/Chiado, Praça do Município, Lis...",-9.139630,38.708258,5.0,Minibus-8,1,FAO,Lisbon,NaN,NaN
38.95062,-77.45685,38.81502,-77.04339,3497952,136596,3491436,1,2024-05-24 20:27:50.000000,1.731517e+09,2024-11-13 12:00,America/New_York,None,None,...,"534 First St, Alexandria, VA 22314, USA",-77.043390,38.815021,2.0,Business Sedan,1,IAD,National Harbor,NaN,NaN

In [21]:
# df.to_sql(label_list[2], sqlite_eng, if_exists='append', index=True)
df.to_sql('routes_vehicle_class_2324', sql_eng, if_exists='append', index=True)

19482

# Precision reduction for start_ltt, start_lng, end_ltt, end_lng and pick distinct values

In [6]:
from tqdm.notebook import tqdm
from sqlalchemy import create_engine, select, func, distinct, MetaData, Table, update, bindparam, Column, insert, desc, asc, and_, or_, not_, Numeric, cast, func
from sqlalchemy.orm import sessionmaker, aliased
import pandas as pd
import numpy as np

In [8]:
sql_eng = create_engine('sqlite:///../data/price_training_raw.db', echo=False)
conn = sql_eng.connect()
my_table = Table('price_training_xrates_2024_usd', MetaData(), autoload_with=sql_eng)

In [9]:
query = select(func.count(distinct(my_table.c.dispatch_id)))

In [10]:
with sql_eng.connect() as connection:
    result = connection.execute(query)
    unique_count = result.scalar()
    
print(unique_count)

872937

In [11]:
query = select(my_table).limit(10)
df = pd.read_sql(query, conn, index_col='dispatch_id')
# df[['route_start','route_end']]
df

,ride_id,trip_count,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,passenger_count,luggage_count,children_count,...,start_ltt,end_place_id,end_place,end_lng,end_ltt,vehicle_class_id,vehicle_class,row_num,route_start,route_end
dispatch_id,,,,,,,,,,,,,,,,,,,,,
2231369,3262046,1,1709907300,2024-03-08 14:15,Europe/London,None,None,2.0,3.0,NaN,...,51.874699,1213723,"Mornington Hotel London Victoria, Gloucester S...",-0.140334,51.490317,1.0,Sedan,8,,
2380672,3325923,1,1711795500,2024-03-30 10:45,Europe/London,None,None,3.0,3.0,NaN,...,51.470600,1340384,"Novotel London Waterloo, Lambeth Road, London, UK",-0.118679,51.494654,1.0,Sedan,1,,
2290888,3291769,1,1710059400,2024-03-10 16:30,Asia/Makassar,None,None,2.0,2.0,NaN,...,-8.742199,1272546,"The Ulus Klumpu, Jl. Batu Nunggul, Pecatu, Kec...",115.098672,-8.838684,1.0,Sedan,3,,
2055209,3170389,1,1706391296,2024-01-27 22:32,Europe/Prague,None,None,4.0,2.0,NaN,...,50.104893,1036004,Michelangelo Grand Hotel,14.421419,50.081013,6.0,MPV-4,1,,
2691326,3456179,2,1716306000,2024-05-21 17:40,Europe/Berlin,2024-05-23 07:30,Central European Summer Time,1.0,1.0,0.0,...,53.047971,1650020,Arkadenhaus - Hotel Freiherr von Schwarzenberg,7.395067,53.078675,1.0,Sedan,30,,
2410501,3348472,1,1712566800,2024-04-08 12:00,Africa/Nairobi,None,None,2.0,2.0,NaN,...,-4.034855,1385010,"Diamonds Leisure Beach & Golf Resort, PH9V+P8V...",39.593202,-4.280521,1.0,Sedan,3,,
2223636,3258133,1,1709066700,2024-02-27 15:45,America/Toronto,None,None,2.0,2.0,NaN,...,45.322303,1205918,"377 Rue O'Connor Street Ottawa, ON K2P 2M2",-75.690897,45.413055,1.0,Sedan,1,,
2483278,3383792,1,1712619000,2024-04-08 18:30,America/Chicago,None,None,2.0,3.0,0.0,...,31.610295,1450974,"128 Reno Rd, Gatesville, TX 76528, USA",-97.685040,31.457460,1.0,Sedan,1,,
1041735,2657669,1,1708737600,2024-02-23 19:20,America/Chicago,None,None,3.0,3.0,NaN,...,29.991090,196037,"Prince Conti Hotel, 830 Conti St, New Orleans,...",-90.068408,29.956659,1.0,Sedan,1,,
2279002,3285856,1,1710884216,2024-03-19 22:34,Europe/Prague,None,None,1.0,2.0,NaN,...,50.104893,1260802,Louis Leger,14.430652,50.070347,6.0,MPV-4,1,,

# order by start_ltt, start_lng, end_ltt, end_lng

In [17]:
sql_eng = create_engine('sqlite:///../data/price_training_raw.db', echo=False)
conn = sql_eng.connect()
metadata = MetaData()
my_table = Table('price_training_xrates_2024_usd', metadata, autoload_with=sql_eng)

In [13]:
metadata.reflect(bind=sql_eng)
raw_t = metadata.tables['price_training_xrates_2024_usd']
s = select(raw_t).limit(10)
rp = sql_eng.connect().execute(s)
df = pd.DataFrame(rp)
df

,dispatch_id,ride_id,trip_count,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,passenger_count,luggage_count,...,start_ltt,end_place_id,end_place,end_lng,end_ltt,vehicle_class_id,vehicle_class,row_num,route_start,route_end
0,2231369,3262046,1,1709907300,2024-03-08 14:15,Europe/London,None,None,2.0,3.0,...,51.874699,1213723,"Mornington Hotel London Victoria, Gloucester S...",-0.140334,51.490317,1.0,Sedan,8,,
1,2380672,3325923,1,1711795500,2024-03-30 10:45,Europe/London,None,None,3.0,3.0,...,51.470600,1340384,"Novotel London Waterloo, Lambeth Road, London, UK",-0.118679,51.494654,1.0,Sedan,1,,
2,2290888,3291769,1,1710059400,2024-03-10 16:30,Asia/Makassar,None,None,2.0,2.0,...,-8.742199,1272546,"The Ulus Klumpu, Jl. Batu Nunggul, Pecatu, Kec...",115.098672,-8.838684,1.0,Sedan,3,,
3,2055209,3170389,1,1706391296,2024-01-27 22:32,Europe/Prague,None,None,4.0,2.0,...,50.104893,1036004,Michelangelo Grand Hotel,14.421419,50.081013,6.0,MPV-4,1,,
4,2691326,3456179,2,1716306000,2024-05-21 17:40,Europe/Berlin,2024-05-23 07:30,Central European Summer Time,1.0,1.0,...,53.047971,1650020,Arkadenhaus - Hotel Freiherr von Schwarzenberg,7.395067,53.078675,1.0,Sedan,30,,
5,2410501,3348472,1,1712566800,2024-04-08 12:00,Africa/Nairobi,None,None,2.0,2.0,...,-4.034855,1385010,"Diamonds Leisure Beach & Golf Resort, PH9V+P8V...",39.593202,-4.280521,1.0,Sedan,3,,
6,2223636,3258133,1,1709066700,2024-02-27 15:45,America/Toronto,None,None,2.0,2.0,...,45.322303,1205918,"377 Rue O'Connor Street Ottawa, ON K2P 2M2",-75.690897,45.413055,1.0,Sedan,1,,
7,2483278,3383792,1,1712619000,2024-04-08 18:30,America/Chicago,None,None,2.0,3.0,...,31.610295,1450974,"128 Reno Rd, Gatesville, TX 76528, USA",-97.685040,31.457460,1.0,Sedan,1,,
8,1041735,2657669,1,1708737600,2024-02-23 19:20,America/Chicago,None,None,3.0,3.0,...,29.991090,196037,"Prince Conti Hotel, 830 Conti St, New Orleans,...",-90.068408,29.956659,1.0,Sedan,1,,
9,2279002,3285856,1,1710884216,2024-03-19 22:34,Europe/Prague,None,None,1.0,2.0,...,50.104893,1260802,Louis Leger,14.430652,50.070347,6.0,MPV-4,1,,

In [14]:
# new_columns = [Column(col.name, col.type, primary_key=col.primary_key) for col in my_table.columns]
# new_table = Table('price_training_raw_2024_usd_reordered', metadata, *new_columns)
# new_table.create(sql_eng)
new_table = Table('price_training_xrates_2024_usd_reordered', metadata, autoload_with=sql_eng)

NoSuchTableError: price_training_xrates_2024_usd_reordered

In [16]:
Session = sessionmaker(bind=sql_eng)
session = Session()

## create new table with latitutde and longitude reduced to 5 decimal places

In [18]:
ordered_t = select(my_table).where(
    and_(
        my_table.c.start_ltt.isnot(None),
        my_table.c.start_lng.isnot(None),
    )
).order_by(asc(my_table.c.start_ltt), asc(my_table.c.start_ltt))
ordered_t = ordered_t.select_from(my_table)
ordered_t = ordered_t.alias()

In [ ]:
# ordered_t = ordered_t.limit(10)
# df = pd.read_sql(ordered_t,sql_eng)
# df

In [19]:
lp_ltt_lng_t = select(ordered_t.c.dispatch_id,
                      cast(ordered_t.c.start_ltt, Numeric(9,5)).label('start_ltt_lp'),
                      cast(ordered_t.c.start_lng, Numeric(9,5)).label('start_lng_lp'),
                      cast(ordered_t.c.end_ltt, Numeric(9,5)).label('end_ltt_lp'),
                      cast(ordered_t.c.end_lng, Numeric(9,5)).label('end_lng_lp'))
lp_ltt_lng_t = lp_ltt_lng_t.select_from(ordered_t)
lp_ltt_lng_t = lp_ltt_lng_t.alias()

In [ ]:
# df = pd.read_sql(lp_ltt_lng_t, sql_eng)
# df

In [20]:
distinct_start_lp_t = select(lp_ltt_lng_t.c.dispatch_id, 
                         lp_ltt_lng_t.c.start_ltt_lp,
                         # func.max(lp_ltt_lng_t.c.start_ltt_lp).label('unique_start_ltt_lp'), 
                         # func.max(lp_ltt_lng_t.c.start_lng_lp).label('unique_start_lng_lp'),
                         lp_ltt_lng_t.c.start_lng_lp, 
                         lp_ltt_lng_t.c.end_ltt_lp,
                         lp_ltt_lng_t.c.end_lng_lp
                         ).group_by(lp_ltt_lng_t.c.start_ltt_lp).distinct(lp_ltt_lng_t.c.start_lng_lp)#.subquery()
# distinct_subq_t = distinct_subq_t.limit(100)

In [ ]:

# df = pd.read_sql(distinct_start_lp_t, sql_eng)
# df

In [21]:

distinct_end_lp_t = select(lp_ltt_lng_t.c.dispatch_id, 
                         lp_ltt_lng_t.c.start_ltt_lp,
                         lp_ltt_lng_t.c.end_ltt_lp,
                         lp_ltt_lng_t.c.end_lng_lp
                         ).group_by(lp_ltt_lng_t.c.end_ltt_lp).distinct(lp_ltt_lng_t.c.end_lng_lp)
distinct_end_lp_t = distinct_end_lp_t.alias()

In [ ]:

# df = pd.read_sql(distinct_end_lp_t, sql_eng)
# df

In [ ]:

# distinct_t = select(distinct(lp_ltt_lng_t.c.start_lng_lp))
# distinct_t = distinct_t.limit(1000)#.distinct(lp_ltt_lng_t.c.start_ltt)
# df = pd.read_sql(distinct_t, sql_eng)
# df

## Create new table with ordered data

In [22]:
ordered_t = select(my_table).where(
    and_(
        my_table.c.start_ltt.isnot(None),
        my_table.c.start_lng.isnot(None),
    )
).order_by(asc(my_table.c.start_ltt), asc(my_table.c.start_ltt))
ordered_t = ordered_t.select_from(my_table)

In [23]:
with sql_eng.connect() as conn:
    result = conn.execute(ordered_t)
    ordered_rows = result.fetchall()
# ordered_rows[:3]

In [24]:
data = ordered_rows[:10]
cols = [c.name for c in ordered_t.subquery().columns]
df = pd.DataFrame(data=data, columns=cols)
df

,dispatch_id,ride_id,trip_count,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,passenger_count,luggage_count,...,start_ltt,end_place_id,end_place,end_lng,end_ltt,vehicle_class_id,vehicle_class,row_num,route_start,route_end
0,2809610,3388335,1,1721070000,2024-07-15 16:00,America/Argentina/Ushuaia,None,None,2.0,3.0,...,-54.8433,1459940,"Canal Beagle Hotel - Av. Maipú 547, V9410 Ushu...",-68.305640,-54.807333,1.0,Sedan,1,,
1,2669145,3248608,1,1718376300,2024-06-14 11:45,America/Argentina/Ushuaia,None,None,3.0,3.0,...,-54.8433,1187336,"Mustapic - Mustapic,Ushuaia,Argentina",-68.313890,-54.807487,1.0,Sedan,1,,
2,2176807,3235214,1,1721564100,2024-07-21 09:15,America/Argentina/Ushuaia,None,None,4.0,4.0,...,-54.8433,1159419,"Hotel Las Lengas - Hotel Las Lengas,Ushuaia,Ar...",-68.323484,-54.811373,6.0,MPV-4,6,,
3,2545374,3412639,1,1715695200,2024-05-14 11:00,America/Argentina/Ushuaia,None,None,2.0,3.0,...,-54.8433,1507812,"Rosa De Los Vientos - 25 de Mayo 8, V9410 DFB,...",-68.306038,-54.807396,1.0,Sedan,2,,
4,2085372,3002859,1,1709389500,2024-03-02 11:25,America/Argentina/Ushuaia,None,None,2.0,3.0,...,-54.8433,732721,"Albatros Hotel - Albatros Hotel,Ushuaia,Argentina",-68.304653,-54.807236,1.0,Sedan,2,,
5,2691904,3303573,1,1718796900,2024-06-19 08:35,America/Argentina/Ushuaia,None,None,4.0,4.0,...,-54.8433,1296024,Los Acebos Ushuaia Hotel - Los Acebos Ushuaia ...,-68.358328,-54.804101,6.0,MPV-4,7,,
6,1784045,3036559,1,1721399100,2024-07-19 11:25,Argentina Standard Time,None,None,3.0,3.0,...,-54.8433,793439,"Alto Andino Hotel - BAR, Gdor. Paz 868, V9410 ...",-68.311036,-54.806209,1.0,Sedan,3,,
7,1971851,3085830,1,1707665100,2024-02-11 12:25,America/Argentina/Ushuaia,None,None,2.0,3.0,...,-54.8433,883525,"Monaco Hotel - Monaco Hotel,Ushuaia,Argentina",-68.316622,-54.809319,1.0,Sedan,2,,
8,2484384,3031625,1,1715521200,2024-05-12 10:40,Argentina Standard Time,None,None,2.0,3.0,...,-54.8433,784484,"Monaco Hotel - Monaco Hotel,Ushuaia,Argentina",-68.316622,-54.809319,1.0,Sedan,10,,
9,1971781,3129228,1,1706542200,2024-01-29 12:30,America/Argentina/Ushuaia,None,None,2.0,3.0,...,-54.8433,959503,"Av. San Martín 1355 - Av. San Martín 1355, V94...",-68.316623,-54.809246,1.0,Sedan,1,,

In [25]:
batch = [dict(zip(cols, row)) for row in data]
batch[:2]

[{'dispatch_id': 2809610,
  'ride_id': 3388335,
  'trip_count': 1,
  'from_utc': 1721070000,
  'from_time_str': '2024-07-15 16:00',
  'from_timezone_str': 'America/Argentina/Ushuaia',
  'to_time_str': None,
  'to_timezone_str': None,
  'passenger_count': 2.0,
  'luggage_count': 3.0,
  'children_count': None,
  'infant_count': None,
  'distance': 6404.0,
  'duration': 777.0,
  'trip_no': 0,
  'dispatch_amount': 11.25,
  'dispatch_currency': 'USD',
  'inserted_at': '2024-06-14 19:23:06.000000',
  'from_cur': 'USD',
  'to_cur': 'USD',
  'rate': 1.0,
  'effective_at': '2024-06-14 19:19:45.000000',
  'expire_at': '2024-06-14 20:19:45.000000',
  'from_date_str': '2024-07-15',
  'from_time_fix_str': '16:00:00',
  'from_datetime_fix_str': '2024-07-15 16:00:00',
  'trip_type_id': 136708097.0,
  'trip_type': 'point2point',
  'ride_status_id': 134610945,
  'ride_status': 'Pending',
  'dispatch_status_id': 134217729,
  'dispatch_status': 'Pending',
  'dispatch_type': 'dispatch',
  'fleet': 'Transporte ushuaia',
  'partner_id': 3,
  'partner': 'Mozio',
  'service_area_id': 895,
  'service_area': 'Ushuaia,Argentina',
  'start_place_id': 1459939,
  'start_place': 'USH',
  'start_lng': -68.2958,
  'start_ltt': -54.8433,
  'end_place_id': 1459940,
  'end_place': 'Canal Beagle Hotel - Av. Maipú 547, V9410 Ushuaia, Tierra del Fuego, Argentina',
  'end_lng': -68.3056405,
  'end_ltt': -54.8073331,
  'vehicle_class_id': 1.0,
  'vehicle_class': 'Sedan',
  'row_num': 1,
  'route_start': '',
  'route_end': ''},
 {'dispatch_id': 2669145,
  'ride_id': 3248608,
  'trip_count': 1,
  'from_utc': 1718376300,
  'from_time_str': '2024-06-14 11:45',
  'from_timezone_str': 'America/Argentina/Ushuaia',
  'to_time_str': None,
  'to_timezone_str': None,
  'passenger_count': 3.0,
  'luggage_count': 3.0,
  'children_count': None,
  'infant_count': None,
  'distance': 6096.0,
  'duration': 734.0,
  'trip_no': 0,
  'dispatch_amount': 11.25,
  'dispatch_currency': 'USD',
  'inserted_at': '2024-05-14 16:05:35.000000',
  'from_cur': 'USD',
  'to_cur': 'USD',
  'rate': 1.0,
  'effective_at': '2024-05-14 15:20:42.000000',
  'expire_at': '2024-05-14 16:20:42.000000',
  'from_date_str': '2024-06-14',
  'from_time_fix_str': '11:45:00',
  'from_datetime_fix_str': '2024-06-14 11:45:00',
  'trip_type_id': 136708097.0,
  'trip_type': 'point2point',
  'ride_status_id': 134610945,
  'ride_status': 'Pending',
  'dispatch_status_id': 134217729,
  'dispatch_status': 'Pending',
  'dispatch_type': 'dispatch',
  'fleet': 'Transporte ushuaia',
  'partner_id': 3,
  'partner': 'Mozio',
  'service_area_id': 895,
  'service_area': 'Ushuaia,Argentina',
  'start_place_id': 1187335,
  'start_place': 'USH',
  'start_lng': -68.2958,
  'start_ltt': -54.8433,
  'end_place_id': 1187336,
  'end_place': 'Mustapic - Mustapic,Ushuaia,Argentina',
  'end_lng': -68.3138896,
  'end_ltt': -54.8074865,
  'vehicle_class_id': 1.0,
  'vehicle_class': 'Sedan',
  'row_num': 1,
  'route_start': '',
  'route_end': ''}]

# Query FP-Server and add label to database

In [ ]:
result = session.execute(
    insert(new_table).values(batch)
)
session.commit()

In [ ]:
chunk_size = 1000
total_rows = len(ordered_rows)
total_rows
total = total_rows//chunk_size+1
total

In [ ]:

for chunk in tqdm(range(total), total=total, desc='Overall Processing'):
    start = chunk*chunk_size
    end = (chunk+1)*chunk_size
    if end > total_rows:
        end = total_rows
    chunk_data = ordered_rows[start:end]
    batch = [dict(zip(cols,row)) for row in chunk_data] 
    result = session.execute(insert(new_table).values(batch))
    session.commit()
    # for row in tqdm(chunk_data, total=len(chunk_data), desc='Chunk Processing'):
    #     session.execute(new_table.insert().values(row))
session.close()

In [ ]:
df = pd.DataFrame(data=ordered_rows)

In [ ]:
for row in tqdm(result, total=unique_count):
    for chunk in tqdm(pd.read_sql(query.statement, conn, index_col='dispatch_id', chunksize=chunk_size), total=total_rows//chunk_size+1, desc='Overall Processing'):
    route_list = []

In [ ]:
with sql_eng.connect() as conn:
    result = conn.execute(ordered_t)
    for row in tqdm(result, total=unique_count):
        session.execute(new_table.insert().values(row))
    session.commit()

In [ ]:
# list(my_table.columns)

In [ ]:
# metadata_new = MetaData()
# my_table.to_metadata(metadata_new)
# metadata_new.tables

In [ ]:
new_table = Table('price_training_raw_2024_usd_geo_ordered', metadata, *my_table.columns)
# list(new_table.columns)
# new_table.name = 'price_training_raw_2024_usd_geo_ordered'
# metadata_new.create_all(sql_eng)

# reduce precision of start_ltt, start_lng, end_ltt, end_lng by 3 digits

In [ ]:
df.loc[:,'route_start'] = 'start'
df

In [ ]:

stmt = (
    update(my_table)  # 'raw' is your table object
    .where(my_table.c.dispatch_id == 822019)
    .values(
        route_start='New Zone C',
        route_end='New Zone D'
    )
)
print(stmt)

In [ ]:
compiled = stmt.compile()
compiled.params

In [ ]:
with sql_eng.connect() as conn:
    result = conn.execute(stmt)
    conn.commit()

In [ ]:
s = select(my_table).where(my_table.c.dispatch_id == 822019)
rp = sql_eng.connect().execute(s)
results = rp.fetchall()
results

In [ ]:
df

In [ ]:
for i,r in df.iterrows():
    l = [i, r['ride_id'], r['dispatch_amount'],r['fleet']]
    # print(r)
    df.at[i,'route_end'] = 'Shanghai'
    stmt = (
        update(my_table)
        .where(my_table.c.dispatch_id == int(i))
        .values(
            route_start='Beijing',
            route_end='Shanghai',
        )
    )
    with sql_eng.connect() as conn:
        conn.execute(stmt)
        conn.commit()
    # print('----')
    print(l)
df

# Update data batchwise in sqlite db

In [ ]:
df.loc[:,'route_start'] = 'Zone 0'
df.loc[:,'route_end'] = 'Zone 1'
df

In [ ]:
stmt = (
    update(my_table)  # 'raw' is your table object
    .where(my_table.c.dispatch_id == bindparam('b_dispatch_id'))
    .values(
        route_start=bindparam('route_start'),
        route_end=bindparam('route_end')
    )
)
print(stmt)

In [ ]:
l = [ 
            {'dispatch_id': i,
             'route_start': r['route_start'],
             'route_end': r['route_end']} 
            for i,r in df.iterrows()
        ]
l

In [ ]:

with sql_eng.begin() as conn:
    conn.execute(
        stmt,
        [ 
            {'b_dispatch_id': i,
             'route_start': r['route_start'],
             'route_end': r['route_end']} 
            for i,r in df.iterrows()
        ],
    )
    conn.commit()

In [ ]:
s = select(my_table).limit(20)
rp = sql_eng.connect().execute(s)
results = rp.fetchall()
df = pd.DataFrame(results)
df

In [ ]:
for i,r in df.iterrows():
    print(i, r['ride_id'], r['dispatch_amount'],r['fleet'])

In [ ]:

# df.to_sql('price_training_raw_2024_usd', sqlite_eng, if_exists= 'replace',index=True, index_label='dispatch_id')

In [ ]:

for r in df.itertuples():
    # print(r)
    print(r.ride_id, r.fleet)
    df.at[r.Index, 'route_start'] = 'PVG'
    # r.route_start = 'start'
    # r.route_end = 'end'
df

In [ ]:

# df.to_sql('price_training_raw_2024_usd', sqlite_eng, if_exists= 'replace',index=True, index_label='dispatch_id')

In [ ]:
#| hide
import nbdev; nbdev.nbdev_export()