# data.database.deduplication
> Geographics coordiantes deduplication after precision reduction in order to get the minimal set of unique geographics coordinates of lower precision of Decimal(9,5) for fixed-priced-zone route label query API

In [38]:
#| default_exp data.database.deduplication

In [39]:
from asyncio import as_completed
from threading import Thread

#| hide
from nbdev.showdoc import *

In [40]:
#| hide
from IPython.core.interactiveshell import InteractiveShell

In [41]:
from tqdm.notebook import tqdm
from sqlalchemy import create_engine, select, func, distinct, MetaData, Table, update, bindparam, Column, insert, desc, asc, and_, or_, not_, Numeric, cast, func
from sqlalchemy.orm import sessionmaker, aliased
import pandas as pd
import numpy as np

In [42]:
#| export
from datetime import datetime
import pytz

In [43]:
from concurrent.futures import ThreadPoolExecutor, as_completed
import httpx
from http import HTTPStatus
from concurrent import futures
from enum import Enum
import requests

In [44]:

#| export
pd.options.mode.chained_assignment = None

In [45]:

InteractiveShell.ast_node_interactivity = "all"

# Precision reduction for start_ltt, start_lng, end_ltt, end_lng and pick distinct values

In [46]:
sql_eng = create_engine('sqlite:///../data/price_tokyo.db', echo=False)
conn = sql_eng.connect()
my_table = Table('price_training_tokyo', MetaData(), autoload_with=sql_eng)
metadata = MetaData()

In [47]:
query = select(func.count(distinct(my_table.c.dispatch_id)))

In [48]:
with sql_eng.connect() as connection:
    result = connection.execute(query)
    unique_count = result.scalar()
    
print(unique_count)

67440

In [49]:
query = select(my_table).limit(10)
df = pd.read_sql(query, conn, index_col='dispatch_id')
# df[['route_start','route_end']]
df

,ride_id,trip_count,ride_inserted_at,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,passenger_count,luggage_count,...,start_ltt,end_place_id,end_place,end_lng,end_ltt,vehicle_class_id,vehicle_class,row_num,route_start,route_end
dispatch_id,,,,,,,,,,,,,,,,,,,,,
4680,2166988,1,2020-10-29 21:41:00.000000,1604239200,2020-11-01 23:00,Japan Standard Time,None,None,1.0,3.0,...,35.771987,2040,Hotel Main Kanda,139.769481,35.689175,1,Sedan,1,,
4724,2167009,1,2020-11-01 02:16:12.000000,1604239200,2020-11-01 23:00,Japan Standard Time,None,None,1.0,3.0,...,35.771987,2057,Koto City,139.817452,35.672775,1,Sedan,1,,
6351,2167772,1,2020-12-23 14:01:24.000000,1608868800,2020-12-25 13:00,Japan Standard Time,None,None,1.0,3.0,...,35.771987,2691,1 Chome-3 Ishikawacho,139.683002,35.601995,1,Sedan,1,,
12562,2171080,1,2021-04-21 23:15:35.000000,1619388000,2021-04-26 07:00,Japan Standard Time,None,None,4.0,10.0,...,35.284527,81,"Tokyo International Airport,",139.779839,35.549393,10,Minibus-12,1,,
25940,2177878,1,2021-06-22 04:49:42.000000,1624442400,2021-06-23 19:00,Asia/Tokyo,None,None,2.0,3.0,...,35.549393,8327,Comforia Shinjuku Eastside Tower,139.708205,35.696093,2,Business Sedan,1,,
25953,2177888,1,2021-06-22 08:27:19.000000,1625551200,2021-07-06 15:00,Asia/Tokyo,None,None,1.0,3.0,...,35.549393,8333,KiLuck,139.627768,35.451921,1,Sedan,1,,
26635,2178127,1,2021-06-23 17:18:03.000000,1624522500,2021-06-24 17:15,Asia/Tokyo,None,None,1.0,3.0,...,35.732941,82,Narita International Airport,140.392850,35.771987,1,Sedan,1,,
39684,2184005,1,2021-07-25 16:30:10.000000,1627354800,2021-07-27 12:00,Asia/Tokyo,None,None,2.0,3.0,...,35.549393,11104,Hiyori Hotel Ginza Higashi,139.773319,35.673644,1,Sedan,1,,
51124,2188968,1,2021-08-20 08:21:58.000000,1629495900,2021-08-21 06:45,Asia/Tokyo,None,None,1.0,3.0,...,35.771987,13339,SAKURA HOUSE Monzen Nakacho,139.791079,35.676564,1,Sedan,1,,
56084,2191084,1,2021-09-04 02:28:26.000000,1630796400,2021-09-05 08:00,Asia/Tokyo,None,None,1.0,5.0,...,35.636373,82,Narita International Airport,140.392850,35.771987,4,Business SUV,1,,

# order by start_ltt, start_lng, end_ltt, end_lng

In [50]:
metadata.reflect(bind=sql_eng)
raw_t = metadata.tables['price_training_tokyo']
s = select(raw_t).limit(10)
rp = sql_eng.connect().execute(s)
df = pd.DataFrame(rp)
df

,dispatch_id,ride_id,trip_count,ride_inserted_at,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,passenger_count,...,start_ltt,end_place_id,end_place,end_lng,end_ltt,vehicle_class_id,vehicle_class,row_num,route_start,route_end
0,4680,2166988,1,2020-10-29 21:41:00.000000,1604239200,2020-11-01 23:00,Japan Standard Time,None,None,1.0,...,35.771987,2040,Hotel Main Kanda,139.769481,35.689175,1,Sedan,1,,
1,4724,2167009,1,2020-11-01 02:16:12.000000,1604239200,2020-11-01 23:00,Japan Standard Time,None,None,1.0,...,35.771987,2057,Koto City,139.817452,35.672775,1,Sedan,1,,
2,6351,2167772,1,2020-12-23 14:01:24.000000,1608868800,2020-12-25 13:00,Japan Standard Time,None,None,1.0,...,35.771987,2691,1 Chome-3 Ishikawacho,139.683002,35.601995,1,Sedan,1,,
3,12562,2171080,1,2021-04-21 23:15:35.000000,1619388000,2021-04-26 07:00,Japan Standard Time,None,None,4.0,...,35.284527,81,"Tokyo International Airport,",139.779839,35.549393,10,Minibus-12,1,,
4,25940,2177878,1,2021-06-22 04:49:42.000000,1624442400,2021-06-23 19:00,Asia/Tokyo,None,None,2.0,...,35.549393,8327,Comforia Shinjuku Eastside Tower,139.708205,35.696093,2,Business Sedan,1,,
5,25953,2177888,1,2021-06-22 08:27:19.000000,1625551200,2021-07-06 15:00,Asia/Tokyo,None,None,1.0,...,35.549393,8333,KiLuck,139.627768,35.451921,1,Sedan,1,,
6,26635,2178127,1,2021-06-23 17:18:03.000000,1624522500,2021-06-24 17:15,Asia/Tokyo,None,None,1.0,...,35.732941,82,Narita International Airport,140.392850,35.771987,1,Sedan,1,,
7,39684,2184005,1,2021-07-25 16:30:10.000000,1627354800,2021-07-27 12:00,Asia/Tokyo,None,None,2.0,...,35.549393,11104,Hiyori Hotel Ginza Higashi,139.773319,35.673644,1,Sedan,1,,
8,51124,2188968,1,2021-08-20 08:21:58.000000,1629495900,2021-08-21 06:45,Asia/Tokyo,None,None,1.0,...,35.771987,13339,SAKURA HOUSE Monzen Nakacho,139.791079,35.676564,1,Sedan,1,,
9,56084,2191084,1,2021-09-04 02:28:26.000000,1630796400,2021-09-05 08:00,Asia/Tokyo,None,None,1.0,...,35.636373,82,Narita International Airport,140.392850,35.771987,4,Business SUV,1,,

## create new table with latitutde and longitude reduced to 5 decimal places

In [51]:
ordered_t = select(my_table).order_by(asc(my_table.c.start_ltt), asc(my_table.c.end_ltt))
ordered_t = ordered_t.select_from(my_table)
ordered_t = ordered_t.alias()

In [52]:
lp_ltt_lng_t = select(ordered_t.c.dispatch_id,
                      cast(ordered_t.c.start_ltt, Numeric(9,5)).label('start_ltt_lp'),
                      cast(ordered_t.c.start_lng, Numeric(9,5)).label('start_lng_lp'),
                      cast(ordered_t.c.end_ltt, Numeric(9,5)).label('end_ltt_lp'),
                      cast(ordered_t.c.end_lng, Numeric(9,5)).label('end_lng_lp'))
lp_ltt_lng_t = lp_ltt_lng_t.select_from(ordered_t)
lp_ltt_lng_t = lp_ltt_lng_t.alias()

In [53]:
distinct_start_lp_t = select(lp_ltt_lng_t.c.dispatch_id, 
                         lp_ltt_lng_t.c.start_ltt_lp,
                         # func.max(lp_ltt_lng_t.c.start_ltt_lp).label('unique_start_ltt_lp'), 
                         # func.max(lp_ltt_lng_t.c.start_lng_lp).label('unique_start_lng_lp'),
                         lp_ltt_lng_t.c.start_lng_lp, 
                         lp_ltt_lng_t.c.end_ltt_lp,
                         lp_ltt_lng_t.c.end_lng_lp
                         ).group_by(lp_ltt_lng_t.c.start_ltt_lp).distinct(lp_ltt_lng_t.c.start_lng_lp)#.subquery()
distinct_start_lp_t = distinct_start_lp_t.alias()

In [54]:
# df = pd.read_sql(distinct_start_lp_t, sql_eng)
# df

In [55]:

distinct_end_lp_t = select(lp_ltt_lng_t.c.dispatch_id, 
                         lp_ltt_lng_t.c.start_ltt_lp,
                         lp_ltt_lng_t.c.start_lng_lp,
                         lp_ltt_lng_t.c.end_ltt_lp,
                         lp_ltt_lng_t.c.end_lng_lp
                         ).group_by(lp_ltt_lng_t.c.end_ltt_lp).distinct(lp_ltt_lng_t.c.end_lng_lp)
distinct_end_lp_t = distinct_end_lp_t.alias()

In [56]:

# df = pd.read_sql(distinct_end_lp_t, sql_eng)
# df

In [57]:
fp_zone_start_t = select(
    ordered_t.c, 
    distinct_start_lp_t.c.start_ltt_lp, 
    distinct_start_lp_t.c.start_lng_lp, 
    distinct_start_lp_t.c.end_ltt_lp, 
    distinct_start_lp_t.c.end_lng_lp
    ).select_from(ordered_t
                  .join(distinct_start_lp_t, 
                        ordered_t.c.dispatch_id == distinct_start_lp_t.c.dispatch_id))
df_start = pd.read_sql(fp_zone_start_t, sql_eng)
df_start

,dispatch_id,ride_id,trip_count,ride_inserted_at,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,passenger_count,...,end_ltt,vehicle_class_id,vehicle_class,row_num,route_start,route_end,start_ltt_lp,start_lng_lp,end_ltt_lp,end_lng_lp
0,1133500,2706735,1,2023-07-23 00:20:29.000000,1690081200,2023-07-23 12:00,Japan Standard Time,None,None,1.0,...,35.682204,1,Sedan,1,,,34.67523,135.44302,35.68220,139.83209
1,2203618,3248629,1,2024-02-21 22:17:57.000000,1708652625,2024-02-23 11:00,Asia/Tokyo,None,None,1.0,...,35.552299,1,Sedan,1,,,34.83150,139.07509,35.55230,139.78000
2,977301,2627012,1,2023-06-12 06:22:11.000000,1688266800,2023-07-02 12:00,Japan Standard Time,None,None,4.0,...,35.636836,3,MPV-5,1,,,34.83160,139.07502,35.63684,139.87816
3,1192663,2680749,1,2023-07-09 08:57:36.000000,1691265600,2023-08-06 05:00,Japan Standard Time,None,None,3.0,...,35.771987,1,Sedan,1,,,34.83233,139.07540,35.77199,140.39285
4,2538533,3409716,1,2024-04-18 14:34:08.000000,1714694400,2024-05-03 09:00,Japan Standard Time,None,None,7.0,...,35.748768,5,Minibus-8,1,,,34.97018,139.09087,35.74877,139.82240
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3189,1491626,2883891,1,2023-10-12 05:57:43.000000,1703127600,2023-12-21 12:00,Asia/Tokyo,None,None,2.0,...,36.932655,7,MPV-6,1,,,36.78548,138.95749,36.93266,138.81110
3190,1827652,3056267,1,2023-12-15 07:33:31.000000,1704661200,2024-01-08 06:00,Asia/Tokyo,None,None,6.0,...,36.643124,7,MPV-6,1,,,36.92068,138.45232,36.64312,138.18864
3191,1826741,3055663,1,2023-12-15 00:37:52.000000,1702782000,2023-12-17 12:00,Asia/Tokyo,None,None,5.0,...,36.704454,7,MPV-6,1,,,36.92397,138.44522,36.70445,137.83602
3192,1775308,3032443,1,2023-12-06 01:50:47.000000,1704660600,2024-01-08 05:50,Asia/Tokyo,None,None,2.0,...,36.845557,7,MPV-6,1,,,36.92439,138.44439,36.84556,138.35866
3193,739545,2512079,1,2023-03-19 16:05:18.000000,1682082000,2023-04-21 22:00,Asia/Tokyo,None,None,2.0,...,36.938390,5,Minibus-8,1,,,36.95073,138.79954,36.93839,138.80355

In [58]:
# df_start.to_sql('price_training_tokyo_start', sql_eng, if_exists='replace', index=True)
# df_start.to_csv('../data/price_training_tokyo_start.csv', index=False)

In [59]:
fp_zone_end_t = select(
    ordered_t.c,
    distinct_end_lp_t.c.start_ltt_lp,
    distinct_end_lp_t.c.start_lng_lp,
    distinct_end_lp_t.c.end_ltt_lp,
    distinct_end_lp_t.c.end_lng_lp
).select_from(ordered_t
              .join(distinct_end_lp_t, 
                    ordered_t.c.dispatch_id == distinct_end_lp_t.c.dispatch_id)
              )
df_end = pd.read_sql(fp_zone_end_t, sql_eng)
df_end

,dispatch_id,ride_id,trip_count,ride_inserted_at,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,passenger_count,...,end_ltt,vehicle_class_id,vehicle_class,row_num,route_start,route_end,start_ltt_lp,start_lng_lp,end_ltt_lp,end_lng_lp
0,585030,2430725,1,2023-01-04 22:06:08.000000,1673080500,2023-01-07 17:35,Japan Standard Time,None,None,1.0,...,NaN,1,Sedan,1,,,35.77257,140.39336,NaN,NaN
1,1107529,2566992,2,2023-05-02 07:37:15.000000,1688372700,2023-07-03 17:25,Asia/Tokyo,2023-07-17 16:00,India Standard Time,5.0,...,28.625018,3,MPV-5,1,,,35.54939,139.77984,28.62502,77.21823
2,2676750,3473304,1,2024-05-16 03:16:52.000000,1715929200,2024-05-17 16:00,Japan Standard Time,None,None,4.0,...,33.628730,5,Minibus-8,1,,,35.54939,139.77984,33.62873,135.94232
3,52905,2189726,1,2021-08-25 07:31:41.000000,1629959400,2021-08-26 15:30,Asia/Tokyo,None,None,1.0,...,34.133324,2,Business Sedan,1,,,35.54939,139.77984,34.13332,-81.46433
4,1720510,3004336,1,2023-11-25 11:15:58.000000,1703808900,2023-12-29 09:15,Asia/Tokyo,None,None,4.0,...,34.432002,7,MPV-6,1,,,36.68937,137.84076,34.43200,135.23039
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4737,1491626,2883891,1,2023-10-12 05:57:43.000000,1703127600,2023-12-21 12:00,Asia/Tokyo,None,None,2.0,...,36.932655,7,MPV-6,1,,,36.78548,138.95749,36.93266,138.81110
4738,739545,2512079,1,2023-03-19 16:05:18.000000,1682082000,2023-04-21 22:00,Asia/Tokyo,None,None,2.0,...,36.938390,5,Minibus-8,1,,,36.95073,138.79954,36.93839,138.80355
4739,30574,2180108,1,2021-07-04 16:11:22.000000,1625472000,2021-07-05 17:00,Japan Standard Time,None,None,1.0,...,38.988908,4,Business SUV,1,,,35.77199,140.39285,38.98891,-80.20393
4740,2291128,3291874,1,2024-03-07 04:47:06.000000,1709971200,2024-03-09 17:00,Asia/Tokyo,None,None,8.0,...,41.568432,5,Minibus-8,1,,,35.77018,140.38432,41.56843,-72.54453
4741,2363672,3327748,1,2024-03-19 02:08:41.000000,1713083400,2024-04-14 17:30,Asia/Tokyo,None,None,5.0,...,55.675742,3,MPV-5,1,,,35.54465,139.76779,55.67574,12.56172

In [60]:
# df_end.to_sql('price_training_tokyo_end', sql_eng, if_exists='replace', index=True)
# df_end.to_csv('../data/price_training_tokyo_end.csv', index=False)

In [66]:
# df_start.to_sql('price_training_raw_2024_usd_start_deduplicated', sql_eng, if_exists='replace', index=True)
start_table = Table('price_training_tokyo_start', metadata, autoload_with=sql_eng)
end_table = Table('price_training_tokyo_end', metadata, autoload_with=sql_eng)
s = select(start_table).limit(10)
# rp =sql_eng.connect().execute(s)
# df = pd.DataFrame(rp)
df = pd.read_sql(s,sql_eng)
df

,index,dispatch_id,ride_id,trip_count,ride_inserted_at,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,...,end_ltt,vehicle_class_id,vehicle_class,row_num,route_start,route_end,start_ltt_lp,start_lng_lp,end_ltt_lp,end_lng_lp
0,0,1133500,2706735,1,2023-07-23 00:20:29.000000,1690081200,2023-07-23 12:00,Japan Standard Time,None,None,...,35.682204,1,Sedan,1,,,34.67523,135.44302,35.68220,139.83209
1,1,2203618,3248629,1,2024-02-21 22:17:57.000000,1708652625,2024-02-23 11:00,Asia/Tokyo,None,None,...,35.552299,1,Sedan,1,,,34.83150,139.07509,35.55230,139.78000
2,2,977301,2627012,1,2023-06-12 06:22:11.000000,1688266800,2023-07-02 12:00,Japan Standard Time,None,None,...,35.636836,3,MPV-5,1,,,34.83160,139.07502,35.63684,139.87816
3,3,1192663,2680749,1,2023-07-09 08:57:36.000000,1691265600,2023-08-06 05:00,Japan Standard Time,None,None,...,35.771987,1,Sedan,1,,,34.83233,139.07540,35.77199,140.39285
4,4,2538533,3409716,1,2024-04-18 14:34:08.000000,1714694400,2024-05-03 09:00,Japan Standard Time,None,None,...,35.748768,5,Minibus-8,1,,,34.97018,139.09087,35.74877,139.82240
5,5,2543715,3411946,1,2024-04-19 14:18:01.000000,1719991800,2024-07-03 16:30,Japan Standard Time,None,None,...,35.771987,9,Minibus-10,1,,,34.97395,139.09232,35.77199,140.39285
6,6,1298792,2789010,1,2023-09-01 09:09:33.000000,1696302000,2023-10-03 12:00,Japan Standard Time,None,None,...,35.680400,5,Minibus-8,1,,,35.09639,139.07178,35.68040,139.76902
7,7,786125,2535302,1,2023-04-06 12:36:46.000000,1680924600,2023-04-08 12:30,Asia/Tokyo,None,None,...,35.419346,1,Sedan,1,,,35.12630,138.91113,35.41935,138.85379
8,8,1200463,2743016,1,2023-08-07 08:17:32.000000,1691638800,2023-08-10 12:40,Asia/Tokyo,None,None,...,35.503636,1,Sedan,1,,,35.14197,138.66360,35.50364,138.76841
9,9,675932,2478996,1,2023-02-21 07:25:30.000000,1681851600,2023-04-19 06:00,Asia/Tokyo,None,None,...,35.549393,2,Business Sedan,1,,,35.20473,139.02164,35.54939,139.77984

In [67]:

query = [select(start_table), select(end_table)]
result_table = ['label_2324_start', 'label_2324_end']

In [69]:

FZPQueryStatus = Enum('FZPQueryStatus', 'JsonError HTTPXStatusError HTTPXError IndexOrKeyError DictError NoFixedPrice Success')
fzp = {'from': None, 'to': None}
def get_one_fixed_zone(start_ltt, start_lng, end_ltt, end_lng) -> FZPQueryStatus:
    global fzp
    params = {
        'from_lat': start_ltt,
        'from_lng': start_lng,
        'to_lat': end_ltt,
        'to_lng': end_lng,
    }
    try:
        # response = requests.get(url=url, params=params)
        response = httpx.get(url=url, params=params)
    except httpx.HTTPStatusError as exc:
        return FZPQueryStatus.HTTPXStatusError
    except Exception as exc:
        return FZPQueryStatus.HTTPXError

    try:
        res = response.json()
    except Exception as exc:
        return FZPQueryStatus.JsonError
    try:
        fix_price_zones = res['fleets'][0]['vehicle_classes'][0]['price_detail']['base_pricing']['fix_price_detail']
    except Exception as exc:
        return FZPQueryStatus.IndexOrKeyError
    # print('4')
    if not isinstance(fix_price_zones,dict):
        return FZPQueryStatus.DictError
    else:
        try:
            fzp['from'] = fix_price_zones['from']
            fzp['to']   = fix_price_zones['to']
            return FZPQueryStatus.Success
        except KeyError as e:
            return FZPQueryStatus.NoFixedPrice

In [70]:
url = 'https://j1j495o5pk.execute-api.us-east-2.amazonaws.com/upncoming/ride-pricings'

In [71]:
csv_file_list = ['../data/price_training_tokyo_start.csv',
             '../data/price_training_tokyo_end.csv']
csv_result_file_list = ['../data/price_training_tokyo_start_result.csv',
                 '../data/price_training_tokyo_end_result.csv']
total_rows = [df_start.shape[0], df_end.shape[0]]
result_csv = '../data/dispatch_fpz_tokyo_label_list.csv'
total_rows

chunk_size = 1000

[3194, 4742]

In [74]:
non_fzp_count = 0
max_concurrent = 96
for t in [1]: #range(2):
    for i,chunk in enumerate(tqdm(pd.read_sql(query[t],conn,index_col='dispatch_id', chunksize=chunk_size),     total=total_rows[t]//chunk_size+1, desc='Overall Progress')):
        chunk = chunk.astype({'route_start': str, 'route_end': str})
        non_fzp_count_chunk = 0
        # get_fixed_zone_chunk(chunk)
        
        with ThreadPoolExecutor(max_workers=max_concurrent) as executor:
            to_do_map = {} # list[futures.Future] = [] 
            # for ind,r in tqdm(chunk.iterrows(),total=chunk_size,desc='chunk progress', leave=False):
            for ind,r in chunk.iterrows():
                future = executor.submit(get_one_fixed_zone, r['start_ltt_lp'], r['start_lng_lp'], r['end_ltt_lp'],     r['end_lng_lp'])
                to_do_map[future] = ind
            done_iter = as_completed(to_do_map)
            done_iter = tqdm(done_iter, total=len(to_do_map), desc='chunk progress', leave=False)
            
            for future in done_iter:
                try:
                    status = future.result()
                except Exception as e:
                    # print(f"Exception: {e}")
                    continue
                
                if status == FZPQueryStatus.Success:
                    ind = to_do_map[future]
                    try:
                        chunk.at[ind, 'route_start'] = fzp['from']
                        chunk.at[ind, 'route_end'] = fzp['to']
                    except KeyError as e:
                        non_fzp_count_chunk += 1
                        # print(f"\r {e}: {non_fzp_count_chunk}/{chunk_size}")
                        continue
                    except Exception as e:
                        non_fzp_count_chunk += 1
                        # print(f"\r {e}: {non_fzp_count_chunk}/{chunk_size}")
                        continue
                else:
                    non_fzp_count_chunk += 1
                    # print(f"\r non fzp chunk: {non_fzp_count_chunk}/{chunk_size}")
                    continue
            
        non_fzp_count += non_fzp_count_chunk
        scanned_row_number = (i+1)*chunk_size
        try:
            # pd.DataFrame(data=route_list, columns=['dispatch_id', 'route_start', 'route_end']).to_csv(result_csv,     mode='a', header=False)
            with open(csv_result_file_list[t], 'a') as f:
                chunk.to_csv(f, header=f.tell()==0,chunksize=chunk_size)
            # chunk.to_csv(path_or_buf=csv_result_file_list[0],mode='a',chunksize=chunk_size)
            # chunk.to_sql(result_table[0], sql_eng, if_exists='append', index=True)
            print(f"\r Non_FZP count: {non_fzp_count}/{scanned_row_number}")
        except Exception as e:
            print(f"\r {e}, Non_FZP count: {non_fzp_count}/{scanned_row_number} ")
            continue

Overall Progress:   0%|          | 0/5 [00:00<?, ?it/s]

chunk progress:   0%|          | 0/1000 [00:00<?, ?it/s]

 Non_FZP count: 42/1000

chunk progress:   0%|          | 0/1000 [00:00<?, ?it/s]

 Non_FZP count: 57/2000

chunk progress:   0%|          | 0/1000 [00:00<?, ?it/s]

 Non_FZP count: 65/3000

chunk progress:   0%|          | 0/1000 [00:00<?, ?it/s]

 Non_FZP count: 84/4000

chunk progress:   0%|          | 0/742 [00:00<?, ?it/s]

 Non_FZP count: 125/5000

In [75]:
#| hide
import nbdev; nbdev.nbdev_export()