# core data

> core utilities for data processing: 
> datetime processing, time zone processing, validity, filtering

In [ ]:
#| default_exp data.utils

In [ ]:
#| hide
from nbdev.showdoc import *

In [ ]:
#| hide
from IPython.core.interactiveshell import InteractiveShell

In [ ]:
#| export
from datetime import datetime
import pandas as pd
import pytz

In [ ]:
from tqdm.notebook import tqdm
from sqlalchemy import create_engine, select, func, distinct, MetaData, Table, update, bindparam, Column, insert, desc, asc, and_, or_, not_, Numeric, cast, func
from sqlalchemy.orm import sessionmaker, aliased
import pandas as pd
import numpy as np

In [ ]:
#| export
pd.options.mode.chained_assignment = None

In [ ]:

InteractiveShell.ast_node_interactivity = "all"

In [ ]:
#| export
def validate_datetime(date_string, format_string):
    """
    Validates if a string is a valid datetime according to the given format.
    """

    try:
        datetime.strptime(date_string, format_string)
        return True
    except ValueError:
        return False
    
def validate_datetime_in_iso_format(date_text):
        try:
            datetime.fromisoformat(date_text)
            return True
        except ValueError:
            # raise ValueError("Incorrect data format, should be YYYY-MM-DD")
            return False

In [ ]:
# Example usage
date_strings = [
    "2023-12-25 24:00:00",
    "2023-12-25 12:60:00.12",
    "2023-12-25 12:10:00",
    "2023-12-25 23:00:00",
    "2011-11-04",
    "20111104",
    "2011-11-04T00:05:23",
    "2011-11-04T00:05:23.283185",
    "20111104T000523",
    "20111104T000523.283185",
    "2011-11-04T00:05:23Z",
    "2011-11-04T00:05:23.283185+08:00",
    "2011-11-04T00:05:23+08:00",
    ]
format_string = "%Y-%m-%d"

for s in date_strings:
    if validate_datetime_in_iso_format(s):
        print(f"{s} is Valid datetime string")
    else:
        print(f"{s} is Invalid datetime string")

2023-12-25 24:00:00 is Invalid datetime string
2023-12-25 12:60:00.12 is Invalid datetime string
2023-12-25 12:10:00 is Valid datetime string
2023-12-25 23:00:00 is Valid datetime string
2011-11-04 is Valid datetime string
20111104 is Valid datetime string
2011-11-04T00:05:23 is Valid datetime string
2011-11-04T00:05:23.283185 is Valid datetime string
20111104T000523 is Valid datetime string
20111104T000523.283185 is Valid datetime string
2011-11-04T00:05:23Z is Valid datetime string
2011-11-04T00:05:23.283185+08:00 is Valid datetime string
2011-11-04T00:05:23+08:00 is Valid datetime string

In [ ]:
df_datetime_str = pd.DataFrame(date_strings)
df_datetime_str.columns = ['datetime']
# df_datetime_str
df_datetime_str['validity'] = df_datetime_str.apply(lambda x: validate_datetime_in_iso_format(x.iloc[0]), axis=1)
df_datetime_str

                            datetime  validity
0                2023-12-25 24:00:00     False
1             2023-12-25 12:60:00.12     False
2                2023-12-25 12:10:00      True
3                2023-12-25 23:00:00      True
4                         2011-11-04      True
5                           20111104      True
6                2011-11-04T00:05:23      True
7         2011-11-04T00:05:23.283185      True
8                    20111104T000523      True
9             20111104T000523.283185      True
10              2011-11-04T00:05:23Z      True
11  2011-11-04T00:05:23.283185+08:00      True
12         2011-11-04T00:05:23+08:00      True

In [ ]:
df_datetime = df_datetime_str[df_datetime_str.apply(lambda x: validate_datetime_in_iso_format(x.iloc[0]), axis=1)]
df_datetime

                            datetime  validity
2                2023-12-25 12:10:00      True
3                2023-12-25 23:00:00      True
4                         2011-11-04      True
5                           20111104      True
6                2011-11-04T00:05:23      True
7         2011-11-04T00:05:23.283185      True
8                    20111104T000523      True
9             20111104T000523.283185      True
10              2011-11-04T00:05:23Z      True
11  2011-11-04T00:05:23.283185+08:00      True
12         2011-11-04T00:05:23+08:00      True

In [ ]:
df_datetime_invalid = df_datetime_str[df_datetime_str.apply(lambda x: not validate_datetime_in_iso_format(x.iloc[0]), axis=1)]
df_datetime_invalid

                 datetime  validity
0     2023-12-25 24:00:00     False
1  2023-12-25 12:60:00.12     False

In [ ]:
df_datetime['datetime']

2                  2023-12-25 12:10:00
3                  2023-12-25 23:00:00
4                           2011-11-04
5                             20111104
6                  2011-11-04T00:05:23
7           2011-11-04T00:05:23.283185
8                      20111104T000523
9               20111104T000523.283185
10                2011-11-04T00:05:23Z
11    2011-11-04T00:05:23.283185+08:00
12           2011-11-04T00:05:23+08:00
Name: datetime, dtype: object

In [ ]:
# df_datetime_str.apply(lambda x: validate_datetime_in_iso_format(x.iloc[0]), axis=1)
df_datetime1 = df_datetime.apply(lambda x: datetime.fromisoformat(x['datetime']), axis=1)
df_datetime1.name = 'datetime'
df_datetime1

2                  2023-12-25 12:10:00
3                  2023-12-25 23:00:00
4                  2011-11-04 00:00:00
5                  2011-11-04 00:00:00
6                  2011-11-04 00:05:23
7           2011-11-04 00:05:23.283185
8                  2011-11-04 00:05:23
9           2011-11-04 00:05:23.283185
10           2011-11-04 00:05:23+00:00
11    2011-11-04 00:05:23.283185+08:00
12           2011-11-04 00:05:23+08:00
Name: datetime, dtype: object

In [ ]:
df_datetime1.loc[0:8]

2           2023-12-25 12:10:00
3           2023-12-25 23:00:00
4           2011-11-04 00:00:00
5           2011-11-04 00:00:00
6           2011-11-04 00:05:23
7    2011-11-04 00:05:23.283185
8           2011-11-04 00:05:23
Name: datetime, dtype: object

In [ ]:
df_no_tz = pd.to_datetime(df_datetime1.loc[0:8])
df_no_tz

2   2023-12-25 12:10:00.000000
3   2023-12-25 23:00:00.000000
4   2011-11-04 00:00:00.000000
5   2011-11-04 00:00:00.000000
6   2011-11-04 00:05:23.000000
7   2011-11-04 00:05:23.283185
8   2011-11-04 00:05:23.000000
Name: datetime, dtype: datetime64[ns]

In [ ]:
#| export
def get_timezone_abbreviation(timezone_name):
    timezone = pytz.timezone(timezone_name)
    now = datetime.now(timezone)
    return now.strftime("%Z")

def validate_timezone_in_iana(timezone_name):
    return timezone_name in pytz.all_timezones

In [ ]:

time_zone_strings = [
    'Eastern Standard Time',
    'Eastern Daylight Time',
    'US/Eastern',
    'US/Daylight',
    'Asia/Shanghai',
    'Asia/Mumbai',
    'America/New_York',
    'Europe/London',
    'America/Los_Angeles',
    'Asia/Kolkata',
    'Europe/London',
    'Asia/Hong_Kong',
    'Asia/Tokyo',
]
df_timezone_str = pd.DataFrame(time_zone_strings)
df_timezone_str.columns = ['timezone']

# df_datetime_str
df_timezone_str['validity'] = df_timezone_str.apply(lambda x: validate_timezone_in_iana(x['timezone']), axis=1)
df_timezone_str

                 timezone  validity
0   Eastern Standard Time     False
1   Eastern Daylight Time     False
2              US/Eastern      True
3             US/Daylight     False
4           Asia/Shanghai      True
5             Asia/Mumbai     False
6        America/New_York      True
7           Europe/London      True
8     America/Los_Angeles      True
9            Asia/Kolkata      True
10          Europe/London      True
11         Asia/Hong_Kong      True
12             Asia/Tokyo      True

In [ ]:
#| export
timezone_fixing_map = {'Eastern Standard Time': 'US/Eastern',
                       'Eastern Daylight Time': 'US/Eastern',
                       'US/Daylight': 'US/Eastern',
                       'Asia/Mumbai': 'Asia/Calcutta',}

In [ ]:
#| export
def fix_timezone(timezone_name):
    return timezone_fixing_map.get(timezone_name, timezone_name)

In [ ]:
for tz in time_zone_strings:
    print(f"{tz} -> {fix_timezone(tz)} -> {get_timezone_abbreviation(fix_timezone(tz))}")

Eastern Standard Time -> US/Eastern -> EDT
Eastern Daylight Time -> US/Eastern -> EDT
US/Eastern -> US/Eastern -> EDT
US/Daylight -> US/Eastern -> EDT
Asia/Shanghai -> Asia/Shanghai -> CST
Asia/Mumbai -> Asia/Calcutta -> IST
America/New_York -> America/New_York -> EDT
Europe/London -> Europe/London -> BST
America/Los_Angeles -> America/Los_Angeles -> PDT
Asia/Kolkata -> Asia/Kolkata -> IST
Europe/London -> Europe/London -> BST
Asia/Hong_Kong -> Asia/Hong_Kong -> HKT
Asia/Tokyo -> Asia/Tokyo -> JST

In [ ]:

df_timezone_unidentified = df_timezone_str[df_timezone_str.apply(lambda x: not validate_timezone_in_iana(x['timezone']), axis=1)]
df_timezone_unidentified

                timezone  validity
0  Eastern Standard Time     False
1  Eastern Daylight Time     False
3            US/Daylight     False
5            Asia/Mumbai     False

In [ ]:

df_timezone_unidentified.apply(lambda x: fix_timezone(x['timezone']), axis=1)

0       US/Eastern
1       US/Eastern
3       US/Eastern
5    Asia/Calcutta
dtype: object

In [ ]:
df_timezone_str['timezone_fixed'] = df_timezone_str.apply(lambda x: fix_timezone(x['timezone']), axis=1)
df_timezone_str

                 timezone  validity       timezone_fixed
0   Eastern Standard Time     False           US/Eastern
1   Eastern Daylight Time     False           US/Eastern
2              US/Eastern      True           US/Eastern
3             US/Daylight     False           US/Eastern
4           Asia/Shanghai      True        Asia/Shanghai
5             Asia/Mumbai     False        Asia/Calcutta
6        America/New_York      True     America/New_York
7           Europe/London      True        Europe/London
8     America/Los_Angeles      True  America/Los_Angeles
9            Asia/Kolkata      True         Asia/Kolkata
10          Europe/London      True        Europe/London
11         Asia/Hong_Kong      True       Asia/Hong_Kong
12             Asia/Tokyo      True           Asia/Tokyo

In [ ]:

df_timezone = df_timezone_str[df_timezone_str.apply(lambda x: validate_timezone_in_iana(x['timezone_fixed']), axis=1)]
df_timezone

                 timezone  validity       timezone_fixed
0   Eastern Standard Time     False           US/Eastern
1   Eastern Daylight Time     False           US/Eastern
2              US/Eastern      True           US/Eastern
3             US/Daylight     False           US/Eastern
4           Asia/Shanghai      True        Asia/Shanghai
5             Asia/Mumbai     False        Asia/Calcutta
6        America/New_York      True     America/New_York
7           Europe/London      True        Europe/London
8     America/Los_Angeles      True  America/Los_Angeles
9            Asia/Kolkata      True         Asia/Kolkata
10          Europe/London      True        Europe/London
11         Asia/Hong_Kong      True       Asia/Hong_Kong
12             Asia/Tokyo      True           Asia/Tokyo

In [ ]:
# extract invalid data
df_timezone_invalid = df_timezone_str[df_timezone_str.apply(lambda x: not validate_timezone_in_iana(x.iloc[0]), axis=1)]
df_timezone_invalid

                timezone  validity timezone_fixed
0  Eastern Standard Time     False     US/Eastern
1  Eastern Daylight Time     False     US/Eastern
3            US/Daylight     False     US/Eastern
5            Asia/Mumbai     False  Asia/Calcutta

In [ ]:
df_abbr = df_timezone.apply(lambda x: get_timezone_abbreviation(x.loc['timezone_fixed']), axis=1)
df_abbr.name = 'abbr'
df_abbr

0     EDT
1     EDT
2     EDT
3     EDT
4     CST
5     IST
6     EDT
7     BST
8     PDT
9     IST
10    BST
11    HKT
12    JST
Name: abbr, dtype: object

In [ ]:
df_timezone

                 timezone  validity       timezone_fixed
0   Eastern Standard Time     False           US/Eastern
1   Eastern Daylight Time     False           US/Eastern
2              US/Eastern      True           US/Eastern
3             US/Daylight     False           US/Eastern
4           Asia/Shanghai      True        Asia/Shanghai
5             Asia/Mumbai     False        Asia/Calcutta
6        America/New_York      True     America/New_York
7           Europe/London      True        Europe/London
8     America/Los_Angeles      True  America/Los_Angeles
9            Asia/Kolkata      True         Asia/Kolkata
10          Europe/London      True        Europe/London
11         Asia/Hong_Kong      True       Asia/Hong_Kong
12             Asia/Tokyo      True           Asia/Tokyo

In [ ]:
# df_timezone_str['validity'] = df_timezone_str.apply(lambda x: validate_timezone_in_iana(x.iloc[0]), axis=1)
# df_timezone['abbr'] = df_timezone.apply(lambda x: get_timezone_abbreviation(x.iloc[0]), axis=1)
# df_timezone.apply(lambda x: get_timezone_abbreviation(x.iloc[0]), axis=1)
df_timezone.loc[:,'abbr'] = df_abbr
df_timezone
# df_timezone

                 timezone  validity       timezone_fixed abbr
0   Eastern Standard Time     False           US/Eastern  EDT
1   Eastern Daylight Time     False           US/Eastern  EDT
2              US/Eastern      True           US/Eastern  EDT
3             US/Daylight     False           US/Eastern  EDT
4           Asia/Shanghai      True        Asia/Shanghai  CST
5             Asia/Mumbai     False        Asia/Calcutta  IST
6        America/New_York      True     America/New_York  EDT
7           Europe/London      True        Europe/London  BST
8     America/Los_Angeles      True  America/Los_Angeles  PDT
9            Asia/Kolkata      True         Asia/Kolkata  IST
10          Europe/London      True        Europe/London  BST
11         Asia/Hong_Kong      True       Asia/Hong_Kong  HKT
12             Asia/Tokyo      True           Asia/Tokyo  JST

In [ ]:

df_utc_offset = (df_timezone.apply(lambda x: datetime.now(pytz.timezone(x.loc['timezone_fixed'])), axis=1)
                            .apply(lambda x: x.strftime('%z')))
df_utc_offset.name = 'utc_offset'
df_utc_offset

0     -0400
1     -0400
2     -0400
3     -0400
4     +0800
5     +0530
6     -0400
7     +0100
8     -0700
9     +0530
10    +0100
11    +0800
12    +0900
Name: utc_offset, dtype: object

In [ ]:

df_timezone.loc[:,'utc_offset'] = df_utc_offset
df_timezone

                 timezone  validity       timezone_fixed abbr utc_offset
0   Eastern Standard Time     False           US/Eastern  EDT      -0400
1   Eastern Daylight Time     False           US/Eastern  EDT      -0400
2              US/Eastern      True           US/Eastern  EDT      -0400
3             US/Daylight     False           US/Eastern  EDT      -0400
4           Asia/Shanghai      True        Asia/Shanghai  CST      +0800
5             Asia/Mumbai     False        Asia/Calcutta  IST      +0530
6        America/New_York      True     America/New_York  EDT      -0400
7           Europe/London      True        Europe/London  BST      +0100
8     America/Los_Angeles      True  America/Los_Angeles  PDT      -0700
9            Asia/Kolkata      True         Asia/Kolkata  IST      +0530
10          Europe/London      True        Europe/London  BST      +0100
11         Asia/Hong_Kong      True       Asia/Hong_Kong  HKT      +0800
12             Asia/Tokyo      True           Asia/Tokyo  JST      +0900

In [ ]:
for tz in df_timezone.loc[:,'timezone_fixed']:
    print(f"{tz}: {datetime.now(pytz.timezone(tz))} - {datetime.now(pytz.timezone(tz)).strftime('%Z')}, {datetime.now(pytz.timezone(tz)).strftime('%z')}")

US/Eastern: 2024-10-24 22:43:09.484754-04:00 - EDT, -0400
US/Eastern: 2024-10-24 22:43:09.484817-04:00 - EDT, -0400
US/Eastern: 2024-10-24 22:43:09.484840-04:00 - EDT, -0400
US/Eastern: 2024-10-24 22:43:09.484857-04:00 - EDT, -0400
Asia/Shanghai: 2024-10-25 10:43:09.484874+08:00 - CST, +0800
Asia/Calcutta: 2024-10-25 08:13:09.484896+05:30 - IST, +0530
America/New_York: 2024-10-24 22:43:09.484915-04:00 - EDT, -0400
Europe/London: 2024-10-25 03:43:09.484936+01:00 - BST, +0100
America/Los_Angeles: 2024-10-24 19:43:09.484953-07:00 - PDT, -0700
Asia/Kolkata: 2024-10-25 08:13:09.484972+05:30 - IST, +0530
Europe/London: 2024-10-25 03:43:09.484990+01:00 - BST, +0100
Asia/Hong_Kong: 2024-10-25 10:43:09.485008+08:00 - HKT, +0800
Asia/Tokyo: 2024-10-25 11:43:09.485027+09:00 - JST, +0900

In [ ]:
for dt,tz in zip(df_no_tz, df_timezone.loc[:,'timezone_fixed']):
    print(f"{dt}: {dt.tz_localize(tz)}, as {dt.tz_localize(tz).astimezone('utc')}")

2023-12-25 12:10:00: 2023-12-25 12:10:00-05:00, as 2023-12-25 17:10:00+00:00
2023-12-25 23:00:00: 2023-12-25 23:00:00-05:00, as 2023-12-26 04:00:00+00:00
2011-11-04 00:00:00: 2011-11-04 00:00:00-04:00, as 2011-11-04 04:00:00+00:00
2011-11-04 00:00:00: 2011-11-04 00:00:00-04:00, as 2011-11-04 04:00:00+00:00
2011-11-04 00:05:23: 2011-11-04 00:05:23+08:00, as 2011-11-03 16:05:23+00:00
2011-11-04 00:05:23.283185: 2011-11-04 00:05:23.283185+05:30, as 2011-11-03 18:35:23.283185+00:00
2011-11-04 00:05:23: 2011-11-04 00:05:23-04:00, as 2011-11-04 04:05:23+00:00

In [ ]:
from zoneinfo import ZoneInfo

In [ ]:
for dt,tz in zip(df_no_tz, df_timezone.loc[:,'timezone_fixed']):
    tz_zone = pytz.timezone(tz)
    print(f"{dt}: {tz_zone.localize(dt)}, or {dt.replace(tzinfo=tz_zone)}, or {dt.tz_localize(tz)}, as {dt.tz_localize(tz).astimezone('utc')}")

2023-12-25 12:10:00: 2023-12-25 12:10:00-05:00, or 2023-12-25 12:10:00-05:00, or 2023-12-25 12:10:00-05:00, as 2023-12-25 17:10:00+00:00
2023-12-25 23:00:00: 2023-12-25 23:00:00-05:00, or 2023-12-25 23:00:00-05:00, or 2023-12-25 23:00:00-05:00, as 2023-12-26 04:00:00+00:00
2011-11-04 00:00:00: 2011-11-04 00:00:00-04:00, or 2011-11-04 00:00:00-04:00, or 2011-11-04 00:00:00-04:00, as 2011-11-04 04:00:00+00:00
2011-11-04 00:00:00: 2011-11-04 00:00:00-04:00, or 2011-11-04 00:00:00-04:00, or 2011-11-04 00:00:00-04:00, as 2011-11-04 04:00:00+00:00
2011-11-04 00:05:23: 2011-11-04 00:05:23+08:00, or 2011-11-04 00:05:23+08:00, or 2011-11-04 00:05:23+08:00, as 2011-11-03 16:05:23+00:00
2011-11-04 00:05:23.283185: 2011-11-04 00:05:23.283185+05:30, or 2011-11-04 00:05:23.283185+05:30, or 2011-11-04 00:05:23.283185+05:30, as 2011-11-03 18:35:23.283185+00:00
2011-11-04 00:05:23: 2011-11-04 00:05:23-04:00, or 2011-11-04 00:05:23-04:00, or 2011-11-04 00:05:23-04:00, as 2011-11-04 04:05:23+00:00

# Convert csv to sqlite db

In [ ]:
sqlite_eng = create_engine('sqlite:///../data/price_tokyo.db', echo=False)

In [ ]:
csv_file_path = '../data/price_training_tokyo.csv'
chunk_size = 10000
total_lines = sum(1 for line in open(csv_file_path))
print(total_lines)

67441

In [ ]:
sample = pd.read_csv(csv_file_path, index_col='dispatch_id', nrows=5)
sample

,ride_id,trip_count,ride_inserted_at,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,passenger_count,luggage_count,...,start_place,start_lng,start_ltt,end_place_id,end_place,end_lng,end_ltt,vehicle_class_id,vehicle_class,row_num
dispatch_id,,,,,,,,,,,,,,,,,,,,,
4680,2166988,1,2020-10-29 21:41:00.000000,1604239200,2020-11-01 23:00,Japan Standard Time,NaN,NaN,1,3,...,Narita International Airport,140.392850,35.771987,2040,Hotel Main Kanda,139.769481,35.689175,1,Sedan,1
4724,2167009,1,2020-11-01 02:16:12.000000,1604239200,2020-11-01 23:00,Japan Standard Time,NaN,NaN,1,3,...,Narita International Airport,140.392850,35.771987,2057,Koto City,139.817452,35.672775,1,Sedan,1
6351,2167772,1,2020-12-23 14:01:24.000000,1608868800,2020-12-25 13:00,Japan Standard Time,NaN,NaN,1,3,...,Narita International Airport,140.392850,35.771987,2691,1 Chome-3 Ishikawacho,139.683002,35.601995,1,Sedan,1
12562,2171080,1,2021-04-21 23:15:35.000000,1619388000,2021-04-26 07:00,Japan Standard Time,NaN,NaN,4,10,...,Navy Gateway Inn & Suites,139.668106,35.284527,81,"Tokyo International Airport,",139.779839,35.549393,10,Minibus-12,1
25940,2177878,1,2021-06-22 04:49:42.000000,1624442400,2021-06-23 19:00,Asia/Tokyo,NaN,NaN,2,3,...,"Tokyo International Airport,",139.779839,35.549393,8327,Comforia Shinjuku Eastside Tower,139.708205,35.696093,2,Business Sedan,1

In [ ]:
for chunk in tqdm(pd.read_csv(csv_file_path, index_col='dispatch_id', chunksize=chunk_size), total=total_lines//chunk_size +1):
# for chunk in tqdm(pd.read_csv(csv_file_path, chunksize=chunk_size), total=total_lines//chunk_size +1):
    data = np.empty((chunk.shape[0],), dtype=[('route_start','U'), ('route_end','U')])
    df_append = pd.DataFrame(index=chunk.index, data=data)
    chunk = pd.concat([chunk, df_append], axis = 1)
    # chunk = chunk.convert_dtypes()
    chunk.to_sql('price_training_tokyo', sqlite_eng, if_exists= 'append',index=True)

  0%|          | 0/7 [00:00<?, ?it/s]

10000

10000

10000

10000

10000

10000

7440

# Precision reduction for start_ltt, start_lng, end_ltt, end_lng and pick distinct values

In [ ]:
sql_eng = create_engine('sqlite:///../data/price_tokyo.db', echo=False)
conn = sql_eng.connect()
my_table = Table('price_training_tokyo', MetaData(), autoload_with=sql_eng)

In [ ]:
query = select(func.count(distinct(my_table.c.dispatch_id)))

In [ ]:
with sql_eng.connect() as connection:
    result = connection.execute(query)
    unique_count = result.scalar()
    
print(unique_count)

67440

In [ ]:
query = select(my_table).limit(10)
df = pd.read_sql(query, conn, index_col='dispatch_id')
# df[['route_start','route_end']]
df

,ride_id,trip_count,ride_inserted_at,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,passenger_count,luggage_count,...,start_ltt,end_place_id,end_place,end_lng,end_ltt,vehicle_class_id,vehicle_class,row_num,route_start,route_end
dispatch_id,,,,,,,,,,,,,,,,,,,,,
4680,2166988,1,2020-10-29 21:41:00.000000,1604239200,2020-11-01 23:00,Japan Standard Time,None,None,1.0,3.0,...,35.771987,2040,Hotel Main Kanda,139.769481,35.689175,1,Sedan,1,,
4724,2167009,1,2020-11-01 02:16:12.000000,1604239200,2020-11-01 23:00,Japan Standard Time,None,None,1.0,3.0,...,35.771987,2057,Koto City,139.817452,35.672775,1,Sedan,1,,
6351,2167772,1,2020-12-23 14:01:24.000000,1608868800,2020-12-25 13:00,Japan Standard Time,None,None,1.0,3.0,...,35.771987,2691,1 Chome-3 Ishikawacho,139.683002,35.601995,1,Sedan,1,,
12562,2171080,1,2021-04-21 23:15:35.000000,1619388000,2021-04-26 07:00,Japan Standard Time,None,None,4.0,10.0,...,35.284527,81,"Tokyo International Airport,",139.779839,35.549393,10,Minibus-12,1,,
25940,2177878,1,2021-06-22 04:49:42.000000,1624442400,2021-06-23 19:00,Asia/Tokyo,None,None,2.0,3.0,...,35.549393,8327,Comforia Shinjuku Eastside Tower,139.708205,35.696093,2,Business Sedan,1,,
25953,2177888,1,2021-06-22 08:27:19.000000,1625551200,2021-07-06 15:00,Asia/Tokyo,None,None,1.0,3.0,...,35.549393,8333,KiLuck,139.627768,35.451921,1,Sedan,1,,
26635,2178127,1,2021-06-23 17:18:03.000000,1624522500,2021-06-24 17:15,Asia/Tokyo,None,None,1.0,3.0,...,35.732941,82,Narita International Airport,140.392850,35.771987,1,Sedan,1,,
39684,2184005,1,2021-07-25 16:30:10.000000,1627354800,2021-07-27 12:00,Asia/Tokyo,None,None,2.0,3.0,...,35.549393,11104,Hiyori Hotel Ginza Higashi,139.773319,35.673644,1,Sedan,1,,
51124,2188968,1,2021-08-20 08:21:58.000000,1629495900,2021-08-21 06:45,Asia/Tokyo,None,None,1.0,3.0,...,35.771987,13339,SAKURA HOUSE Monzen Nakacho,139.791079,35.676564,1,Sedan,1,,
56084,2191084,1,2021-09-04 02:28:26.000000,1630796400,2021-09-05 08:00,Asia/Tokyo,None,None,1.0,5.0,...,35.636373,82,Narita International Airport,140.392850,35.771987,4,Business SUV,1,,

# order by start_ltt, start_lng, end_ltt, end_lng

In [ ]:
sql_eng = create_engine('sqlite:///../data/price_tokyo.db', echo=False)
conn = sql_eng.connect()
metadata = MetaData()
my_table = Table('price_training_tokyo', metadata, autoload_with=sql_eng)

In [ ]:
metadata.reflect(bind=sql_eng)
raw_t = metadata.tables['price_training_tokyo']
s = select(raw_t).limit(10)
rp = sql_eng.connect().execute(s)
df = pd.DataFrame(rp)
df

,dispatch_id,ride_id,trip_count,ride_inserted_at,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,passenger_count,...,start_ltt,end_place_id,end_place,end_lng,end_ltt,vehicle_class_id,vehicle_class,row_num,route_start,route_end
0,4680,2166988,1,2020-10-29 21:41:00.000000,1604239200,2020-11-01 23:00,Japan Standard Time,None,None,1.0,...,35.771987,2040,Hotel Main Kanda,139.769481,35.689175,1,Sedan,1,,
1,4724,2167009,1,2020-11-01 02:16:12.000000,1604239200,2020-11-01 23:00,Japan Standard Time,None,None,1.0,...,35.771987,2057,Koto City,139.817452,35.672775,1,Sedan,1,,
2,6351,2167772,1,2020-12-23 14:01:24.000000,1608868800,2020-12-25 13:00,Japan Standard Time,None,None,1.0,...,35.771987,2691,1 Chome-3 Ishikawacho,139.683002,35.601995,1,Sedan,1,,
3,12562,2171080,1,2021-04-21 23:15:35.000000,1619388000,2021-04-26 07:00,Japan Standard Time,None,None,4.0,...,35.284527,81,"Tokyo International Airport,",139.779839,35.549393,10,Minibus-12,1,,
4,25940,2177878,1,2021-06-22 04:49:42.000000,1624442400,2021-06-23 19:00,Asia/Tokyo,None,None,2.0,...,35.549393,8327,Comforia Shinjuku Eastside Tower,139.708205,35.696093,2,Business Sedan,1,,
5,25953,2177888,1,2021-06-22 08:27:19.000000,1625551200,2021-07-06 15:00,Asia/Tokyo,None,None,1.0,...,35.549393,8333,KiLuck,139.627768,35.451921,1,Sedan,1,,
6,26635,2178127,1,2021-06-23 17:18:03.000000,1624522500,2021-06-24 17:15,Asia/Tokyo,None,None,1.0,...,35.732941,82,Narita International Airport,140.392850,35.771987,1,Sedan,1,,
7,39684,2184005,1,2021-07-25 16:30:10.000000,1627354800,2021-07-27 12:00,Asia/Tokyo,None,None,2.0,...,35.549393,11104,Hiyori Hotel Ginza Higashi,139.773319,35.673644,1,Sedan,1,,
8,51124,2188968,1,2021-08-20 08:21:58.000000,1629495900,2021-08-21 06:45,Asia/Tokyo,None,None,1.0,...,35.771987,13339,SAKURA HOUSE Monzen Nakacho,139.791079,35.676564,1,Sedan,1,,
9,56084,2191084,1,2021-09-04 02:28:26.000000,1630796400,2021-09-05 08:00,Asia/Tokyo,None,None,1.0,...,35.636373,82,Narita International Airport,140.392850,35.771987,4,Business SUV,1,,

In [ ]:
new_columns = [Column(col.name, col.type, primary_key=col.primary_key) for col in my_table.columns]
new_table = Table('price_training_tokyo_reordered', metadata, *new_columns)
new_table.create(sql_eng)
# new_table = Table('price_training_tokyo_reordered', metadata, autoload_with=sql_eng)

In [ ]:
Session = sessionmaker(bind=sql_eng)
session = Session()

## create new table with latitutde and longitude reduced to 5 decimal places

In [ ]:
ordered_t = select(my_table).where(
    and_(
        my_table.c.start_ltt.isnot(None),
        my_table.c.start_lng.isnot(None),
    )
).order_by(asc(my_table.c.start_ltt), asc(my_table.c.start_ltt))
ordered_t = ordered_t.select_from(my_table)
ordered_t = ordered_t.alias()

In [ ]:
# ordered_t = ordered_t.limit(10)
# df = pd.read_sql(ordered_t,sql_eng)
# df

In [ ]:
lp_ltt_lng_t = select(ordered_t.c.dispatch_id,
                      cast(ordered_t.c.start_ltt, Numeric(9,5)).label('start_ltt_lp'),
                      cast(ordered_t.c.start_lng, Numeric(9,5)).label('start_lng_lp'),
                      cast(ordered_t.c.end_ltt, Numeric(9,5)).label('end_ltt_lp'),
                      cast(ordered_t.c.end_lng, Numeric(9,5)).label('end_lng_lp'))
lp_ltt_lng_t = lp_ltt_lng_t.select_from(ordered_t)
lp_ltt_lng_t = lp_ltt_lng_t.alias()

In [ ]:
# df = pd.read_sql(lp_ltt_lng_t, sql_eng)
# df

In [ ]:

distinct_start_lp_t = select(lp_ltt_lng_t.c.dispatch_id, 
                         lp_ltt_lng_t.c.start_ltt_lp,
                         # func.max(lp_ltt_lng_t.c.start_ltt_lp).label('unique_start_ltt_lp'), 
                         # func.max(lp_ltt_lng_t.c.start_lng_lp).label('unique_start_lng_lp'),
                         lp_ltt_lng_t.c.start_lng_lp, 
                         lp_ltt_lng_t.c.end_ltt_lp,
                         lp_ltt_lng_t.c.end_lng_lp
                         ).group_by(lp_ltt_lng_t.c.start_ltt_lp).distinct(lp_ltt_lng_t.c.start_lng_lp)#.subquery()
# distinct_subq_t = distinct_subq_t.limit(100)

In [ ]:

# df = pd.read_sql(distinct_start_lp_t, sql_eng)
# df

In [ ]:

distinct_end_lp_t = select(lp_ltt_lng_t.c.dispatch_id, 
                         lp_ltt_lng_t.c.start_ltt_lp,
                         lp_ltt_lng_t.c.end_ltt_lp,
                         lp_ltt_lng_t.c.end_lng_lp
                         ).group_by(lp_ltt_lng_t.c.end_ltt_lp).distinct(lp_ltt_lng_t.c.end_lng_lp)
distinct_end_lp_t = distinct_end_lp_t.alias()

In [ ]:

# df = pd.read_sql(distinct_end_lp_t, sql_eng)
# df

In [ ]:

# distinct_t = select(distinct(lp_ltt_lng_t.c.start_lng_lp))
# distinct_t = distinct_t.limit(1000)#.distinct(lp_ltt_lng_t.c.start_ltt)
# df = pd.read_sql(distinct_t, sql_eng)
# df

## Create new table with ordered data

In [ ]:
ordered_t = select(my_table).where(
    and_(
        my_table.c.start_ltt.isnot(None),
        my_table.c.start_lng.isnot(None),
    )
).order_by(asc(my_table.c.start_ltt), asc(my_table.c.start_ltt))
ordered_t = ordered_t.select_from(my_table)

In [ ]:
with sql_eng.connect() as conn:
    result = conn.execute(ordered_t)
    ordered_rows = result.fetchall()
# ordered_rows[:3]

In [ ]:
data = ordered_rows[:10]
cols = [c.name for c in ordered_t.subquery().columns]
df = pd.DataFrame(data=data, columns=cols)
df

,dispatch_id,ride_id,trip_count,ride_inserted_at,from_utc,from_time_str,from_timezone_str,to_time_str,to_timezone_str,passenger_count,...,start_ltt,end_place_id,end_place,end_lng,end_ltt,vehicle_class_id,vehicle_class,row_num,route_start,route_end
0,1133500,2706735,1,2023-07-23 00:20:29.000000,1690081200,2023-07-23 12:00,Japan Standard Time,None,None,1.0,...,34.675233,234479,北砂５丁目団地３号棟,139.832095,35.682204,1,Sedan,1,,
1,1133602,2706735,1,2023-07-23 00:20:29.000000,1690081200,2023-07-23 12:00,Japan Standard Time,None,None,1.0,...,34.675233,234479,北砂５丁目団地３号棟,139.832095,35.682204,1,Sedan,1,,
2,1133485,2706735,1,2023-07-23 00:20:29.000000,1690081200,2023-07-23 12:00,Japan Standard Time,None,None,1.0,...,34.675233,234479,北砂５丁目団地３号棟,139.832095,35.682204,1,Sedan,1,,
3,1133600,2706735,1,2023-07-23 00:20:29.000000,1690081200,2023-07-23 12:00,Japan Standard Time,None,None,1.0,...,34.675233,234479,北砂５丁目団地３号棟,139.832095,35.682204,1,Sedan,1,,
4,2203618,3248629,1,2024-02-21 22:17:57.000000,1708652625,2024-02-23 11:00,Asia/Tokyo,None,None,1.0,...,34.831497,1187377,Haneda Airport,139.779999,35.552299,1,Sedan,1,,
5,2203796,3248629,1,2024-02-21 22:17:57.000000,1708652625,2024-02-23 11:00,Asia/Tokyo,None,None,1.0,...,34.831497,1187377,Haneda Airport,139.779999,35.552299,1,Sedan,1,,
6,977301,2627012,1,2023-06-12 06:22:11.000000,1688266800,2023-07-02 12:00,Japan Standard Time,None,None,4.0,...,34.831600,88117,Tokyo Disneyland Hotel,139.878159,35.636836,3,MPV-5,1,,
7,1041223,2627012,1,2023-06-12 06:22:11.000000,1688266800,2023-07-02 12:00,Japan Standard Time,None,None,4.0,...,34.831600,88117,Tokyo Disneyland Hotel,139.878159,35.636836,3,MPV-5,1,,
8,1192663,2680749,1,2023-07-09 08:57:36.000000,1691265600,2023-08-06 05:00,Japan Standard Time,None,None,3.0,...,34.832327,82,Narita International Airport,140.392850,35.771987,1,Sedan,1,,
9,1079793,2680749,1,2023-07-09 08:57:36.000000,1691265600,2023-08-06 05:00,Japan Standard Time,None,None,3.0,...,34.832327,82,Narita International Airport,140.392850,35.771987,1,Sedan,1,,

In [ ]:
#| hide
import nbdev; nbdev.nbdev_export()